{
  "hash": "56b5017cd607b59dbc8c47e94bd3c5e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands on Exercise 05\"\nauthor: \"Gautamgovan\"\ndate: \"Sep 25, 2025\"\ndate-modified: \"last-modified\"\nformat: \n  html:\n    toc: true\n    toc-depth: 4 \n    number-sections: true\n    \nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true \n---\n## Global Measures of Spatial Autocorrelation\n\n### Overview\n\nIn this hands-on exercise, we will learn how to compute **Global Measures of Spatial Autocorrelation (GMSA)** using the **spdep** package.  \nBy the end of this exercise, you will be able to:\n\n- Import geospatial data using appropriate functions from the **sf** package.\n- Import CSV files using appropriate functions from the **readr** package.\n- Perform relational joins using appropriate join functions from the **dplyr** package.\n- Compute Global Spatial Autocorrelation (GSA) statistics using functions from the **spdep** package:\n  - Plot a Moran scatterplot.\n  - Compute and plot a spatial correlogram using functions from the **spdep** package.\n- Provide a statistically correct interpretation of GSA statistics.\n\n### Getting Started\n\n#### The analytical question\nIn spatial policy, one of the main development objective of the local government and planners is to ensure equal distribution of development in the province. Our task in this study, hence, is to apply appropriate spatial statistical methods to discover if development are even distributed geographically. If the answer is No. Then, our next question will be “is there sign of spatial clustering?”. And, if the answer for this question is yes, then our next question will be “where are these clusters?”\n\nIn this case study, we are interested to examine the spatial pattern of a selected development indicator (i.e. GDP per capita) of Hunan Provice, People Republic of China.\n\n#### The Study Area\nTwo data sets will be used in this hands-on exercise, they are:\n\n- Hunan province administrative boundary layer at county level. This is a geospatial data set in ESRI shapefile format.\n- Hunan_2012.csv: This csv file contains selected Hunan’s local development indicators in 2012.\n\n#### Setting the Analytical Tools\n\nBefore we get started, we need to ensure that the **spdep**, **sf**, **tmap**, and **tidyverse** packages of R are installed in your environment.\n\n- **sf**: for importing and handling geospatial data in R.  \n- **tidyverse**: for wrangling attribute data in R.  \n- **spdep**: for computing spatial weights and performing global and local spatial autocorrelation analysis.  \n- **tmap**: for preparing cartographic-quality choropleth maps.\n\nThe following code chunk will:\n\n- Create a package list containing the required R packages.\n- Check whether the packages in the list are installed:\n  - If not installed, RStudio will install the missing packages automatically.\n- Load the packages into the R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse)\n```\n:::\n\n\n### Getting the Data Into R Environment\nIn this section, you will learn how to bring a geospatial data and its associated attribute table into R environment. The geospatial data is in ESRI shapefile format and the attribute table is in csv fomat.\n\n####  Import shapefile into r environment\n\nThe code chunk below uses st_read() of sf package to import Hunan shapefile into R. The imported shapefile will be simple features Object of sf.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", \n                 layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `C:\\govanzz\\ISSS626_GEO_AUG_2025\\Hands-on_Ex\\Hands-on_Ex05\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n#### Import csv file into r environment\n\nNext, we will import Hunan_2012.csv into R by using read_csv() of readr package. The output is R data frame class.\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n\n#### Performing relational join\nThe code chunk below will be used to update the attribute table of hunan’s SpatialPolygonsDataFrame with the attribute fields of hunan2012 dataframe. This is performed by using left_join() of dplyr package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan2012) %>%\n  select(1:4, 7, 15)\n```\n:::\n\n#### Visualising Regional Development Indicator\nNow, we are going to prepare a basemap and a choropleth map showing the distribution of GDPPC 2012 by using qtm() of tmap package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Equal interval classification\")\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5)) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Quantile classification\")\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n### Global Measures of Spatial Autocorrelation\nIn this section, we will learn how to compute global spatial autocorrelation statistics and to perform spatial complete randomness test for global spatial autocorrelation.\n\n#### Computing Contiguity Spatial Weights\nBefore we can compute the global spatial autocorrelation statistics, we need to construct a spatial weights of the study area. The spatial weights is used to define the neighbourhood relationships between the geographical units (i.e. county) in the study area.\n\nIn the code chunk below, poly2nb() of spdep package is used to compute contiguity weight matrices for the study area. This function builds a neighbours list based on regions with contiguous boundaries. If you look at the documentation you will see that you can pass a “queen” argument that takes TRUE or FALSE as options. If you do not specify this argument the default is set to TRUE, that is, if you don’t specify queen = FALSE this function will return a list of first order neighbours using the Queen criteria.\n\nMore specifically, the code chunk below is used to compute Queen contiguity weight matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, \n                queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\nThe summary report above shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one neighbours.\n\n#### Row-standardised weights matrix\n\nNext, we need to assign weights to each neighboring polygon. In our case, each neighboring polygon will be assigned equal weight (style=“W”). This is accomplished by assigning the fraction 1/(#ofneighbors) to each neighboring county then summing the weighted income values. While this is the most intuitive way to summaries the neighbors’ values it has one drawback in that polygons along the edges of the study area will base their lagged values on fewer polygons thus potentially over- or under-estimating the true nature of the spatial autocorrelation in the data. For this example, we’ll stick with the style=“W” option for simplicity’s sake but note that other more robust options are available, notably style=“B”.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, \n                   style=\"W\", \n                   zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n### Global Measures of Spatial Autocorrelation: Moran’s I\n\nIn this section, we will learn how to perform **Moran’s I** statistics testing by using [`moran.test()`](https://r-spatial.github.io/spdep/reference/moran.test.html) of **spdep**.\n\n#### Maron’s I test\n\nThe code chunk below performs Moran’s I statistical testing using [`moran.test()`](https://r-spatial.github.io/spdep/reference/moran.test.html) of spdep.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC, \n           listw=rswm_q, \n           zero.policy = TRUE, \n           na.action=na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\nThe Moran’s I test shows I = 0.3007 with z = 4.735 and p = 1.095e-06 (alternative = “greater”). \nWe therefore reject the null hypothesis of no spatial autocorrelation and conclude there is significant positive spatial autocorrelation in GDP per capita across Hunan counties—neighboring counties tend to have similar GDPPC values (high-with-high, low-with-low). \nThe magnitude (~0.30) suggests moderate clustering rather than randomness.\n\n#### Computing Monte Carlo Moran’s I\n\nThe code chunk below performs a permutation test for **Moran’s I** statistic by using [`moran.mc()`](https://r-spatial.github.io/spdep/reference/moran.mc.html) of **spdep**. A total of **1000 simulations** will be performed.\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(hunan$GDPPC, \n                listw=rswm_q, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\nThe permutation test shows a Moran’s I = 0.30075 with a p-value = 0.001, which is far below the typical significance level (e.g., 0.05). \n\n- Therefore, we reject the null hypothesis of spatial randomness.\n\n- This indicates that GDP per capita values across Hunan counties exhibit significant      positive spatial autocorrelation, meaning areas with high (or low) GDPPC tend to         cluster near each other rather than being randomly distributed.\n\n####  Visualising Monte Carlo Moran’s I\n\nIt is always good practice to examine the simulated **Moran’s I** test statistics in greater detail. This can be done by plotting the distribution as a histogram using the code chunk below.\n\nIn the code below, base R’s [`hist()`](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/hist.html) and [`abline()`](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/abline.html) are used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, \n     freq=TRUE, \n     breaks=20, \n     xlab=\"Simulated Moran's I\")\nabline(v=0, \n       col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n**Statistical observation**\n\n- The permutation distribution of Moran’s I is centered near **0** (mean ≈ **–0.015**, var ≈ **0.00437**), as expected under spatial randomness.\n- The **observed Moran’s I = 0.30075** lies far in the **right tail** of this distribution.\n- The Monte-Carlo **p-value = 0.001**, so we **reject H₀ (no spatial autocorrelation)** and conclude **significant positive spatial autocorrelation** in GDPPC.\n\n\n**ggplot2 version of the histogram**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# sims: the permutation distribution; obs: observed Moran's I\nsims <- bperm$res[1:999]                 # 999 simulated values\nobs  <- as.numeric(bperm$statistic)      # observed Moran's I\np_emp <- mean(sims >= obs)               # empirical one-sided p-value\n\ndf <- data.frame(sim = sims)\n\nggplot(df, aes(x = sim)) +\n  geom_histogram(bins = 30, fill = \"grey40\", color = \"black\") +\n  geom_vline(xintercept = 0, color = \"red\", linewidth = 1) +\n  geom_vline(xintercept = obs, linetype = \"dashed\", color = \"blue\", linewidth = 1) +\n  expand_limits(x = obs) +\n  labs(\n    title = \"Permutation Distribution of Moran's I\",\n    x = \"Simulated Moran's I\",\n    y = \"Count\",\n    subtitle = paste0(\"Observed I = \", round(obs, 5),\n                      \" | Empirical p = \", signif(p_emp, 3))\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n### Global Measures of Spatial Autocorrelation: Geary’s C\n\nIn this section, we will learn how to perform Geary’s C statistics testing by using appropriate functions of spdep package.\n\n#### Geary's C test\nThe code chunk below performs Geary’s C test for spatial autocorrelation by using geary.test() of spdep.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw=rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n**Statistical conclusion**\n\n- The Geary’s C test produced a statistic of **0.6907**, which is **significantly lower than 1** (the expected value under spatial randomness).  \n- The associated **p-value = 0.0001526** is much less than 0.05, so we **reject the null hypothesis** of no spatial autocorrelation.  \n- A Geary’s C value below 1 indicates **positive spatial autocorrelation**, meaning that counties with similar GDP per capita values are spatially clustered together.  \n- This result supports the conclusion that **GDPPC values are not randomly distributed**, but instead show **spatial dependence and similarity among neighboring regions**.\n\n#### Computing Monte Carlo Geary’s C\nThe code chunk below performs permutation test for Geary’s C statistic by using geary.mc() of spdep.\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm=geary.mc(hunan$GDPPC, \n               listw=rswm_q, \n               nsim=999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n**Statistical conclusion**\n\n- The Monte Carlo permutation test for Geary’s C produced a statistic of **0.69072**, which is significantly lower than the expected value of **1** under spatial randomness.  \n- The **p-value = 0.001** indicates strong evidence against the null hypothesis of no spatial autocorrelation.  \n- Since the observed Geary’s C is less than 1, we conclude that there is **significant positive spatial autocorrelation** in GDP per capita.  \n- This means that regions with similar GDPPC values tend to be **spatially clustered**, rather than randomly distributed across Hunan province.\n\n#### Visualising the Monte Carlo Geary’s C\n\nNext, we will plot a histogram to reveal the distribution of the simulated values by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, freq=TRUE, breaks=20, xlab=\"Simulated Geary c\")\nabline(v=1, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n**Statistical observation**\n\n- The permutation distribution of Geary’s C is centered near **1.0044**, which is close to the expected value of **1** under spatial randomness.  \n- The observed Geary’s C statistic (**0.69072**) is located far to the **left tail** of the simulated distribution, indicating it is significantly lower than expected by chance.  \n- Since the observed statistic is much less than 1, we **reject the null hypothesis** of no spatial autocorrelation.  \n- This provides strong evidence of **positive spatial autocorrelation**, meaning that regions with similar GDP per capita values are **spatially clustered** rather than randomly distributed.\n\n### Spatial Correlogram\nSpatial correlograms are great to examine patterns of spatial autocorrelation indata or model residuals. They show how correlated are pairs of spatial observations when you increase the distance (lag) between them - they are plots of some index of autocorrelation (Moran’s I or Geary’s c) against distance.Although correlograms are not as fundamental as variograms (a keystone concept of geostatistics), they are very useful as an exploratory and descriptive tool. For this purpose they actually provide richer information than variograms.\n\n#### Compute Moran’s I correlogram\n\nIn the code chunk below, sp.correlogram() of spdep package is used to compute a 6-lag spatial correlogram of GDPPC. The global spatial autocorrelation used in Moran’s I. The plot() of base Graph is then used to plot the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"I\", \n                          style=\"W\")\nplot(MI_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\nBy plotting the output might not allow us to provide complete interpretation. This is because not all autocorrelation values are statistically significant. Hence, it is important for us to examine the full analysis report by printing out the analysis results as in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(MI_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       2.189e-06 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       2.029e-06 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496        0.040400 *  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107        0.226015    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       5.984e-05 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164        0.008886 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n**Statistical observation**\n\n- The Moran’s I correlogram shows how spatial autocorrelation of GDP per capita changes with increasing spatial lags.  \n- For the first and second lags, Moran’s I values (**0.3008** and **0.2060**) are **positive and statistically significant (p < 0.001)**, indicating **strong positive spatial autocorrelation** — nearby regions tend to have similar GDPPC values.  \n- At the third lag (**0.0668**), Moran’s I remains positive but the strength of autocorrelation decreases and is only **marginally significant**.  \n- Beyond the fourth lag, Moran’s I values become **insignificant or negative**, with significant negative values at the fifth (**–0.1530**) and sixth (**–0.1187**) lags, suggesting **spatial dispersion or dissimilarity** at larger distances.  \n- Overall, this pattern indicates that **positive spatial clustering is strongest at short distances**, but **weakens and turns negative as distance increases**, revealing a spatial structure where similarity diminishes with spatial separation.\n\n#### Compute Geary’s C correlogram and plot\nIn the code chunk below, sp.correlogram() of spdep package is used to compute a 6-lag spatial correlogram of GDPPC. The global spatial autocorrelation used in Geary’s C. The plot() of base Graph is then used to plot the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGC_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"C\", \n                          style=\"W\")\nplot(GC_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex05_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\nSimilar to the previous step, we will print out the analysis report by using the code chunk below.\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(GC_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided    \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108       0.0003052 ***\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811       0.0007220 ***\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610       0.3892612    \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564       0.8757128    \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673       0.0007592 ***\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151       0.3100407    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n**Statistical conclusion**\n\n- The Geary’s C correlogram provides insight into how spatial autocorrelation changes across increasing spatial lags.  \n- At lower lags (e.g., lag 1 and 2), Geary’s C values are **significantly less than 1**, indicating **strong positive spatial autocorrelation** — nearby regions tend to have similar GDP per capita values.  \n- As the spatial lag increases, the Geary’s C statistic approaches or exceeds **1**, suggesting that spatial autocorrelation weakens and may transition towards randomness or even **negative autocorrelation**.  \n- This pattern confirms that spatial dependence is strongest at **short distances** and gradually diminishes as the spatial separation between regions increases.\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "Hands-on_Ex05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}