<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gautamgovan">
<meta name="dcterms.date" content="2025-09-13">

<title>Take Home Exercise 1 – ISSS626</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In Class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Exercise/In-class_Ex03/In-class_Ex03a.html">
 <span class="dropdown-text">In Class Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Exercise/In-class-Ex03b.html">
 <span class="dropdown-text">In Class Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Exercise/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In Class Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take Home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take_Home_Exercise/Take_Home_Ex01/Take_Home_Ex01.html">
 <span class="dropdown-text">Take Home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">2</span> The Data</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">2.1</span> Data sources</a></li>
  <li><a href="#fields-used-acra" id="toc-fields-used-acra" class="nav-link" data-scroll-target="#fields-used-acra"><span class="header-section-number">2.2</span> Fields used (ACRA)</a></li>
  <li><a href="#study-coverage" id="toc-study-coverage" class="nav-link" data-scroll-target="#study-coverage"><span class="header-section-number">2.3</span> Study coverage</a></li>
  <li><a href="#pre-processing-wrangling-summary" id="toc-pre-processing-wrangling-summary" class="nav-link" data-scroll-target="#pre-processing-wrangling-summary"><span class="header-section-number">2.4</span> Pre-processing &amp; wrangling (summary)</a></li>
  <li><a href="#data-quality-limitations" id="toc-data-quality-limitations" class="nav-link" data-scroll-target="#data-quality-limitations"><span class="header-section-number">2.5</span> Data quality &amp; limitations</a></li>
  <li><a href="#coordinate-reference-systems-crs" id="toc-coordinate-reference-systems-crs" class="nav-link" data-scroll-target="#coordinate-reference-systems-crs"><span class="header-section-number">2.6</span> Coordinate reference systems (CRS)</a></li>
  <li><a href="#ethicalusage-notes" id="toc-ethicalusage-notes" class="nav-link" data-scroll-target="#ethicalusage-notes"><span class="header-section-number">2.7</span> Ethical/usage notes</a></li>
  </ul></li>
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link" data-scroll-target="#load-packages"><span class="header-section-number">3</span> Load Packages</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">4</span> Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#preparing-the-subzone-boundary-why-how" id="toc-preparing-the-subzone-boundary-why-how" class="nav-link" data-scroll-target="#preparing-the-subzone-boundary-why-how"><span class="header-section-number">4.1</span> Preparing the Subzone Boundary (why &amp; how)</a></li>
  <li><a href="#load-tidy-acra" id="toc-load-tidy-acra" class="nav-link" data-scroll-target="#load-tidy-acra"><span class="header-section-number">4.2</span> Load &amp; Tidy Acra</a></li>
  <li><a href="#select-the-3-industries" id="toc-select-the-3-industries" class="nav-link" data-scroll-target="#select-the-3-industries"><span class="header-section-number">4.3</span> Select the 3 Industries</a></li>
  <li><a href="#geocode-unique-postcodes-with-onemap" id="toc-geocode-unique-postcodes-with-onemap" class="nav-link" data-scroll-target="#geocode-unique-postcodes-with-onemap"><span class="header-section-number">4.4</span> Geocode unique postcodes with OneMap</a></li>
  <li><a href="#convert-to-sf-project-to-svy21-and-join-subzones" id="toc-convert-to-sf-project-to-svy21-and-join-subzones" class="nav-link" data-scroll-target="#convert-to-sf-project-to-svy21-and-join-subzones"><span class="header-section-number">4.5</span> Convert to sf, project to SVY21, and join subzones</a></li>
  <li><a href="#load-precomputed-outputs" id="toc-load-precomputed-outputs" class="nav-link" data-scroll-target="#load-precomputed-outputs"><span class="header-section-number">4.6</span> Load precomputed outputs</a></li>
  <li><a href="#quick-sanity-check" id="toc-quick-sanity-check" class="nav-link" data-scroll-target="#quick-sanity-check"><span class="header-section-number">4.7</span> Quick sanity check</a></li>
  <li><a href="#removing-unwanted-planning-areas" id="toc-removing-unwanted-planning-areas" class="nav-link" data-scroll-target="#removing-unwanted-planning-areas"><span class="header-section-number">4.8</span> Removing unwanted planning areas</a></li>
  </ul></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda"><span class="header-section-number">5</span> EDA</a>
  <ul class="collapse">
  <li><a href="#top-planning-areas-per-sector" id="toc-top-planning-areas-per-sector" class="nav-link" data-scroll-target="#top-planning-areas-per-sector"><span class="header-section-number">5.1</span> Top Planning Areas per sector</a></li>
  <li><a href="#subzone-coverage-check-how-many-subzones-have-1-registration-by-sector" id="toc-subzone-coverage-check-how-many-subzones-have-1-registration-by-sector" class="nav-link" data-scroll-target="#subzone-coverage-check-how-many-subzones-have-1-registration-by-sector"><span class="header-section-number">5.2</span> Subzone coverage check: how many subzones have ≥1 registration (by sector)</a></li>
  <li><a href="#choroplethcounts-by-planning-area-and-subzone" id="toc-choroplethcounts-by-planning-area-and-subzone" class="nav-link" data-scroll-target="#choroplethcounts-by-planning-area-and-subzone"><span class="header-section-number">5.3</span> Choropleth:counts By Planning Area and Subzone</a></li>
  </ul></li>
  <li><a href="#st-order-spatio-temporal-analysis" id="toc-st-order-spatio-temporal-analysis" class="nav-link" data-scroll-target="#st-order-spatio-temporal-analysis"><span class="header-section-number">6</span> 1st Order Spatio Temporal Analysis</a>
  <ul class="collapse">
  <li><a href="#clarkevans-test-per-sector" id="toc-clarkevans-test-per-sector" class="nav-link" data-scroll-target="#clarkevans-test-per-sector"><span class="header-section-number">6.1</span> Clark–Evans test per sector</a></li>
  <li><a href="#spatial-intensity-of-fb-ssic-56-business-registrations" id="toc-spatial-intensity-of-fb-ssic-56-business-registrations" class="nav-link" data-scroll-target="#spatial-intensity-of-fb-ssic-56-business-registrations"><span class="header-section-number">6.2</span> Spatial Intensity of F&amp;B (SSIC 56) Business Registrations</a></li>
  <li><a href="#spatial-intensity-of-it-services-ssic-62-business-registrations" id="toc-spatial-intensity-of-it-services-ssic-62-business-registrations" class="nav-link" data-scroll-target="#spatial-intensity-of-it-services-ssic-62-business-registrations"><span class="header-section-number">6.3</span> Spatial Intensity of IT Services (SSIC 62) Business Registrations</a></li>
  <li><a href="#spatial-intensity-of-logistics-services-ssic-52-business-registrations" id="toc-spatial-intensity-of-logistics-services-ssic-52-business-registrations" class="nav-link" data-scroll-target="#spatial-intensity-of-logistics-services-ssic-52-business-registrations"><span class="header-section-number">6.4</span> Spatial Intensity of Logistics Services (SSIC 52) Business Registrations</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take Home Exercise 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gautamgovan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 13, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 23, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="overview"><span class="header-section-number">1</span> Overview</h2>
<p>This take-home exercise investigates the <strong>spatial</strong> (“where”) and <strong>spatio-temporal</strong> (“where + when”) patterns of <strong>new business registrations in Singapore</strong> between <strong>1 Jan 2024 and 30 Jun 2025</strong>. Using the ACRA “Information on Corporate Entities” datasets and SSIC 2020 classifications, we select at least <strong>three business types</strong> (2- or 3-digit SSIC) and analyse how their locations and intensities evolve over time.</p>
<p>Our workflow mirrors the point-pattern framework taught in class:</p>
<ul>
<li><strong>Data wrangling &amp; geocoding:</strong> tidy ACRA records, standardise dates/SSIC codes, and geocode by postal code via OneMap; convert to <code>sf</code> with SVY21 (EPSG:3414).</li>
<li><strong>Exploratory mapping:</strong> counts by subzone/planning area to establish baseline patterns.</li>
<li><strong>First-order analysis (intensity):</strong> <strong>Kernel Density Estimation (KDE)</strong> to reveal spatial hot spots for each SSIC and period.</li>
<li><strong>Second-order analysis (dependence):</strong> <strong>Ripley’s K / CSR envelopes</strong> to test whether registrations are clustered, random, or dispersed.</li>
<li><strong>Spatio-temporal analysis:</strong> <strong>STKDE</strong> (monthly slices) to detect <strong>emerging, persistent, and fading</strong> clusters over the study window.</li>
</ul>
<p>The results are communicated through cartographic maps and concise figure captions words , followed by a synthesis translating findings into <strong>urban land-use and economic development implications</strong>—e.g., infrastructure readiness, zoning flexibility, activation of under-served subzones, and monitoring of over-concentration risks.</p>
</section>
<section id="the-data" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="the-data"><span class="header-section-number">2</span> The Data</h2>
<p>This study uses ACRA corporate entity registrations combined with reference layers and services to enable spatial and spatio-temporal analysis.</p>
<section id="data-sources" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">2.1</span> Data sources</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset Name</th>
<th>Description</th>
<th>Format</th>
<th>Provider</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>ACRA – Information on Corporate Entities (A–Z, Others)</strong></td>
<td>All entity registrations. Used to extract new businesses by SSIC and date.</td>
<td>CSV (27 files)</td>
<td>data.gov.sg / ACRA</td>
<td>Split alphabetically: A–Z plus a 27th file for names starting with digits/symbols.</td>
</tr>
<tr class="even">
<td><strong>SSIC 2020</strong></td>
<td>Singapore Standard Industrial Classification; used to choose business types (2-/3-/5-digit).</td>
<td>CSV/XLSX</td>
<td>SingStat</td>
<td>We derive <code>ssic2</code>, <code>ssic3</code> and use <code>primary_ssic_code</code>.</td>
</tr>
<tr class="odd">
<td><strong>OneMap Search API</strong></td>
<td>Geocoding service to convert postal codes to coordinates.</td>
<td>Web API</td>
<td>SLA / OneMap</td>
<td>Returns WGS84 (lat/lon). We transform to SVY21 (EPSG:3414).</td>
</tr>
<tr class="even">
<td><strong>Master Plan Subzones (MPSZ 2024)</strong></td>
<td>Administrative subzone polygons for aggregation and mapping.</td>
<td>GPKG/Shapefile</td>
<td>data.gov.sg / URA/SLA</td>
<td>Reprojected to SVY21 (EPSG:3414) for analysis.</td>
</tr>
</tbody>
</table>
</section>
<section id="fields-used-acra" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="fields-used-acra"><span class="header-section-number">2.2</span> Fields used (ACRA)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Meaning</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>uen</code></td>
<td>Unique Entity Number (entity identifier)</td>
<td>201912345K</td>
</tr>
<tr class="even">
<td><code>entity_name</code></td>
<td>Registered business name</td>
<td>ABC PTE. LTD.</td>
</tr>
<tr class="odd">
<td><code>registration_incorporation_date</code></td>
<td>Registration date (YYYY-MM-DD)</td>
<td>2025-03-14</td>
</tr>
<tr class="even">
<td><code>primary_ssic_code</code></td>
<td>Primary SSIC code (2/3/4/5-digit)</td>
<td>56111</td>
</tr>
<tr class="odd">
<td><code>postal_code</code></td>
<td>Registered postal code (should be 6 digits)</td>
<td>018989</td>
</tr>
<tr class="even">
<td><code>entity_type</code> / <code>status</code></td>
<td>Type/status if required for filtering</td>
<td>LIVE COMPANY</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Additional columns may exist in different ACRA dumps; we standardise names with <code>janitor::clean_names()</code> and coalesce equivalent fields where needed.</p>
</blockquote>
</section>
<section id="study-coverage" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="study-coverage"><span class="header-section-number">2.3</span> Study coverage</h3>
<ul>
<li><strong>Temporal window:</strong> 1 Jan 2024 – 30 Jun 2025 (inclusive).<br>
</li>
<li><strong>Spatial extent:</strong> Singapore national boundary; mapping/aggregation by <strong>subzone</strong> and <strong>planning area</strong>.<br>
</li>
<li><strong>Business scope:</strong> At least <strong>three</strong> SSIC types (2- or 3-digit groups, or 5-digit subclasses), selected prior to analysis.</li>
</ul>
</section>
<section id="pre-processing-wrangling-summary" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="pre-processing-wrangling-summary"><span class="header-section-number">2.4</span> Pre-processing &amp; wrangling (summary)</h3>
<ul>
<li>Read and row-bind <strong>all 27 ACRA CSVs</strong>; add <code>source_file</code> for provenance.<br>
</li>
<li>Standardise fields: parse <code>registration_incorporation_date</code> as Date (UTC), derive <code>year</code>, <code>month</code>.<br>
</li>
<li><strong>Postal code hygiene:</strong> keep digits only, left-pad to 6; drop non-6-digit values before geocoding.<br>
</li>
<li><strong>Deduplicate</strong> by <code>uen</code> + <code>registration_incorporation_date</code> (if necessary).<br>
</li>
<li>Filter to the target SSIC code set and to the study window.<br>
</li>
<li><strong>Geocode</strong> unique postal codes via OneMap; join <code>X</code>/<code>Y</code> back to ACRA records.<br>
</li>
<li>Convert to <code>sf</code> (WGS84) → transform to <strong>SVY21 (EPSG:3414)</strong> for distance-based methods.<br>
</li>
<li>Join subzone attributes; save intermediates as RDS for reproducibility.</li>
</ul>
</section>
<section id="data-quality-limitations" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="data-quality-limitations"><span class="header-section-number">2.5</span> Data quality &amp; limitations</h3>
<ul>
<li><strong>Geocoding precision:</strong> Postal codes resolve to building/entrance centroids, not unit-level; some industrial sites share codes.<br>
</li>
<li><strong>Registration vs.&nbsp;operation:</strong> Registration date ≠ opening date; counts reflect legal registrations.<br>
</li>
<li><strong>Address anomalies:</strong> Legacy/PO box or malformed postcodes may not geocode; these are excluded.<br>
</li>
<li><strong>Classification drift:</strong> SSIC codes can change over time; we use the recorded <code>primary_ssic_code</code> as-is.</li>
</ul>
</section>
<section id="coordinate-reference-systems-crs" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="coordinate-reference-systems-crs"><span class="header-section-number">2.6</span> Coordinate reference systems (CRS)</h3>
<ul>
<li><strong>Input:</strong> WGS84 (EPSG:4326) from OneMap.<br>
</li>
<li><strong>Analysis/Maps:</strong> SVY21 / Singapore TM (EPSG:3414), metres, suitable for KDE and K-functions.</li>
</ul>
</section>
<section id="ethicalusage-notes" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="ethicalusage-notes"><span class="header-section-number">2.7</span> Ethical/usage notes</h3>
<ul>
<li>ACRA data contains <strong>entity names</strong> (public corporate info), not personal data.<br>
</li>
<li>Results are aggregated for planning insights; avoid singling out individual firms.</li>
</ul>
</section>
</section>
<section id="load-packages" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="load-packages"><span class="header-section-number">3</span> Load Packages</h2>
<p>Following code chunk is used to load neccessary packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  tidyverse,   <span class="co"># dplyr/readr/purrr/stringr</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  sf, tmap,    <span class="co"># geospatial + mapping</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  httr,        <span class="co"># OneMap API calls</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  lubridate,   <span class="co"># year(), month(), etc.</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  spatstat, spatstat.geom, spatstat.explore,    <span class="co"># KDE, K-function, CSR (monolithic ok)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  spNetwork,   <span class="co"># network KDE (optional/bonus)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  sparr,       <span class="co"># relative risk (optional/bonus)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  plotly,      <span class="co"># interactive plots (optional)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  gtsummary,   <span class="co"># summary tables </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  dplyr,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  janitor,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  stringr,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  readr,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  purrr</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-wrangling" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="data-wrangling"><span class="header-section-number">4</span> Data Wrangling</h2>
<section id="preparing-the-subzone-boundary-why-how" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="preparing-the-subzone-boundary-why-how"><span class="header-section-number">4.1</span> Preparing the Subzone Boundary (why &amp; how)</h3>
<p>This chunk converts URA’s <strong>Master Plan Subzone (No Sea)</strong> GeoJSON into a clean, projected <strong>GeoPackage</strong> with consistent field names. We use it as: 1) the <strong>analysis window</strong> for point-pattern methods, and<br>
2) the <strong>join layer</strong> to aggregate new businesses by subzone/planning area. Extract data for planning</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sz_raw_path <span class="ot">&lt;-</span> <span class="st">"data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaGEOJSON.geojson"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>subzones <span class="ot">&lt;-</span> <span class="fu">st_read</span>(sz_raw_path, <span class="at">quiet =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>() <span class="sc">%&gt;%</span>                 <span class="co"># lower_case_names</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_make_valid</span>() <span class="sc">%&gt;%</span>               <span class="co"># fix any tiny geometry issues</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">3414</span>)                <span class="co"># SVY21 metres (needed for KDE/K-functions)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Standardise key attribute names</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper: extract a field value from the HTML in `description`</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>extract_field <span class="ot">&lt;-</span> <span class="cf">function</span>(html, key){</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">str_match</span>(html, <span class="fu">paste0</span>(<span class="st">"&lt;th&gt;"</span>, key, <span class="st">"&lt;/th&gt;</span><span class="sc">\\</span><span class="st">s*&lt;td&gt;([^&lt;]*)&lt;/td&gt;"</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  val <span class="ot">&lt;-</span> m[, <span class="dv">2</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  val <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(val) <span class="sc">|</span> val <span class="sc">==</span> <span class="st">""</span>, <span class="cn">NA_character_</span>, <span class="fu">str_squish</span>(val))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(val)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>subzones_std <span class="ot">&lt;-</span> subzones <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">SUBZONE_NO =</span> <span class="fu">as.integer</span>(<span class="fu">extract_field</span>(description, <span class="st">"SUBZONE_NO"</span>)),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">SUBZONE_N  =</span> <span class="fu">extract_field</span>(description, <span class="st">"SUBZONE_N"</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">SUBZONE_C  =</span> <span class="fu">extract_field</span>(description, <span class="st">"SUBZONE_C"</span>),</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">CA_IND     =</span> <span class="fu">extract_field</span>(description, <span class="st">"CA_IND"</span>),</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">PLN_AREA_N =</span> <span class="fu">extract_field</span>(description, <span class="st">"PLN_AREA_N"</span>),</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">PLN_AREA_C =</span> <span class="fu">extract_field</span>(description, <span class="st">"PLN_AREA_C"</span>),</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">REGION_N   =</span> <span class="fu">extract_field</span>(description, <span class="st">"REGION_N"</span>),</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">REGION_C   =</span> <span class="fu">extract_field</span>(description, <span class="st">"REGION_C"</span>),</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">FMEL_UPD_D =</span> <span class="fu">extract_field</span>(description, <span class="st">"FMEL_UPD_D"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SUBZONE_NO, SUBZONE_N, SUBZONE_C, CA_IND,</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>         PLN_AREA_N, PLN_AREA_C, REGION_N, REGION_C, FMEL_UPD_D, geometry) <span class="sc">%&gt;%</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_make_valid</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">3414</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="co"># save a clean, fast-to-load copy</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="fu">st_write</span>(subzones_std, <span class="st">"data/geospatial/mpsz_subzones_2019_nosea.gpkg"</span>,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>         <span class="at">layer =</span> <span class="st">"subzones"</span>, <span class="at">delete_dsn =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Deleting source `data/geospatial/mpsz_subzones_2019_nosea.gpkg' using driver `GPKG'
Writing layer `subzones' to data source 
  `data/geospatial/mpsz_subzones_2019_nosea.gpkg' using driver `GPKG'
Writing 332 features with 9 fields and geometry type Unknown (any).</code></pre>
</div>
</div>
</section>
<section id="load-tidy-acra" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="load-tidy-acra"><span class="header-section-number">4.2</span> Load &amp; Tidy Acra</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>aspatial_dir <span class="ot">&lt;-</span> <span class="st">"data/aspatial"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>rds_dir      <span class="ot">&lt;-</span> <span class="st">"data/rds"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(rds_dir, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(aspatial_dir, <span class="at">pattern =</span> <span class="st">"^ACRA.*</span><span class="sc">\\</span><span class="st">.csv$"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>acra_raw <span class="ot">&lt;-</span> file_list <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map_dfr</span>(<span class="sc">~</span> <span class="fu">read_csv</span>(.x, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 2) Tidy dates, SSIC, postal codes; derive time fields; filter study window</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>acra_tidy <span class="ot">&lt;-</span> acra_raw <span class="sc">|&gt;</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">reg_date  =</span> <span class="fu">as.Date</span>(registration_incorporation_date),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">year      =</span> <span class="fu">year</span>(reg_date),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">month_num =</span> <span class="fu">month</span>(reg_date),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">month     =</span> <span class="fu">month</span>(reg_date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># keep only digits in postal_code; left-pad to 6</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">postal_code =</span> postal_code <span class="sc">|&gt;</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_replace_all</span>(<span class="st">"[^0-9]"</span>, <span class="st">""</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_pad</span>(<span class="at">width =</span> <span class="dv">6</span>, <span class="at">side =</span> <span class="st">"left"</span>, <span class="at">pad =</span> <span class="st">"0"</span>),</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># normalise primary SSIC to 5 chars, and derive 2-/3-digit prefixes</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">primary_ssic_code =</span> <span class="fu">str_pad</span>(<span class="fu">str_sub</span>(primary_ssic_code, <span class="dv">1</span>, <span class="dv">5</span>), <span class="dv">5</span>, <span class="at">pad =</span> <span class="st">"0"</span>),</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">ssic2 =</span> <span class="fu">str_sub</span>(primary_ssic_code, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">ssic3 =</span> <span class="fu">str_sub</span>(primary_ssic_code, <span class="dv">1</span>, <span class="dv">3</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(reg_date),</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>         reg_date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2024-01-01"</span>),</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>         reg_date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2025-06-30"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="select-the-3-industries" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="select-the-3-industries"><span class="header-section-number">4.3</span> Select the 3 Industries</h3>
<p>Choosing the three industries</p>
<p>The assignment requires at least three business types. We select broad, policy-relevant <strong>2-digit SSIC</strong> groups that span consumer, knowledge, and logistics activities:</p>
<ul>
<li><strong>56 — Food &amp; Beverage Service Activities</strong> (restaurants, cafés, bars)<br>
</li>
<li><strong>62 — Computer programming, IT consultancy &amp; related activities</strong><br>
</li>
<li><strong>52 — Warehousing &amp; support activities for transportation</strong></li>
</ul>
<p>In the code below, we:</p>
<ol type="1">
<li><strong>Build</strong> a small lookup to attach readable sector labels to each 2-digit SSIC.<br>
</li>
<li><strong>Filter</strong> the cleaned ACRA records to these codes.<br>
</li>
<li><strong>Produce</strong> a quick <em>sector × year</em> table to sanity-check sample sizes for 2024 and 2025.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 56 = Food &amp; Beverage, 62 = Information Technology, 52 = Warehousing &amp; support activities for transport</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>targets <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">ssic2 =</span> <span class="fu">c</span>(<span class="st">"56"</span>, <span class="st">"62"</span>, <span class="st">"52"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sector =</span> <span class="fu">c</span>(<span class="st">"F&amp;B (56)"</span>, <span class="st">"IT (62)"</span>, <span class="st">"Logistics/Warehousing (52)"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>biz_sel <span class="ot">&lt;-</span> acra_tidy <span class="sc">|&gt;</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ssic2 <span class="sc">%in%</span> targets<span class="sc">$</span>ssic2) <span class="sc">|&gt;</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(targets, <span class="at">by =</span> <span class="st">"ssic2"</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(biz_sel<span class="sc">$</span>sector, biz_sel<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            
                             2024 2025
  F&amp;B (56)                   3793 1965
  IT (62)                    5845 2895
  Logistics/Warehousing (52)  995  723</code></pre>
</div>
</div>
</section>
<section id="geocode-unique-postcodes-with-onemap" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="geocode-unique-postcodes-with-onemap"><span class="header-section-number">4.4</span> Geocode unique postcodes with OneMap</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper that hits OneMap Search API for one postcode</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>onemap_lookup <span class="ot">&lt;-</span> <span class="cf">function</span>(pc){</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="st">"https://onemap.gov.sg/api/common/elastic/search"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">query =</span> <span class="fu">list</span>(<span class="at">searchVal =</span> pc, <span class="at">returnGeom =</span> <span class="st">"Y"</span>, <span class="at">getAddrDetails =</span> <span class="st">"Y"</span>, <span class="at">pageNum =</span> <span class="st">"1"</span>))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  js <span class="ot">&lt;-</span> <span class="fu">content</span>(res)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(js<span class="sc">$</span>found) <span class="sc">&amp;&amp;</span> js<span class="sc">$</span>found <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    r <span class="ot">&lt;-</span> js<span class="sc">$</span>results[[<span class="dv">1</span>]]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(<span class="at">POSTAL =</span> r<span class="sc">$</span>POSTAL, <span class="at">X =</span> <span class="fu">as.numeric</span>(r<span class="sc">$</span>X), <span class="at">Y =</span> <span class="fu">as.numeric</span>(r<span class="sc">$</span>Y))</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(<span class="at">POSTAL =</span> pc, <span class="at">X =</span> <span class="cn">NA_real_</span>, <span class="at">Y =</span> <span class="cn">NA_real_</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Geocode unique postcodes</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>pcs <span class="ot">&lt;-</span> biz_sel<span class="sc">$</span>postal_code <span class="sc">|&gt;</span> <span class="fu">unique</span>()</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>geo_tbl <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(pcs, <span class="sc">~</span> <span class="fu">tryCatch</span>(<span class="fu">onemap_lookup</span>(.x), <span class="at">error =</span> <span class="cf">function</span>(e)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">POSTAL =</span> .x, <span class="at">X =</span> <span class="cn">NA_real_</span>, <span class="at">Y =</span> <span class="cn">NA_real_</span>)))</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Join back and keep geocoded rows</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>biz_geo <span class="ot">&lt;-</span> biz_sel <span class="sc">|&gt;</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(geo_tbl, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"postal_code"</span> <span class="ot">=</span> <span class="st">"POSTAL"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(X), <span class="sc">!</span><span class="fu">is.na</span>(Y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="convert-to-sf-project-to-svy21-and-join-subzones" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="convert-to-sf-project-to-svy21-and-join-subzones"><span class="header-section-number">4.5</span> Convert to sf, project to SVY21, and join subzones</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>biz_pts <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(biz_geo, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">3414</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_join</span>(subzones_std <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">select</span>(SUBZONE_N, PLN_AREA_N), <span class="at">left =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Save intermediates for fast reload</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(acra_tidy, <span class="fu">file.path</span>(rds_dir, <span class="st">"acra_tidy_2024H1_2025H1.rds"</span>))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(biz_pts,  <span class="fu">file.path</span>(rds_dir, <span class="st">"biz_points_geocoded.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-precomputed-outputs" class="level3" data-number="4.6">
<h3 data-number="4.6" class="anchored" data-anchor-id="load-precomputed-outputs"><span class="header-section-number">4.6</span> Load precomputed outputs</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>acra_tidy <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_rds</span>(<span class="fu">file.path</span>(rds_dir, <span class="st">"acra_tidy_2024H1_2025H1.rds"</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>biz_pts   <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_rds</span>(<span class="fu">file.path</span>(rds_dir, <span class="st">"biz_points_geocoded.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="quick-sanity-check" class="level3" data-number="4.7">
<h3 data-number="4.7" class="anchored" data-anchor-id="quick-sanity-check"><span class="header-section-number">4.7</span> Quick sanity check</h3>
<section id="counts-crs-validity" class="level4" data-number="4.7.1">
<h4 data-number="4.7.1" class="anchored" data-anchor-id="counts-crs-validity"><span class="header-section-number">4.7.1</span> counts, CRS, validity</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expect these to exist from earlier chunks:</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">exists</span>(<span class="st">"subzones_std"</span>), <span class="fu">exists</span>(<span class="st">"biz_pts"</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic shapes</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(subzones_std); <span class="fu">nrow</span>(biz_pts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 332</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16213</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CRS should be SVY21 / EPSG:3414</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(subzones_std)<span class="sc">$</span>epsg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3414</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(biz_pts)<span class="sc">$</span>epsg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3414</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Any invalid geometries?</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(<span class="fu">st_is_valid</span>(subzones_std))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(<span class="fu">st_is_valid</span>(biz_pts))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Any missing coordinates?</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="fu">st_coordinates</span>(biz_pts)[,<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="fu">st_coordinates</span>(biz_pts)[,<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick distribution check</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>biz_pts <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sector, year, <span class="at">name =</span> <span class="st">"n"</span>) <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sector, year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  sector                      year     n
  &lt;chr&gt;                      &lt;dbl&gt; &lt;int&gt;
1 F&amp;B (56)                    2024  3791
2 F&amp;B (56)                    2025  1965
3 IT (62)                     2024  5844
4 IT (62)                     2025  2895
5 Logistics/Warehousing (52)  2024   995
6 Logistics/Warehousing (52)  2025   723</code></pre>
</div>
</div>
</section>
<section id="are-points-inside-singapore-subzones" class="level4" data-number="4.7.2">
<h4 data-number="4.7.2" class="anchored" data-anchor-id="are-points-inside-singapore-subzones"><span class="header-section-number">4.7.2</span> Are points inside Singapore subzones?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>inside <span class="ot">&lt;-</span> <span class="fu">st_intersects</span>(biz_pts, subzones_std, <span class="at">sparse =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">lengths</span>(inside) <span class="sc">&gt;</span> <span class="dv">0</span>)   <span class="co"># share of points that fall in a subzone (expect ~1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>we find that intersects results in 0 which means some thing went wrong somewhere therefore we rectify this in the next Sub section</p>
</section>
<section id="rebuild-the-sf-points-with-the-correct-crs-directly-no-transform" class="level4" data-number="4.7.3">
<h4 data-number="4.7.3" class="anchored" data-anchor-id="rebuild-the-sf-points-with-the-correct-crs-directly-no-transform"><span class="header-section-number">4.7.3</span> Rebuild the sf points with the correct CRS directly (no transform)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># X/Y from OneMap are already SVY21 metres → set crs = 3414 and DO NOT transform</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>biz_pts <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(biz_geo, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>), <span class="at">crs =</span> <span class="dv">3414</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_join</span>(subzones_std <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">select</span>(SUBZONE_N, PLN_AREA_N), <span class="at">left =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick sanity</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">st_crs</span>(biz_pts)<span class="sc">$</span>epsg <span class="sc">==</span> <span class="dv">3414</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">lengths</span>(<span class="fu">st_intersects</span>(biz_pts, subzones_std)) <span class="sc">&gt;</span> <span class="dv">0</span>)  <span class="co"># should be ~1</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Overwrite the saved file</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(biz_pts, <span class="fu">file.path</span>(rds_dir, <span class="st">"biz_points_geocoded.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-precomputed-outputs-again" class="level4" data-number="4.7.4">
<h4 data-number="4.7.4" class="anchored" data-anchor-id="load-precomputed-outputs-again"><span class="header-section-number">4.7.4</span> Load precomputed outputs again</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>acra_tidy <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_rds</span>(<span class="fu">file.path</span>(rds_dir, <span class="st">"acra_tidy_2024H1_2025H1.rds"</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>biz_pts   <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_rds</span>(<span class="fu">file.path</span>(rds_dir, <span class="st">"biz_points_geocoded.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="quick-check-again" class="level4" data-number="4.7.5">
<h4 data-number="4.7.5" class="anchored" data-anchor-id="quick-check-again"><span class="header-section-number">4.7.5</span> Quick Check again</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: qc-rebuild-using-biz-pts</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: true</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Coordinate ranges in SVY21 metres</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_coordinates</span>(biz_pts)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       X               Y        
 Min.   : 4721   Min.   :24733  
 1st Qu.:28071   1st Qu.:29868  
 Median :29744   Median :33206  
 Mean   :29492   Mean   :34315  
 3rd Qu.:32938   3rd Qu.:36953  
 Max.   :53137   Max.   :50104  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Validity + missing checks</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(sf<span class="sc">::</span><span class="fu">st_is_valid</span>(biz_pts))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(coords[,<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(coords[,<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coverage inside subzones</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>inside <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_intersects</span>(biz_pts, subzones_std, <span class="at">sparse =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">lengths</span>(inside) <span class="sc">&gt;</span> <span class="dv">0</span>)   <span class="co"># should be ~1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Now intersects() does leave 1 which means all points are in Singapore</p>
</section>
<section id="quick-map" class="level4" data-number="4.7.6">
<h4 data-number="4.7.6" class="anchored" data-anchor-id="quick-map"><span class="header-section-number">4.7.6</span> Quick Map</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(subzones_std) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"grey90"</span>, <span class="at">border.col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(biz_pts) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.02</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex01_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="removing-unwanted-planning-areas" class="level3" data-number="4.8">
<h3 data-number="4.8" class="anchored" data-anchor-id="removing-unwanted-planning-areas"><span class="header-section-number">4.8</span> Removing unwanted planning areas</h3>
<p>To avoid empty polygons biasing our maps and point-pattern statistics, we trim the study area to places that actually have registrations. Specifically, we:</p>
<ul>
<li><strong>Keep</strong> planning areas with ≥ 1 geocoded point (computed from <code>biz_pts</code>).<br>
</li>
<li><strong>Exclude</strong> <em>NORTH-EASTERN ISLANDS</em> on purpose (offshore, no relevant activity for our scope).<br>
</li>
<li><strong>Keep</strong> <em>WESTERN ISLANDS</em> because logistics/port activity is plausible.<br>
</li>
<li><strong>Filter</strong> both the polygon layer (<code>subzones_std → subzones_use</code>) and the points (<code>biz_pts → biz_pts_use</code>) so subsequent joins and KDE/K-functions use a consistent window.</li>
</ul>
<p>This reduces noise, speeds processing, and prevents intensity estimates from being diluted by large empty areas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Planning areas that have at least one point</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>keep_pa <span class="ot">&lt;-</span> biz_pts <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(PLN_AREA_N, <span class="at">name =</span> <span class="st">"n"</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(PLN_AREA_N)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>subzones_use <span class="ot">&lt;-</span> subzones_std <span class="sc">|&gt;</span> <span class="fu">filter</span>(PLN_AREA_N <span class="sc">%in%</span> keep_pa)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>subzones_use <span class="ot">&lt;-</span> subzones_std <span class="sc">|&gt;</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(PLN_AREA_N <span class="sc">%in%</span> keep_pa,</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>                PLN_AREA_N <span class="sc">!=</span> <span class="st">"NORTH-EASTERN ISLANDS"</span>)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co">#  also drop any biz points that lie in North-Eastern Islands,</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="co"># or that didn’t pick up a planning area for any reason.</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>biz_pts_use <span class="ot">&lt;-</span> biz_pts <span class="sc">|&gt;</span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(PLN_AREA_N),</span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>                PLN_AREA_N <span class="sc">!=</span> <span class="st">"NORTH-EASTERN ISLANDS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="map-check" class="level4" data-number="4.8.1">
<h4 data-number="4.8.1" class="anchored" data-anchor-id="map-check"><span class="header-section-number">4.8.1</span> Map Check</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(subzones_use) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"grey90"</span>, <span class="at">border.col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(biz_pts) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.02</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex01_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="eda" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="eda"><span class="header-section-number">5</span> EDA</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sector x Year counts</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>biz_pts_use <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sector, year, <span class="at">name =</span> <span class="st">"n"</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sector, year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  sector                      year     n
  &lt;chr&gt;                      &lt;dbl&gt; &lt;int&gt;
1 F&amp;B (56)                    2024  3790
2 F&amp;B (56)                    2025  1965
3 IT (62)                     2024  5844
4 IT (62)                     2025  2895
5 Logistics/Warehousing (52)  2024   995
6 Logistics/Warehousing (52)  2025   723</code></pre>
</div>
</div>
<section id="top-planning-areas-per-sector" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="top-planning-areas-per-sector"><span class="header-section-number">5.1</span> Top Planning Areas per sector</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top Planning Areas per sector (top 10)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>top_pa <span class="ot">&lt;-</span> biz_pts_use <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sector, PLN_AREA_N, <span class="at">name =</span> <span class="st">"n"</span>) <span class="sc">|&gt;</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sector) <span class="sc">|&gt;</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(n, <span class="at">n =</span> <span class="dv">10</span>, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>top_pa</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 3
   sector   PLN_AREA_N        n
   &lt;chr&gt;    &lt;chr&gt;         &lt;int&gt;
 1 F&amp;B (56) GEYLANG         526
 2 F&amp;B (56) DOWNTOWN CORE   362
 3 F&amp;B (56) KALLANG         294
 4 F&amp;B (56) WOODLANDS       287
 5 F&amp;B (56) OUTRAM          283
 6 F&amp;B (56) BEDOK           269
 7 F&amp;B (56) HOUGANG         254
 8 F&amp;B (56) SEMBAWANG       210
 9 F&amp;B (56) TOA PAYOH       210
10 F&amp;B (56) YISHUN          209
# ℹ 20 more rows</code></pre>
</div>
</div>
</section>
<section id="subzone-coverage-check-how-many-subzones-have-1-registration-by-sector" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="subzone-coverage-check-how-many-subzones-have-1-registration-by-sector"><span class="header-section-number">5.2</span> Subzone coverage check: how many subzones have ≥1 registration (by sector)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># all sector × subzone combinations in your study window</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>all_grid <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sector    =</span> <span class="fu">unique</span>(biz_pts_use<span class="sc">$</span>sector),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">SUBZONE_N =</span> <span class="fu">unique</span>(subzones_use<span class="sc">$</span>SUBZONE_N)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fill missing combos with n = 0, then compute has_any</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>subzone_cover <span class="ot">&lt;-</span> biz_pts_use <span class="sc">|&gt;</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sector, SUBZONE_N, <span class="at">name =</span> <span class="st">"n"</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(all_grid, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"sector"</span>,<span class="st">"SUBZONE_N"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">replace_na</span>(n, <span class="dv">0</span>), <span class="at">has_any =</span> n <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sector, has_any, <span class="at">name =</span> <span class="st">"subzones"</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">names_from =</span> has_any, <span class="at">values_from =</span> subzones, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">subzones_with_≥1</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">TRUE</span><span class="st">`</span>, <span class="st">`</span><span class="at">subzones_with_0</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">FALSE</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">subzones_total =</span> <span class="st">`</span><span class="at">subzones_with_≥1</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">subzones_with_0</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sector, subzones_total, <span class="st">`</span><span class="at">subzones_with_≥1</span><span class="st">`</span>, <span class="st">`</span><span class="at">subzones_with_0</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sector)</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>subzone_cover</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  sector                     subzones_total `subzones_with_≥1` subzones_with_0
  &lt;chr&gt;                               &lt;int&gt;              &lt;int&gt;           &lt;int&gt;
1 F&amp;B (56)                              319                278              41
2 IT (62)                               319                260              59
3 Logistics/Warehousing (52)            319                202             117</code></pre>
</div>
</div>
<ul>
<li><p><strong>Headline:</strong> IT and Logistics appear to “peak” in the CBD due to <em>registered-office addresses</em>; <strong>Logistics relocates to industrial corridors</strong> and IT to <strong>business parks + town centres</strong>.</p></li>
<li><p><strong>Policy insight:</strong></p>
<ul>
<li><strong>F&amp;B:</strong> island-wide, population-following growth → watch <strong>malls/transport nodes</strong>.<br>
</li>
<li><strong>IT:</strong> concentrates in <strong>CBD + parks</strong> → plan <strong>flexible office stock</strong> near transit.<br>
</li>
<li><strong>Logistics:</strong> anchored to <strong>port/airport/expressways</strong> → reserve <strong>industrial land</strong> and manage <strong>last-mile interfaces</strong> with residential areas.</li>
</ul></li>
</ul>
</section>
<section id="choroplethcounts-by-planning-area-and-subzone" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="choroplethcounts-by-planning-area-and-subzone"><span class="header-section-number">5.3</span> Choropleth:counts By Planning Area and Subzone</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Planning Area counts</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>pa_counts <span class="ot">&lt;-</span> biz_pts_use <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(PLN_AREA_N, sector, <span class="at">name =</span> <span class="st">"n"</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>subzones_pa <span class="ot">&lt;-</span> subzones_use <span class="sc">|&gt;</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(PLN_AREA_N, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(pa_counts <span class="sc">|&gt;</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">group_by</span>(PLN_AREA_N) <span class="sc">|&gt;</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">n_all =</span> <span class="fu">sum</span>(n), <span class="at">.groups =</span> <span class="st">"drop"</span>),</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"PLN_AREA_N"</span>)</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a single Singapore outline from your filtered subzones</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>sg_outline <span class="ot">&lt;-</span> subzones_use <span class="sc">|&gt;</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">|&gt;</span>              <span class="co"># dissolve to one geometry</span></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_make_valid</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="st">"Singapore"</span>) <span class="co"># (dummy column just to keep an sf)</span></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(subzones_pa) <span class="sc">+</span></span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(</span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">"n_all"</span>,</span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Registrations (all sectors)"</span>,</span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">style =</span> <span class="st">"quantile"</span>, <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">border.col =</span> <span class="st">"grey30"</span>, <span class="at">border.lwd =</span> <span class="fl">0.6</span></span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb50-28"><a href="#cb50-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sg_outline) <span class="sc">+</span></span>
<span id="cb50-29"><a href="#cb50-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">1.2</span>) <span class="sc">+</span>   <span class="co"># &lt;- country border</span></span>
<span id="cb50-30"><a href="#cb50-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex01_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Darker shades indicate planning areas with higher counts of registered businesses.<br>
- The strongest concentrations appear in <strong>Downtown Core, Geylang, and Kallang</strong>, reflecting both genuine activity and the prevalence of registered office addresses in the CBD.<br>
- Peripheral industrial/logistics corridors (e.g., <strong>Jurong, Woodlands, Changi</strong>) also show elevated counts.<br>
- Many heartland towns register moderate F&amp;B and IT entries, highlighting the <strong>broad spatial reach of local services</strong>.</p>
<p>This baseline choropleth provides the starting point for intensity (KDE) and clustering (K/CSR) analyses in subsequent sections.</p>
</section>
</section>
<section id="st-order-spatio-temporal-analysis" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="st-order-spatio-temporal-analysis"><span class="header-section-number">6</span> 1st Order Spatio Temporal Analysis</h2>
<p>Convert sf → owin and ppp</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build polygonal window (country outline) from filtered subzones</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> spatstat.geom<span class="sc">::</span><span class="fu">as.owin</span>(<span class="fu">st_union</span>(subzones_use))   <span class="co"># SVY21 metres (EPSG:3414)</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper: convert an sf points subset to ppp in window W</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>to_ppp <span class="ot">&lt;-</span> <span class="cf">function</span>(pts_sf) {</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  xy <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_coordinates</span>(pts_sf)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  spatstat.geom<span class="sc">::</span><span class="fu">ppp</span>(<span class="at">x =</span> xy[,<span class="dv">1</span>], <span class="at">y =</span> xy[,<span class="dv">2</span>], <span class="at">window =</span> W, <span class="at">check =</span> <span class="cn">FALSE</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="clarkevans-test-per-sector" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="clarkevans-test-per-sector"><span class="header-section-number">6.1</span> Clark–Evans test per sector</h3>
<p>The Clark–Evans nearest-neighbour test evaluates whether business registrations are <strong>randomly distributed</strong>, <strong>clustered</strong>, or <strong>regularly spaced</strong> relative to Complete Spatial Randomness (CSR).</p>
<ul>
<li><strong>Null hypothesis (H₀):</strong> The point pattern of business registrations follows <strong>CSR</strong> (i.e., randomly distributed).<br>
</li>
<li><strong>Alternative hypothesis (H₁):</strong> The point pattern is <strong>more clustered than CSR</strong> (R &lt; 1).</li>
</ul>
<p>We test this hypothesis for each selected sector (F&amp;B, IT, Logistics/Warehousing) using both the <strong>asymptotic test</strong> and the <strong>Monte Carlo CSR simulation</strong> (999 realisations).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>sectors <span class="ot">&lt;-</span> <span class="fu">unique</span>(biz_pts_use<span class="sc">$</span>sector)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Asymptotic (no CSR simulation)</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>ce_asym <span class="ot">&lt;-</span> <span class="fu">lapply</span>(sectors, <span class="cf">function</span>(sec){</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">to_ppp</span>(biz_pts_use <span class="sc">%&gt;%</span> <span class="fu">filter</span>(sector <span class="sc">==</span> sec))</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> <span class="fu">clarkevans.test</span>(X, <span class="at">correction =</span> <span class="st">"none"</span>, <span class="at">clipregion =</span> W, <span class="at">alternative =</span> <span class="st">"clustered"</span>)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">sector =</span> sec,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">n =</span> X<span class="sc">$</span>n,</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">R =</span> <span class="fu">unname</span>(z<span class="sc">$</span>statistic),</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">p_value =</span> z<span class="sc">$</span>p.value,</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"Asymptotic (no CSR)"</span>)</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">bind_rows</span>()</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Monte Carlo against CSR (recommended for reporting)</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>ce_mc <span class="ot">&lt;-</span> <span class="fu">lapply</span>(sectors, <span class="cf">function</span>(sec){</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">to_ppp</span>(biz_pts_use <span class="sc">%&gt;%</span> <span class="fu">filter</span>(sector <span class="sc">==</span> sec))</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> <span class="fu">clarkevans.test</span>(X, <span class="at">correction =</span> <span class="st">"none"</span>, <span class="at">clipregion =</span> W,</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>                       <span class="at">alternative =</span> <span class="st">"clustered"</span>, <span class="at">method =</span> <span class="st">"MonteCarlo"</span>, <span class="at">nsim =</span> <span class="dv">999</span>)</span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">sector =</span> sec,</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">n =</span> X<span class="sc">$</span>n,</span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">R =</span> <span class="fu">unname</span>(z<span class="sc">$</span>statistic),</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">p_value =</span> z<span class="sc">$</span>p.value,</span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"Monte Carlo (999 CSR sims)"</span>)</span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">bind_rows</span>()</span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>ce_results <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(ce_asym, ce_mc) <span class="sc">%&gt;%</span></span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sector, method)</span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a>ce_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>ce_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  sector                         n     R p_value method                    
  &lt;chr&gt;                      &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                     
1 F&amp;B (56)                    5755 0.365   0     Asymptotic (no CSR)       
2 F&amp;B (56)                    5755 0.365   0.001 Monte Carlo (999 CSR sims)
3 IT (62)                     8739 0.248   0     Asymptotic (no CSR)       
4 IT (62)                     8739 0.248   0.001 Monte Carlo (999 CSR sims)
5 Logistics/Warehousing (52)  1718 0.317   0     Asymptotic (no CSR)       
6 Logistics/Warehousing (52)  1718 0.317   0.001 Monte Carlo (999 CSR sims)</code></pre>
</div>
</div>
<p><strong>Clark–Evans nearest-neighbour test (window = Singapore outline, SVY21).</strong><br>
Across all sectors the Clark–Evans statistic (R) is <strong>below 1</strong> and Monte-Carlo p-values are <strong>significant</strong> (()), indicating <strong>clustering relative to CSR</strong> at nearest-neighbour scale.</p>
<ul>
<li><strong>IT (62):</strong> (R ), (p ) → <strong>strongest clustering</strong>. Likely reflects CBD/fringe-CBD registered-office addresses and business-park nodes (one-north, CBP).<br>
</li>
<li><strong>Logistics/Warehousing (52):</strong> (R ), (p ) → <strong>clear clustering</strong>, consistent with industrial land concentration near port/airport/expressways.<br>
</li>
<li><strong>F&amp;B (56):</strong> (R ), (p ) → <strong>clustered but more diffuse</strong> than IT/Logistics, aligning with town-centre/mall/transit nodes spread island-wide.</li>
</ul>
<p><strong>Implications.</strong><br>
Nearest-neighbour distances are <strong>smaller than CSR expectations</strong> ( (R&lt;1) ), so new registrations tend to occur near one another rather than randomly. This justifies: 1) mapping <strong>first-order intensity</strong> with KDE to locate hot spots, and<br>
2) using <strong>K/CSR envelopes</strong> to see at which spatial ranges clustering persists beyond nearest neighbours.</p>
</section>
<section id="spatial-intensity-of-fb-ssic-56-business-registrations" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="spatial-intensity-of-fb-ssic-56-business-registrations"><span class="header-section-number">6.2</span> Spatial Intensity of F&amp;B (SSIC 56) Business Registrations</h3>
<p>In this section, we compute and visualize the spatial intensity of F&amp;B (SSIC 56) business registrations:</p>
<ol type="1">
<li>Cache paths</li>
</ol>
<ul>
<li>Create folders (<code>data/rds</code>, <code>data/rasters</code>) to store intermediate results.<br>
</li>
<li>This avoids re-running expensive computations every time the document is rendered.</li>
</ul>
<ol start="2" type="1">
<li>Data preparation</li>
</ol>
<ul>
<li>F&amp;B points are filtered from the master dataset (<code>biz_pts_use</code>).<br>
</li>
<li>Their coordinates are extracted and converted into a <code>ppp</code> object (planar point pattern) using <strong>spatstat</strong>.<br>
</li>
<li>The observation window <code>W</code> is already defined from the trimmed planning area polygons.</li>
</ul>
<ol start="3" type="1">
<li>Kernel Density Estimation (KDE)</li>
</ol>
<ul>
<li>If a cached result exists, it is loaded.<br>
</li>
<li>Otherwise, a suitable bandwidth is estimated with <code>bw.diggle</code>, with safeguards (clamped between <strong>300 m and 800 m</strong>).<br>
</li>
<li>The KDE is then computed using a <strong>Gaussian kernel</strong>.<br>
</li>
<li>The result is saved as an <code>.rds</code> file for future use.</li>
</ul>
<ol start="4" type="1">
<li>Scaling and conversion</li>
</ol>
<ul>
<li>The density is originally in units of <strong>points per m²</strong>.<br>
</li>
<li>Multiply by <code>1e6</code> to rescale into <strong>points per km²</strong>, a more interpretable measure.<br>
</li>
<li>Convert the raster into a <code>SpatRaster</code> with the correct CRS (<strong>EPSG:3414</strong>).</li>
</ul>
<ol start="5" type="1">
<li>Saving outputs</li>
</ol>
<ul>
<li>Save the raster as a <strong>GeoTIFF (.tif)</strong> so it can be reused in GIS software.</li>
</ul>
<ol start="6" type="1">
<li>Mapping</li>
</ol>
<ul>
<li>Using <strong>tmap</strong>, render a choropleth of F&amp;B intensity.<br>
</li>
<li>Overlay planning area boundaries (thin white borders) and the outer municipal boundary (thicker black border).<br>
</li>
<li>The legend title clearly states that values represent <strong>registrations per km²</strong>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Always-available constants (paths) ---</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>rds_dir      <span class="ot">&lt;-</span> <span class="st">"data/rds"</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>rasters_dir  <span class="ot">&lt;-</span> <span class="st">"data/rasters"</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(rds_dir, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(rasters_dir, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>fnb_kde_rds <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"fnb_kde_im.rds"</span>)</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>fnb_bw_rds  <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"fnb_bw.rds"</span>)</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>fnb_kde_tif <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rasters_dir, <span class="st">"fnb_kde_per_km2.tif"</span>)</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Ensure window and ppp exist (robust to earlier chunks being skipped) ---</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">exists</span>(<span class="st">"subzones_use"</span>)) <span class="fu">stop</span>(<span class="st">"subzones_use is missing; load/build it before this chunk."</span>)</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">exists</span>(<span class="st">"W"</span>)) {</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>  W <span class="ot">&lt;-</span> spatstat.geom<span class="sc">::</span><span class="fu">as.owin</span>(sf<span class="sc">::</span><span class="fu">st_union</span>(subzones_use))</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">exists</span>(<span class="st">"biz_pts_use"</span>)) <span class="fu">stop</span>(<span class="st">"biz_pts_use is missing; load/build it before this chunk."</span>)</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>fnb_sf  <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(biz_pts_use, sector <span class="sc">==</span> <span class="st">"F&amp;B (56)"</span>)</span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a>xy      <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_coordinates</span>(fnb_sf)</span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a>fnb_ppp <span class="ot">&lt;-</span> spatstat.geom<span class="sc">::</span><span class="fu">ppp</span>(<span class="at">x =</span> xy[,<span class="dv">1</span>], <span class="at">y =</span> xy[,<span class="dv">2</span>], <span class="at">window =</span> W, <span class="at">check =</span> <span class="cn">FALSE</span>)</span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Load or compute KDE + bandwidth, and persist both ---</span></span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a>fnb_bw <span class="ot">&lt;-</span> <span class="cn">NA_real_</span></span>
<span id="cb55-24"><a href="#cb55-24" aria-hidden="true" tabindex="-1"></a>kde_im <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb55-25"><a href="#cb55-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-26"><a href="#cb55-26" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">file.exists</span>(fnb_kde_rds)) {</span>
<span id="cb55-27"><a href="#cb55-27" aria-hidden="true" tabindex="-1"></a>  kde_im <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(fnb_kde_rds)</span>
<span id="cb55-28"><a href="#cb55-28" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">file.exists</span>(fnb_bw_rds)) fnb_bw <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(fnb_bw_rds)</span>
<span id="cb55-29"><a href="#cb55-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb55-30"><a href="#cb55-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-31"><a href="#cb55-31" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">is.null</span>(kde_im) <span class="sc">||</span> <span class="sc">!</span><span class="fu">is.numeric</span>(fnb_bw) <span class="sc">||</span> <span class="fu">is.na</span>(fnb_bw)) {</span>
<span id="cb55-32"><a href="#cb55-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># estimate &amp; clamp bandwidth</span></span>
<span id="cb55-33"><a href="#cb55-33" aria-hidden="true" tabindex="-1"></a>  h_est <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(spatstat.explore<span class="sc">::</span><span class="fu">bw.diggle</span>(fnb_ppp), <span class="at">error =</span> <span class="cf">function</span>(e) <span class="dv">400</span>)</span>
<span id="cb55-34"><a href="#cb55-34" aria-hidden="true" tabindex="-1"></a>  h_est <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(h_est)</span>
<span id="cb55-35"><a href="#cb55-35" aria-hidden="true" tabindex="-1"></a>  fnb_bw <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="fu">max</span>(h_est, <span class="dv">300</span>), <span class="dv">800</span>)   <span class="co"># clamp 300–800 m</span></span>
<span id="cb55-36"><a href="#cb55-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-37"><a href="#cb55-37" aria-hidden="true" tabindex="-1"></a>  kde_im <span class="ot">&lt;-</span> spatstat.explore<span class="sc">::</span><span class="fu">density.ppp</span>(</span>
<span id="cb55-38"><a href="#cb55-38" aria-hidden="true" tabindex="-1"></a>    fnb_ppp, <span class="at">sigma =</span> fnb_bw, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span></span>
<span id="cb55-39"><a href="#cb55-39" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb55-40"><a href="#cb55-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-41"><a href="#cb55-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">saveRDS</span>(kde_im, fnb_kde_rds)</span>
<span id="cb55-42"><a href="#cb55-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">saveRDS</span>(fnb_bw, fnb_bw_rds)</span>
<span id="cb55-43"><a href="#cb55-43" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb55-44"><a href="#cb55-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-45"><a href="#cb55-45" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Scale to per km^2 and convert to SpatRaster with CRS ---</span></span>
<span id="cb55-46"><a href="#cb55-46" aria-hidden="true" tabindex="-1"></a>kde_im_km2 <span class="ot">&lt;-</span> kde_im <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb55-47"><a href="#cb55-47" aria-hidden="true" tabindex="-1"></a>kde_r <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(kde_im_km2)</span>
<span id="cb55-48"><a href="#cb55-48" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">crs</span>(kde_r) <span class="ot">&lt;-</span> <span class="st">"EPSG:3414"</span></span>
<span id="cb55-49"><a href="#cb55-49" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(fnb_kde_tif)) terra<span class="sc">::</span><span class="fu">writeRaster</span>(kde_r, fnb_kde_tif, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-50"><a href="#cb55-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-51"><a href="#cb55-51" aria-hidden="true" tabindex="-1"></a><span class="co"># --- (Optional) map directly ---</span></span>
<span id="cb55-52"><a href="#cb55-52" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb55-53"><a href="#cb55-53" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kde_r) <span class="sc">+</span></span>
<span id="cb55-54"><a href="#cb55-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(</span>
<span id="cb55-55"><a href="#cb55-55" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.scale  =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"Blues"</span>),</span>
<span id="cb55-56"><a href="#cb55-56" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"F&amp;B intensity</span><span class="sc">\n</span><span class="st">(registrations per km²)"</span>)</span>
<span id="cb55-57"><a href="#cb55-57" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb55-58"><a href="#cb55-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(subzones_use) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">lwd =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb55-59"><a href="#cb55-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sf<span class="sc">::</span><span class="fu">st_as_sf</span>(sf<span class="sc">::</span><span class="fu">st_make_valid</span>(sf<span class="sc">::</span><span class="fu">st_union</span>(subzones_use)))) <span class="sc">+</span></span>
<span id="cb55-60"><a href="#cb55-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb55-61"><a href="#cb55-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex01_files/figure-html/KDEF&amp;B-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Improving KDE Raster Interpretability</p>
<p>To improve the interpretability of the KDE raster and ensure consistency across sectors, we perform the following steps:</p>
<ol type="1">
<li>Clamp and winsorize values</li>
</ol>
<ul>
<li>Negative density values (possible from smoothing) are reset to <strong>zero</strong>.<br>
</li>
<li>Extremely high values above the <strong>99th percentile</strong> are capped.<br>
</li>
<li>This reduces the influence of outliers and makes the colour scale more readable.</li>
</ul>
<ol start="2" type="1">
<li>Define consistent breaks</li>
</ol>
<ul>
<li>Using the <strong>classInt</strong> package, compute six <strong>quantile-based breakpoints</strong>.<br>
</li>
<li>These can be reused across sectors (e.g., <em>IT services, Logistics</em>) to keep maps directly comparable.</li>
</ul>
<ol start="3" type="1">
<li>Generate a cleaned raster</li>
</ol>
<ul>
<li>Create a new raster (<code>kde_rw</code>) with the adjusted values.</li>
</ul>
<ol start="4" type="1">
<li>Thematic mapping</li>
</ol>
<ul>
<li>Plot the KDE with <strong>fixed breaks</strong> and a <strong>blue sequential palette</strong>.<br>
</li>
<li>White borders show planning areas, and a thick black outline marks the overall study area.<br>
</li>
<li>Place the legend <strong>outside the map</strong> for clarity.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clamp negatives, winsorize top tail for readability</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">values</span>(kde_r, <span class="at">mat =</span> <span class="cn">FALSE</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">pmax</span>(vals, <span class="dv">0</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>cap <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">quantile</span>(vals, <span class="fl">0.99</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))   <span class="co"># 99th percentile cap</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">pmin</span>(vals, cap)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>kde_rw <span class="ot">&lt;-</span> kde_r</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">values</span>(kde_rw) <span class="ot">&lt;-</span> vals</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Pretty breaks (same set you can reuse for IT/Logistics for comparability)</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(classInt)</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>brks <span class="ot">&lt;-</span> classInt<span class="sc">::</span><span class="fu">classIntervals</span>(vals, <span class="at">n =</span> <span class="dv">6</span>, <span class="at">style =</span> <span class="st">"quantile"</span>)<span class="sc">$</span>brks</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kde_rw) <span class="sc">+</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">style =</span> <span class="st">"fixed"</span>, <span class="at">breaks =</span> brks,</span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"Blues"</span>),</span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"F&amp;B intensity</span><span class="sc">\n</span><span class="st">(registrations per km²)"</span>)</span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(subzones_use) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">lwd =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sf<span class="sc">::</span><span class="fu">st_as_sf</span>(sf<span class="sc">::</span><span class="fu">st_make_valid</span>(sf<span class="sc">::</span><span class="fu">st_union</span>(subzones_use)))) <span class="sc">+</span></span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">component.autoscale =</span> <span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex01_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>F&amp;B business registrations, KDE (Jan 2024–Jun 2025).</strong> Intensities shown as registrations per km².Bandwidth = 300 m.. The surface is zero-clamped and capped at the 99th percentile to enhance mid-range readability. Hot spots cluster around CBD/fringe-CBD and town-centre nodes; diffuse background reflects island-wide service presence.</p>
<section id="descriptive-statistics-for-the-fb-kde-surface" class="level4" data-number="6.2.1">
<h4 data-number="6.2.1" class="anchored" data-anchor-id="descriptive-statistics-for-the-fb-kde-surface"><span class="header-section-number">6.2.1</span> Descriptive Statistics for the F&amp;B KDE Surface</h4>
<p>This section generates descriptive statistics for the F&amp;B KDE surface:</p>
<ul>
<li><p><strong>Bandwidth retrieval:</strong><br>
The smoothing bandwidth used in KDE (<code>fnb_bw</code>) is loaded from cache if available, otherwise recomputed with <code>bw.diggle</code> and clamped between <strong>300–800 m</strong> for stability.</p></li>
<li><p><strong>Raster values:</strong><br>
Raw cell values from the KDE raster (<code>kde_r</code>, in registrations per km²) are extracted. Missing values are removed and any small negatives are clamped to zero.</p></li>
<li><p><strong>Summary statistics:</strong><br>
From these values, we calculate:</p>
<ul>
<li>total number of F&amp;B points (<code>n</code>),<br>
</li>
<li>bandwidth (m),<br>
</li>
<li>mean and median intensity,<br>
</li>
<li>90th and 99th percentile intensities,<br>
</li>
<li>maximum intensity.</li>
</ul></li>
<li><p><strong>Output table:</strong><br>
Results are organized into a tidy <code>tibble</code> with two columns (<code>metric</code>, <code>value</code>), making them easy to render in the report.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fnb-kde-stats</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Uses the raster you mapped (kde_r = per km²). We clamp small negatives to 0.</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># bandwidth (prefer the cached fnb_bw; fall back to recompute &amp; clamp)</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">exists</span>(<span class="st">"fnb_bw"</span>) <span class="sc">||</span> <span class="sc">!</span><span class="fu">is.numeric</span>(fnb_bw) <span class="sc">||</span> <span class="fu">is.na</span>(fnb_bw)) {</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  fnb_bw_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(<span class="st">"data"</span>, <span class="st">"rds"</span>, <span class="st">"fnb_bw.rds"</span>)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">file.exists</span>(fnb_bw_path)) {</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>    fnb_bw <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(fnb_bw_path)</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>    h_est  <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(spatstat.explore<span class="sc">::</span><span class="fu">bw.diggle</span>(fnb_ppp), <span class="at">error =</span> <span class="cf">function</span>(e) <span class="cn">NA_real_</span>)</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>    fnb_bw <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">is.na</span>(h_est)) <span class="cn">NA_real_</span> <span class="cf">else</span> <span class="fu">min</span>(<span class="fu">max</span>(<span class="fu">as.numeric</span>(h_est), <span class="dv">300</span>), <span class="dv">800</span>)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="co"># raster values</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>vals_raw <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">values</span>(kde_r, <span class="at">mat =</span> <span class="cn">FALSE</span>)</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> vals_raw[<span class="sc">!</span><span class="fu">is.na</span>(vals_raw)]</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">pmax</span>(vals, <span class="dv">0</span>)  <span class="co"># clamp negatives</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a><span class="co"># stats</span></span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>fnb_n      <span class="ot">&lt;-</span> fnb_ppp<span class="sc">$</span>n</span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>fnb_mean   <span class="ot">&lt;-</span> <span class="fu">mean</span>(vals)</span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>fnb_median <span class="ot">&lt;-</span> <span class="fu">median</span>(vals)</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>fnb_p90    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">quantile</span>(vals, <span class="fl">0.90</span>))</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>fnb_p99    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">quantile</span>(vals, <span class="fl">0.99</span>))</span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>fnb_max    <span class="ot">&lt;-</span> <span class="fu">max</span>(vals)</span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a><span class="co"># summary table</span></span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric =</span> <span class="fu">c</span>(<span class="st">"Points (n)"</span>, <span class="st">"Bandwidth (m)"</span>, <span class="st">"Mean"</span>, <span class="st">"Median"</span>, <span class="st">"P90"</span>, <span class="st">"P99"</span>, <span class="st">"Max"</span>),</span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">value  =</span> <span class="fu">c</span>(fnb_n,</span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a>             <span class="fu">ifelse</span>(<span class="fu">is.na</span>(fnb_bw), <span class="cn">NA</span>, <span class="fu">round</span>(fnb_bw,<span class="dv">0</span>)),</span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(fnb_mean,<span class="dv">2</span>),</span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(fnb_median,<span class="dv">2</span>),</span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(fnb_p90,<span class="dv">2</span>),</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(fnb_p99,<span class="dv">2</span>),</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(fnb_max,<span class="dv">2</span>))</span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  metric          value
  &lt;chr&gt;           &lt;dbl&gt;
1 Points (n)    5755   
2 Bandwidth (m)  300   
3 Mean             9.02
4 Median           1.85
5 P90             23.4 
6 P99             94.7 
7 Max            306.  </code></pre>
</div>
</div>
</section>
<section id="fb-ssic-56-kde-summary-jan-2024jun-2025" class="level4" data-number="6.2.2">
<h4 data-number="6.2.2" class="anchored" data-anchor-id="fb-ssic-56-kde-summary-jan-2024jun-2025"><span class="header-section-number">6.2.2</span> F&amp;B (SSIC 56) – KDE Summary (Jan 2024–Jun 2025)</h4>
<p>The kernel density estimation (KDE) of F&amp;B registrations (n = 5,755) reveals strong clustering around the CBD, fringe-CBD, and major town-centre nodes. The median intensity is 1.85 registrations/km², while the mean is higher (9.02/km²) due to concentrated hotspots. The upper tail is steep: the 90th percentile reaches 23.5/km², the 99th percentile 94.7/km², and the maximum exceeds 305/km². This indicates a few very dense commercial zones embedded within an otherwise broad, diffuse service distribution. The map highlights downtown areas (e.g., Raffles Place, Orchard, Bugis) alongside regional hubs such as Tampines and Jurong as consistent hotspots. In contrast, outer residential areas exhibit light, evenly spread presence, consistent with population-driven demand. Overall, the KDE confirms that F&amp;B businesses form clustered yet island-wide patterns, with strong concentration in high-footfall districts and a long tail of moderate background service intensity across Singapore.</p>
</section>
</section>
<section id="spatial-intensity-of-it-services-ssic-62-business-registrations" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="spatial-intensity-of-it-services-ssic-62-business-registrations"><span class="header-section-number">6.3</span> Spatial Intensity of IT Services (SSIC 62) Business Registrations</h3>
<p>This helper chunk sets up shared resources and utility functions for kernel density estimation (KDE):</p>
<p>Directory setup: Defines data/rds and data/rasters as cache locations, creating them if they don’t exist. These folders store RDS objects (intermediate results) and raster files (GeoTIFFs).</p>
<p>Analysis window: Ensures the spatial observation window W exists, created from the union of planning area polygons (subzones_use). This window defines the study area for point pattern analysis.</p>
<p>Breakpoints for comparability: Loads a set of fixed class breaks (kde_breaks_6.rds) that were saved from the F&amp;B analysis. These breaks will be reused across sectors so that KDE maps are directly comparable.</p>
<p>Utility functions:</p>
<p>make_ppp(sf_pts, W): converts an sf point object into a ppp (planar point pattern) object within the window W.</p>
<p>compute_kde_cached(ppp_obj, rds_im, rds_bw): computes a Gaussian KDE for the given point pattern. If cached raster (im) and bandwidth (bw) exist, they are loaded; otherwise, a new bandwidth is estimated (bw.diggle, clamped between 300–800 m), KDE computed, and results saved.</p>
<p>to_raster_km2(im): converts a spatstat image into a SpatRaster, scaling values from per m² to per km² and assigning the correct CRS (EPSG:3414).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>rds_dir     <span class="ot">&lt;-</span> <span class="st">"data/rds"</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>rasters_dir <span class="ot">&lt;-</span> <span class="st">"data/rasters"</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(rds_dir, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(rasters_dir, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure analysis window exists</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">exists</span>(<span class="st">"W"</span>)) W <span class="ot">&lt;-</span> spatstat.geom<span class="sc">::</span><span class="fu">as.owin</span>(sf<span class="sc">::</span><span class="fu">st_union</span>(subzones_use))</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the fixed breaks saved from the F&amp;B map</span></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>brks_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"kde_breaks_6.rds"</span>)</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">file.exists</span>(brks_path))  <span class="co"># ensure F&amp;B saved these earlier</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>brks <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(brks_path)</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Small utilities</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>make_ppp <span class="ot">&lt;-</span> <span class="cf">function</span>(sf_pts, W){</span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>  xy <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_coordinates</span>(sf_pts)</span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>  spatstat.geom<span class="sc">::</span><span class="fu">ppp</span>(xy[,<span class="dv">1</span>], xy[,<span class="dv">2</span>], <span class="at">window =</span> W, <span class="at">check =</span> <span class="cn">FALSE</span>)</span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb59-19"><a href="#cb59-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-20"><a href="#cb59-20" aria-hidden="true" tabindex="-1"></a>compute_kde_cached <span class="ot">&lt;-</span> <span class="cf">function</span>(ppp_obj, rds_im, rds_bw, <span class="at">sigma_min =</span> <span class="dv">300</span>, <span class="at">sigma_max =</span> <span class="dv">800</span>){</span>
<span id="cb59-21"><a href="#cb59-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">file.exists</span>(rds_im) <span class="sc">&amp;&amp;</span> <span class="fu">file.exists</span>(rds_bw)) {</span>
<span id="cb59-22"><a href="#cb59-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">im =</span> <span class="fu">readRDS</span>(rds_im), <span class="at">bw =</span> <span class="fu">readRDS</span>(rds_bw))</span>
<span id="cb59-23"><a href="#cb59-23" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb59-24"><a href="#cb59-24" aria-hidden="true" tabindex="-1"></a>    h_est <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(spatstat.explore<span class="sc">::</span><span class="fu">bw.diggle</span>(ppp_obj), <span class="at">error =</span> <span class="cf">function</span>(e) <span class="dv">400</span>)</span>
<span id="cb59-25"><a href="#cb59-25" aria-hidden="true" tabindex="-1"></a>    bw    <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="fu">max</span>(<span class="fu">as.numeric</span>(h_est), sigma_min), sigma_max)</span>
<span id="cb59-26"><a href="#cb59-26" aria-hidden="true" tabindex="-1"></a>    im    <span class="ot">&lt;-</span> spatstat.explore<span class="sc">::</span><span class="fu">density.ppp</span>(ppp_obj, <span class="at">sigma =</span> bw, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span>)</span>
<span id="cb59-27"><a href="#cb59-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">saveRDS</span>(im, rds_im); <span class="fu">saveRDS</span>(bw, rds_bw)</span>
<span id="cb59-28"><a href="#cb59-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">im =</span> im, <span class="at">bw =</span> bw)</span>
<span id="cb59-29"><a href="#cb59-29" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb59-30"><a href="#cb59-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb59-31"><a href="#cb59-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-32"><a href="#cb59-32" aria-hidden="true" tabindex="-1"></a>to_raster_km2 <span class="ot">&lt;-</span> <span class="cf">function</span>(im){</span>
<span id="cb59-33"><a href="#cb59-33" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(im <span class="sc">*</span> <span class="fl">1e6</span>)   <span class="co"># per m^2 -&gt; per km^2</span></span>
<span id="cb59-34"><a href="#cb59-34" aria-hidden="true" tabindex="-1"></a>  terra<span class="sc">::</span><span class="fu">crs</span>(r) <span class="ot">&lt;-</span> <span class="st">"EPSG:3414"</span></span>
<span id="cb59-35"><a href="#cb59-35" aria-hidden="true" tabindex="-1"></a>  r</span>
<span id="cb59-36"><a href="#cb59-36" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This block reproduces the KDE workflow for the IT (SSIC 62) sector and plots it on the <strong>same scale</strong> as F&amp;B for apples-to-apples comparison.</p>
<ul>
<li><p><strong>File paths:</strong><br>
Sets RDS/GeoTIFF cache targets for the IT KDE image (<code>it_kde_im.rds</code>), bandwidth (<code>it_bw.rds</code>), and raster (<code>it_kde_per_km2.tif</code>).</p></li>
<li><p><strong>Point pattern setup:</strong><br>
Filters IT registrations from <code>biz_pts_use</code>, converts them to a <code>ppp</code> object within the study window <code>W</code> via <code>make_ppp()</code>.</p></li>
<li><p><strong>KDE with caching:</strong></p>
<ul>
<li><code>compute_kde_cached()</code> loads precomputed KDE + bandwidth if present; otherwise it estimates bandwidth (Diggle, clamped 300–800 m), computes a Gaussian KDE, and caches both.<br>
</li>
<li><code>to_raster_km2()</code> converts the KDE image to a <code>SpatRaster</code> and rescales units to <strong>registrations per km²</strong>.<br>
</li>
<li>The raster is written once as a GeoTIFF for reuse.</li>
</ul></li>
<li><p><strong>Value cleaning (no winsorizing):</strong><br>
Negative cells are clamped to zero to remove smoothing artefacts. Unlike F&amp;B, no top-tail winsorizing is applied here, because we will <strong>reuse the fixed breaks</strong> saved from F&amp;B (<code>brks</code>) for strict comparability.</p></li>
<li><p><strong>Mapping with shared breaks:</strong><br>
Plots the cleaned IT raster using <code>style = "fixed"</code> + <code>breaks = brks</code> (the exact class limits from F&amp;B), a blue sequential scale, white subzone borders, and a black outer boundary.<br>
The legend sits outside for clarity.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>it_im_rds <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"it_kde_im.rds"</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>it_bw_rds <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"it_bw.rds"</span>)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>it_tif    <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rasters_dir, <span class="st">"it_kde_per_km2.tif"</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Build ppp</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>it_sf  <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(biz_pts_use, sector <span class="sc">==</span> <span class="st">"IT (62)"</span>)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>it_ppp <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(it_sf, W)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="co"># KDE (load/compute), convert to per-km^2 raster, save GeoTIFF (first time)</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>it_kde <span class="ot">&lt;-</span> <span class="fu">compute_kde_cached</span>(it_ppp, it_im_rds, it_bw_rds)</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>it_r   <span class="ot">&lt;-</span> <span class="fu">to_raster_km2</span>(it_kde<span class="sc">$</span>im)</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(it_tif)) terra<span class="sc">::</span><span class="fu">writeRaster</span>(it_r, it_tif, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean negatives (don’t winsorize so we keep common breaks from F&amp;B)</span></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>vals  <span class="ot">&lt;-</span> <span class="fu">pmax</span>(terra<span class="sc">::</span><span class="fu">values</span>(it_r, <span class="at">mat =</span> <span class="cn">FALSE</span>), <span class="dv">0</span>)</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>it_rw <span class="ot">&lt;-</span> it_r; terra<span class="sc">::</span><span class="fu">values</span>(it_rw) <span class="ot">&lt;-</span> vals</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot with the SAME breaks as F&amp;B</span></span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(it_rw) <span class="sc">+</span></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(</span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">style =</span> <span class="st">"fixed"</span>, <span class="at">breaks =</span> brks,</span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.scale  =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"Blues"</span>),</span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"IT intensity</span><span class="sc">\n</span><span class="st">(registrations per km²)"</span>)</span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb60-26"><a href="#cb60-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(subzones_use) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">lwd =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb60-27"><a href="#cb60-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sf<span class="sc">::</span><span class="fu">st_as_sf</span>(sf<span class="sc">::</span><span class="fu">st_make_valid</span>(sf<span class="sc">::</span><span class="fu">st_union</span>(subzones_use)))) <span class="sc">+</span></span>
<span id="cb60-28"><a href="#cb60-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb60-29"><a href="#cb60-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">component.autoscale =</span> <span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex01_files/figure-html/kde-it-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="descriptive-statistics-for-the-it-kde-surface" class="level4" data-number="6.3.1">
<h4 data-number="6.3.1" class="anchored" data-anchor-id="descriptive-statistics-for-the-it-kde-surface"><span class="header-section-number">6.3.1</span> Descriptive Statistics for the IT KDE Surface</h4>
<p>This block computes <strong>summary statistics</strong> for the IT (SSIC 62) KDE surface:</p>
<ul>
<li><p><strong>Bandwidth retrieval:</strong><br>
Loads the cached bandwidth (<code>it_bw.rds</code>) if available; otherwise sets it to <code>NA</code>.<br>
This is the smoothing parameter used when computing the KDE.</p></li>
<li><p><strong>Raster values:</strong><br>
Extracts intensity values (registrations per km²) from the IT raster (<code>it_r</code>).<br>
Missing values are removed, and small negative values (artefacts from smoothing) are clamped to zero.</p></li>
<li><p><strong>Statistical measures:</strong><br>
From these cleaned values, the code computes:</p>
<ul>
<li><strong>Points (<code>n</code>)</strong>: number of IT registrations in the point pattern,<br>
</li>
<li><strong>Bandwidth (m)</strong>: smoothing bandwidth,<br>
</li>
<li><strong>Mean</strong> and <strong>Median</strong> intensity,<br>
</li>
<li><strong>P90</strong> and <strong>P99</strong>: the 90th and 99th percentile intensities,<br>
</li>
<li><strong>Max</strong>: maximum observed intensity value.</li>
</ul></li>
<li><p><strong>Tidy output:</strong><br>
Assembles all results into a <code>tibble</code> with three columns:</p>
<ul>
<li><code>sector</code> (always “IT (62)” here),<br>
</li>
<li><code>metric</code> (name of the statistic),<br>
</li>
<li><code>value</code> (calculated numeric result, rounded for readability).</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bandwidth: use cached value if available</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>it_bw_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"it_bw.rds"</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>it_bw <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">file.exists</span>(it_bw_path)) <span class="fu">readRDS</span>(it_bw_path) <span class="cf">else</span> <span class="cn">NA_real_</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Raster values (per km^2); clamp tiny negatives to zero</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>vals_raw <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">values</span>(it_r, <span class="at">mat =</span> <span class="cn">FALSE</span>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">pmax</span>(vals_raw[<span class="sc">!</span><span class="fu">is.na</span>(vals_raw)], <span class="dv">0</span>)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Stats</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>it_n      <span class="ot">&lt;-</span> it_ppp<span class="sc">$</span>n</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>it_mean   <span class="ot">&lt;-</span> <span class="fu">mean</span>(vals)</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>it_median <span class="ot">&lt;-</span> <span class="fu">median</span>(vals)</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>it_p90    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">quantile</span>(vals, <span class="fl">0.90</span>))</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>it_p99    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">quantile</span>(vals, <span class="fl">0.99</span>))</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>it_max    <span class="ot">&lt;-</span> <span class="fu">max</span>(vals)</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy table</span></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>it_stats <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">sector =</span> <span class="st">"IT (62)"</span>,</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric =</span> <span class="fu">c</span>(<span class="st">"Points (n)"</span>, <span class="st">"Bandwidth (m)"</span>, <span class="st">"Mean"</span>, <span class="st">"Median"</span>, <span class="st">"P90"</span>, <span class="st">"P99"</span>, <span class="st">"Max"</span>),</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">value  =</span> <span class="fu">c</span>(it_n,</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>             <span class="fu">ifelse</span>(<span class="fu">is.na</span>(it_bw), <span class="cn">NA</span>, <span class="fu">round</span>(it_bw,<span class="dv">0</span>)),</span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(it_mean,<span class="dv">2</span>),</span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(it_median,<span class="dv">2</span>),</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(it_p90,<span class="dv">2</span>),</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(it_p99,<span class="dv">2</span>),</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(it_max,<span class="dv">2</span>))</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>it_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  sector  metric          value
  &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt;
1 IT (62) Points (n)    8739   
2 IT (62) Bandwidth (m)  300   
3 IT (62) Mean            13.7 
4 IT (62) Median           1.03
5 IT (62) P90             16.9 
6 IT (62) P99            219.  
7 IT (62) Max           2352.  </code></pre>
</div>
</div>
</section>
<section id="it-services-ssic-62-kde-summary-jan-2024jun-2025" class="level4" data-number="6.3.2">
<h4 data-number="6.3.2" class="anchored" data-anchor-id="it-services-ssic-62-kde-summary-jan-2024jun-2025"><span class="header-section-number">6.3.2</span> IT Services (SSIC 62) – KDE Summary (Jan 2024–Jun 2025)</h4>
<p>The kernel density estimation (KDE) of IT services registrations (n = 8,739) shows a broad and highly diffuse spatial footprint, with hotspots concentrated in business and mixed-use zones. The chosen bandwidth (300 m) highlights dense clusters while retaining local variation. The median intensity is low at 1.03 registrations/km², but the mean rises to 13.7/km², reflecting the influence of high-density nodes. The upper tail is heavy: the 90th percentile reaches 16.9/km², the 99th percentile surges to 219/km², and the maximum exceeds 2,350/km². These figures indicate that while most of the island experiences modest IT business presence, a few concentrated commercial zones (notably CBD, One-North, and regional hubs like Tampines and Jurong East) dominate the distribution. Compared to F&amp;B, IT services exhibit wider dispersal across industrial estates and mixed-use clusters, consistent with the sector’s reliance on both centralised office hubs and distributed business parks.</p>
</section>
</section>
<section id="spatial-intensity-of-logistics-services-ssic-52-business-registrations" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="spatial-intensity-of-logistics-services-ssic-52-business-registrations"><span class="header-section-number">6.4</span> Spatial Intensity of Logistics Services (SSIC 52) Business Registrations</h3>
<p>This block repeats the KDE workflow for <strong>Logistics/Warehousing (SSIC 52)</strong> and renders it on the <strong>same scale</strong> as F&amp;B/IT for strict cross-sector comparison.</p>
<ul>
<li><p><strong>Cache paths:</strong><br>
Defines where to store/load the KDE image (<code>log_kde_im.rds</code>), the chosen bandwidth (<code>log_bw.rds</code>), and the exported GeoTIFF (<code>log_kde_per_km2.tif</code>).</p></li>
<li><p><strong>Point pattern:</strong><br>
Filters Logistics/Warehousing registrations from <code>biz_pts_use</code>, then converts them to a <code>ppp</code> object within the study window <code>W</code> using <code>make_ppp()</code>.</p></li>
<li><p><strong>KDE with caching + export:</strong></p>
<ul>
<li><code>compute_kde_cached()</code> loads an existing KDE and bandwidth if present; otherwise it estimates bandwidth (Diggle, clamped 300–800 m), computes a Gaussian KDE, and saves both.<br>
</li>
<li><code>to_raster_km2()</code> converts the KDE to a <code>SpatRaster</code> and rescales units to <strong>registrations per km²</strong>.<br>
</li>
<li>The raster is written once to GeoTIFF for reuse.</li>
</ul></li>
<li><p><strong>Value cleanup (no winsorizing):</strong><br>
Negative artefacts from smoothing are clamped to zero; no upper-tail capping here so we can directly reuse <strong>common class breaks</strong>.</p></li>
<li><p><strong>Mapping with shared breaks:</strong><br>
Plots the cleaned Logistics raster using <code>style = "fixed"</code> + <code>breaks = brks</code> — the exact breakpoints saved from the F&amp;B map.</p>
<ul>
<li>Identical colours mean identical intensity ranges across sectors.<br>
</li>
<li>Adds white subzone borders, a black outer boundary, and an outside legend for readability.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>log_im_rds <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"log_kde_im.rds"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>log_bw_rds <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"log_bw.rds"</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>log_tif    <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rasters_dir, <span class="st">"log_kde_per_km2.tif"</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Build ppp</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>log_sf  <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(biz_pts_use, sector <span class="sc">==</span> <span class="st">"Logistics/Warehousing (52)"</span>)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>log_ppp <span class="ot">&lt;-</span> <span class="fu">make_ppp</span>(log_sf, W)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="co"># KDE (load/compute), convert to per-km^2 raster, save GeoTIFF (first time)</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>log_kde <span class="ot">&lt;-</span> <span class="fu">compute_kde_cached</span>(log_ppp, log_im_rds, log_bw_rds)</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>log_r   <span class="ot">&lt;-</span> <span class="fu">to_raster_km2</span>(log_kde<span class="sc">$</span>im)</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(log_tif)) terra<span class="sc">::</span><span class="fu">writeRaster</span>(log_r, log_tif, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean negatives; keep common breaks from F&amp;B</span></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a>vals   <span class="ot">&lt;-</span> <span class="fu">pmax</span>(terra<span class="sc">::</span><span class="fu">values</span>(log_r, <span class="at">mat =</span> <span class="cn">FALSE</span>), <span class="dv">0</span>)</span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a>log_rw <span class="ot">&lt;-</span> log_r; terra<span class="sc">::</span><span class="fu">values</span>(log_rw) <span class="ot">&lt;-</span> vals</span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot with the SAME breaks as F&amp;B</span></span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(log_rw) <span class="sc">+</span></span>
<span id="cb63-21"><a href="#cb63-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(</span>
<span id="cb63-22"><a href="#cb63-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">style =</span> <span class="st">"fixed"</span>, <span class="at">breaks =</span> brks,</span>
<span id="cb63-23"><a href="#cb63-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.scale  =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"Blues"</span>),</span>
<span id="cb63-24"><a href="#cb63-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Logistics intensity</span><span class="sc">\n</span><span class="st">(registrations per km²)"</span>)</span>
<span id="cb63-25"><a href="#cb63-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb63-26"><a href="#cb63-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(subzones_use) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">lwd =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb63-27"><a href="#cb63-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(sf<span class="sc">::</span><span class="fu">st_as_sf</span>(sf<span class="sc">::</span><span class="fu">st_make_valid</span>(sf<span class="sc">::</span><span class="fu">st_union</span>(subzones_use)))) <span class="sc">+</span></span>
<span id="cb63-28"><a href="#cb63-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb63-29"><a href="#cb63-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">component.autoscale =</span> <span class="cn">FALSE</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_Home_Ex01_files/figure-html/kde-logistics-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="descriptive-statistics-for-the-logistics-kde-surface" class="level4" data-number="6.4.1">
<h4 data-number="6.4.1" class="anchored" data-anchor-id="descriptive-statistics-for-the-logistics-kde-surface"><span class="header-section-number">6.4.1</span> Descriptive Statistics for the Logistics KDE Surface</h4>
<p>This chunk produces a <strong>numerical summary</strong> for the Logistics/Warehousing (SSIC 52) KDE:</p>
<ul>
<li><p><strong>Bandwidth retrieval:</strong><br>
Looks for a cached KDE bandwidth at <code>data/rds/log_bw.rds</code>.<br>
If found, loads it into <code>log_bw</code>; otherwise sets <code>NA</code>.<br>
The bandwidth is the smoothing parameter used when computing the KDE.</p></li>
<li><p><strong>Raster values (per km²):</strong><br>
Extracts cell values from the Logistics raster (<code>log_r</code>), drops <code>NA</code>s, and clamps any tiny negative artefacts to zero (<code>pmax</code>).</p></li>
<li><p><strong>Summary statistics:</strong><br>
Computes:</p>
<ul>
<li><strong>Points (<code>n</code>)</strong>: number of Logistics points used (<code>log_ppp$n</code>),<br>
</li>
<li><strong>Bandwidth (m)</strong>: cached/loaded bandwidth (rounded),<br>
</li>
<li><strong>Mean, Median</strong> KDE intensity,<br>
</li>
<li><strong>P90, P99</strong>: 90th and 99th percentile intensities,<br>
</li>
<li><strong>Max</strong>: maximum intensity value.</li>
</ul></li>
<li><p><strong>Tidy table output:</strong><br>
Packs results into a <code>tibble</code> with columns:</p>
<ul>
<li><code>sector</code> = “Logistics/Warehousing (52)”,<br>
</li>
<li><code>metric</code> = statistic name,<br>
</li>
<li><code>value</code> = numeric result (rounded for readability).</li>
</ul>
<p>Printing <code>log_stats</code> displays the table in the document.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bandwidth: use cached value if available</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>log_bw_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(rds_dir, <span class="st">"log_bw.rds"</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>log_bw <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">file.exists</span>(log_bw_path)) <span class="fu">readRDS</span>(log_bw_path) <span class="cf">else</span> <span class="cn">NA_real_</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Raster values (per km^2); clamp tiny negatives to zero</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>vals_raw <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">values</span>(log_r, <span class="at">mat =</span> <span class="cn">FALSE</span>)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">pmax</span>(vals_raw[<span class="sc">!</span><span class="fu">is.na</span>(vals_raw)], <span class="dv">0</span>)</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Stats</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>log_n      <span class="ot">&lt;-</span> log_ppp<span class="sc">$</span>n</span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>log_mean   <span class="ot">&lt;-</span> <span class="fu">mean</span>(vals)</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>log_median <span class="ot">&lt;-</span> <span class="fu">median</span>(vals)</span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>log_p90    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">quantile</span>(vals, <span class="fl">0.90</span>))</span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>log_p99    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">quantile</span>(vals, <span class="fl">0.99</span>))</span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>log_max    <span class="ot">&lt;-</span> <span class="fu">max</span>(vals)</span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy table</span></span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a>log_stats <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">sector =</span> <span class="st">"Logistics/Warehousing (52)"</span>,</span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric =</span> <span class="fu">c</span>(<span class="st">"Points (n)"</span>, <span class="st">"Bandwidth (m)"</span>, <span class="st">"Mean"</span>, <span class="st">"Median"</span>, <span class="st">"P90"</span>, <span class="st">"P99"</span>, <span class="st">"Max"</span>),</span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">value  =</span> <span class="fu">c</span>(log_n,</span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a>             <span class="fu">ifelse</span>(<span class="fu">is.na</span>(log_bw), <span class="cn">NA</span>, <span class="fu">round</span>(log_bw,<span class="dv">0</span>)),</span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(log_mean,<span class="dv">2</span>),</span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(log_median,<span class="dv">2</span>),</span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(log_p90,<span class="dv">2</span>),</span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(log_p99,<span class="dv">2</span>),</span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(log_max,<span class="dv">2</span>))</span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a>log_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  sector                     metric          value
  &lt;chr&gt;                      &lt;chr&gt;           &lt;dbl&gt;
1 Logistics/Warehousing (52) Points (n)    1718   
2 Logistics/Warehousing (52) Bandwidth (m)  300   
3 Logistics/Warehousing (52) Mean             2.69
4 Logistics/Warehousing (52) Median           0.14
5 Logistics/Warehousing (52) P90              5.5 
6 Logistics/Warehousing (52) P99             41.6 
7 Logistics/Warehousing (52) Max            238.  </code></pre>
</div>
</div></li>
</ul>
</section>
<section id="logisticswarehousing-ssic-52-kde-summary-jan-2024jun-2025" class="level4" data-number="6.4.2">
<h4 data-number="6.4.2" class="anchored" data-anchor-id="logisticswarehousing-ssic-52-kde-summary-jan-2024jun-2025"><span class="header-section-number">6.4.2</span> Logistics/Warehousing (SSIC 52) – KDE Summary (Jan 2024–Jun 2025)</h4>
<p>The KDE of Logistics/Warehousing registrations (n = 1,718) highlights a sparse but spatially meaningful distribution. The median intensity is just 0.14 registrations/km², while the mean is moderately higher at 2.69/km², indicating a long-tailed distribution. High-intensity clusters are rare but notable: the 90th percentile reaches 5.5/km², the 99th percentile 41.7/km², and the maximum exceeds 237/km², reflecting concentrated warehousing activity in specific industrial zones. Spatially, hotspots align with Singapore’s established logistics corridors — the western region around Jurong and Tuas, port-related areas, and select eastern nodes near Changi Airport. In contrast, residential and central business districts show minimal activity, consistent with land-use zoning. The map confirms a sector shaped strongly by infrastructure access and industrial planning, producing highly localized clusters of intense activity embedded within an otherwise low-density national backdrop.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>