{
  "hash": "c95efb2cb8caf80e14bcc7d4e02b41de",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 1\"\nauthor: \"Gautamgovan\"\ndate: \"September 13, 2025\"\ndate-modified: \"last-modified\"\nformat: \n  html:\n    toc: true\n    number-sections: true\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Overview \n\nThis take-home exercise investigates the **spatial** (“where”) and **spatio-temporal** (“where + when”) patterns of **new business registrations in Singapore** between **1 Jan 2024 and 30 Jun 2025**. Using the ACRA “Information on Corporate Entities” datasets and SSIC 2020 classifications, we select at least **three business types** (2- or 3-digit SSIC) and analyse how their locations and intensities evolve over time.\n\nOur workflow mirrors the point-pattern framework taught in class:\n\n- **Data wrangling & geocoding:** tidy ACRA records, standardise dates/SSIC codes, and geocode by postal code via OneMap; convert to `sf` with SVY21 (EPSG:3414).\n- **Exploratory mapping:** counts by subzone/planning area to establish baseline patterns.\n- **First-order analysis (intensity):** **Kernel Density Estimation (KDE)** to reveal spatial hot spots for each SSIC and period.\n- **Second-order analysis (dependence):** **Ripley’s K / CSR envelopes** to test whether registrations are clustered, random, or dispersed.\n- **Spatio-temporal analysis:** **STKDE** (monthly slices) to detect **emerging, persistent, and fading** clusters over the study window.\n\nThe results are communicated through cartographic maps and concise figure captions  words , followed by a synthesis translating findings into **urban land-use and economic development implications**—e.g., infrastructure readiness, zoning flexibility, activation of under-served subzones, and monitoring of over-concentration risks.\n\n## The Data\n\nThis study uses ACRA corporate entity registrations combined with reference layers and services to enable spatial and spatio-temporal analysis.\n\n### Data sources\n\n| Dataset Name | Description | Format | Provider | Notes |\n|---|---|---|---|---|\n| **ACRA – Information on Corporate Entities (A–Z, Others)** | All entity registrations. Used to extract new businesses by SSIC and date. | CSV (27 files) | data.gov.sg / ACRA | Split alphabetically: A–Z plus a 27th file for names starting with digits/symbols. |\n| **SSIC 2020** | Singapore Standard Industrial Classification; used to choose business types (2-/3-/5-digit). | CSV/XLSX | SingStat | We derive `ssic2`, `ssic3` and use `primary_ssic_code`. |\n| **OneMap Search API** | Geocoding service to convert postal codes to coordinates. | Web API | SLA / OneMap | Returns WGS84 (lat/lon). We transform to SVY21 (EPSG:3414). |\n| **Master Plan Subzones (MPSZ 2024)** | Administrative subzone polygons for aggregation and mapping. | GPKG/Shapefile | data.gov.sg / URA/SLA | Reprojected to SVY21 (EPSG:3414) for analysis. |\n\n### Fields used (ACRA)\n\n| Field | Meaning | Example |\n|---|---|---|\n| `uen` | Unique Entity Number (entity identifier) | 201912345K |\n| `entity_name` | Registered business name | ABC PTE. LTD. |\n| `registration_incorporation_date` | Registration date (YYYY-MM-DD) | 2025-03-14 |\n| `primary_ssic_code` | Primary SSIC code (2/3/4/5-digit) | 56111 |\n| `postal_code` | Registered postal code (should be 6 digits) | 018989 |\n| `entity_type` / `status` | Type/status if required for filtering | LIVE COMPANY |\n\n> Additional columns may exist in different ACRA dumps; we standardise names with `janitor::clean_names()` and coalesce equivalent fields where needed.\n\n### Study coverage\n\n- **Temporal window:** 1 Jan 2024 – 30 Jun 2025 (inclusive).  \n- **Spatial extent:** Singapore national boundary; mapping/aggregation by **subzone** and **planning area**.  \n- **Business scope:** At least **three** SSIC types (2- or 3-digit groups, or 5-digit subclasses), selected prior to analysis.\n\n### Pre-processing & wrangling (summary)\n\n- Read and row-bind **all 27 ACRA CSVs**; add `source_file` for provenance.  \n- Standardise fields: parse `registration_incorporation_date` as Date (UTC), derive `year`, `month`.  \n- **Postal code hygiene:** keep digits only, left-pad to 6; drop non-6-digit values before geocoding.  \n- **Deduplicate** by `uen` + `registration_incorporation_date` (if necessary).  \n- Filter to the target SSIC code set and to the study window.  \n- **Geocode** unique postal codes via OneMap; join `X`/`Y` back to ACRA records.  \n- Convert to `sf` (WGS84) → transform to **SVY21 (EPSG:3414)** for distance-based methods.  \n- Join subzone attributes; save intermediates as RDS for reproducibility.\n\n### Data quality & limitations\n\n- **Geocoding precision:** Postal codes resolve to building/entrance centroids, not unit-level; some industrial sites share codes.  \n- **Registration vs. operation:** Registration date ≠ opening date; counts reflect legal registrations.  \n- **Address anomalies:** Legacy/PO box or malformed postcodes may not geocode; these are excluded.  \n- **Classification drift:** SSIC codes can change over time; we use the recorded `primary_ssic_code` as-is.\n\n### Coordinate reference systems (CRS)\n\n- **Input:** WGS84 (EPSG:4326) from OneMap.  \n- **Analysis/Maps:** SVY21 / Singapore TM (EPSG:3414), metres, suitable for KDE and K-functions.\n\n### Ethical/usage notes\n\n- ACRA data contains **entity names** (public corporate info), not personal data.  \n- Results are aggregated for planning insights; avoid singling out individual firms.\n\n## Load Packages\n\nFollowing code chunk is used to load neccessary packages \n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  tidyverse,   # dplyr/readr/purrr/stringr\n  sf, tmap,    # geospatial + mapping\n  httr,        # OneMap API calls\n  lubridate,   # year(), month(), etc.\n  spatstat,    # KDE, K-function, CSR (monolithic ok)\n  spNetwork,   # network KDE (optional/bonus)\n  sparr,       # relative risk (optional/bonus)\n  plotly,      # interactive plots (optional)\n  gtsummary,   # summary tables \n  dplyr,\n  janitor,\n  stringr,\n  readr,\n  purrr\n)\n```\n:::\n\n## Data Wrangling \n### Preparing the Subzone Boundary (why & how)\n\nThis chunk converts URA’s **Master Plan Subzone (No Sea)** GeoJSON into a clean, projected **GeoPackage** with consistent field names. We use it as:\n1) the **analysis window** for point-pattern methods, and  \n2) the **join layer** to aggregate new businesses by subzone/planning area.\nExtract data for planning \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsz_raw_path <- \"data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaGEOJSON.geojson\"\n\nsubzones <- st_read(sz_raw_path, quiet = TRUE) %>%\n  clean_names() %>%                 # lower_case_names\n  st_make_valid() %>%               # fix any tiny geometry issues\n  st_transform(3414)                # SVY21 metres (needed for KDE/K-functions)\n```\n:::\n\n\nStandardise key attribute names \n\n::: {.cell}\n\n```{.r .cell-code}\n# Helper: extract a field value from the HTML in `description`\nextract_field <- function(html, key){\n  m <- str_match(html, paste0(\"<th>\", key, \"</th>\\\\s*<td>([^<]*)</td>\"))\n  val <- m[, 2]\n  val <- ifelse(is.na(val) | val == \"\", NA_character_, str_squish(val))\n  return(val)\n}\n\nsubzones_std <- subzones %>%\n  mutate(\n    SUBZONE_NO = as.integer(extract_field(description, \"SUBZONE_NO\")),\n    SUBZONE_N  = extract_field(description, \"SUBZONE_N\"),\n    SUBZONE_C  = extract_field(description, \"SUBZONE_C\"),\n    CA_IND     = extract_field(description, \"CA_IND\"),\n    PLN_AREA_N = extract_field(description, \"PLN_AREA_N\"),\n    PLN_AREA_C = extract_field(description, \"PLN_AREA_C\"),\n    REGION_N   = extract_field(description, \"REGION_N\"),\n    REGION_C   = extract_field(description, \"REGION_C\"),\n    FMEL_UPD_D = extract_field(description, \"FMEL_UPD_D\")\n  ) %>%\n  select(SUBZONE_NO, SUBZONE_N, SUBZONE_C, CA_IND,\n         PLN_AREA_N, PLN_AREA_C, REGION_N, REGION_C, FMEL_UPD_D, geometry) %>%\n  st_make_valid() %>%\n  st_transform(3414)\n\n# save a clean, fast-to-load copy\nst_write(subzones_std, \"data/geospatial/mpsz_subzones_2019_nosea.gpkg\",\n         layer = \"subzones\", delete_dsn = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDeleting source `data/geospatial/mpsz_subzones_2019_nosea.gpkg' using driver `GPKG'\nWriting layer `subzones' to data source \n  `data/geospatial/mpsz_subzones_2019_nosea.gpkg' using driver `GPKG'\nWriting 332 features with 9 fields and geometry type Unknown (any).\n```\n\n\n:::\n:::\n\n### Load & Tidy Acra \n\n\n::: {.cell}\n\n```{.r .cell-code}\naspatial_dir <- \"data/aspatial\"\nrds_dir      <- \"data/rds\"\ndir.create(rds_dir, showWarnings = FALSE, recursive = TRUE)\nfile_list <- list.files(aspatial_dir, pattern = \"^ACRA.*\\\\.csv$\", full.names = TRUE)\n\nacra_raw <- file_list |>\n  map_dfr(~ read_csv(.x, show_col_types = FALSE)) |>\n  clean_names()\n\n# 2) Tidy dates, SSIC, postal codes; derive time fields; filter study window\nacra_tidy <- acra_raw |>\n  mutate(\n    reg_date  = as.Date(registration_incorporation_date),\n    year      = year(reg_date),\n    month_num = month(reg_date),\n    month     = month(reg_date, label = TRUE, abbr = TRUE),\n\n    # keep only digits in postal_code; left-pad to 6\n    postal_code = postal_code |>\n      str_replace_all(\"[^0-9]\", \"\") |>\n      str_pad(width = 6, side = \"left\", pad = \"0\"),\n\n    # normalise primary SSIC to 5 chars, and derive 2-/3-digit prefixes\n    primary_ssic_code = str_pad(str_sub(primary_ssic_code, 1, 5), 5, pad = \"0\"),\n    ssic2 = str_sub(primary_ssic_code, 1, 2),\n    ssic3 = str_sub(primary_ssic_code, 1, 3)\n  ) |>\n  filter(!is.na(reg_date),\n         reg_date >= as.Date(\"2024-01-01\"),\n         reg_date <= as.Date(\"2025-06-30\"))\n```\n:::\n\n### Select the 3 Industries \nChoosing the three industries\n\nThe assignment requires at least three business types. We select broad, policy-relevant **2-digit SSIC** groups that span consumer, knowledge, and logistics activities:\n\n- **56 — Food & Beverage Service Activities** (restaurants, cafés, bars)  \n- **62 — Computer programming, IT consultancy & related activities**  \n- **52 — Warehousing & support activities for transportation**  \n\nIn the code below, we:\n\n1. **Build** a small lookup to attach readable sector labels to each 2-digit SSIC.  \n2. **Filter** the cleaned ACRA records to these codes.  \n3. **Produce** a quick *sector × year* table to sanity-check sample sizes for 2024 and 2025.  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 56 = Food & Beverage, 62 = Information Technology, 52 = Warehousing & support activities for transport\ntargets <- tibble(\n  ssic2 = c(\"56\", \"62\", \"52\"),\n  sector = c(\"F&B (56)\", \"IT (62)\", \"Logistics/Warehousing (52)\")\n)\n\nbiz_sel <- acra_tidy |>\n  filter(ssic2 %in% targets$ssic2) |>\n  left_join(targets, by = \"ssic2\")\n\ntable(biz_sel$sector, biz_sel$year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            \n                             2024 2025\n  F&B (56)                   3793 1965\n  IT (62)                    5845 2895\n  Logistics/Warehousing (52)  995  723\n```\n\n\n:::\n:::\n\n### Geocode unique postcodes with OneMap \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Helper that hits OneMap Search API for one postcode\nonemap_lookup <- function(pc){\n  res <- GET(\"https://onemap.gov.sg/api/common/elastic/search\",\n             query = list(searchVal = pc, returnGeom = \"Y\", getAddrDetails = \"Y\", pageNum = \"1\"))\n  js <- content(res)\n  if (!is.null(js$found) && js$found > 0) {\n    r <- js$results[[1]]\n    tibble(POSTAL = r$POSTAL, X = as.numeric(r$X), Y = as.numeric(r$Y))\n  } else {\n    tibble(POSTAL = pc, X = NA_real_, Y = NA_real_)\n  }\n}\n\n# Geocode unique postcodes\npcs <- biz_sel$postal_code |> unique()\ngeo_tbl <- map_dfr(pcs, ~ tryCatch(onemap_lookup(.x), error = function(e)\n  tibble(POSTAL = .x, X = NA_real_, Y = NA_real_)))\n\n# Join back and keep geocoded rows\nbiz_geo <- biz_sel |>\n  left_join(geo_tbl, by = c(\"postal_code\" = \"POSTAL\")) |>\n  filter(!is.na(X), !is.na(Y))\n```\n:::\n\n\n### Convert to sf, project to SVY21, and join subzones\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_pts <- st_as_sf(biz_geo, coords = c(\"X\",\"Y\"), crs = 4326) |>\n  st_transform(3414) |>\n  st_join(subzones_std |> dplyr::select(SUBZONE_N, PLN_AREA_N), left = TRUE)\n\n# Save intermediates for fast reload\nwrite_rds(acra_tidy, file.path(rds_dir, \"acra_tidy_2024H1_2025H1.rds\"))\nwrite_rds(biz_pts,  file.path(rds_dir, \"biz_points_geocoded.rds\"))\n```\n:::\n\n### Load precomputed outputs\n\n::: {.cell}\n\n```{.r .cell-code}\nacra_tidy <- readr::read_rds(file.path(rds_dir, \"acra_tidy_2024H1_2025H1.rds\"))\nbiz_pts   <- readr::read_rds(file.path(rds_dir, \"biz_points_geocoded.rds\"))\n```\n:::\n\n\n### Quick sanity check \n#### counts, CRS, validity\n\n::: {.cell}\n\n```{.r .cell-code}\n# Expect these to exist from earlier chunks:\nstopifnot(exists(\"subzones_std\"), exists(\"biz_pts\"))\n\n# Basic shapes\nnrow(subzones_std); nrow(biz_pts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 332\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16213\n```\n\n\n:::\n\n```{.r .cell-code}\n# CRS should be SVY21 / EPSG:3414\nst_crs(subzones_std)$epsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3414\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(biz_pts)$epsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3414\n```\n\n\n:::\n\n```{.r .cell-code}\n# Any invalid geometries?\nall(st_is_valid(subzones_std))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nall(st_is_valid(biz_pts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\n# Any missing coordinates?\nsum(is.na(st_coordinates(biz_pts)[,1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(st_coordinates(biz_pts)[,2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Quick distribution check\nbiz_pts |>\n  st_drop_geometry() |>\n  count(sector, year, name = \"n\") |>\n  arrange(sector, year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  sector                      year     n\n  <chr>                      <dbl> <int>\n1 F&B (56)                    2024  3791\n2 F&B (56)                    2025  1965\n3 IT (62)                     2024  5844\n4 IT (62)                     2025  2895\n5 Logistics/Warehousing (52)  2024   995\n6 Logistics/Warehousing (52)  2025   723\n```\n\n\n:::\n:::\n\n#### Are points inside Singapore subzones?\n\n::: {.cell}\n\n```{.r .cell-code}\ninside <- st_intersects(biz_pts, subzones_std, sparse = TRUE)\nmean(lengths(inside) > 0)   # share of points that fall in a subzone (expect ~1)\n```\n:::\n\nwe find that intersects results in 0 which means some thing went wrong somewhere\ntherefore we rectify this in the next Sub section \n\n#### Rebuild the sf points with the correct CRS directly (no transform)\n\n::: {.cell}\n\n```{.r .cell-code}\n# X/Y from OneMap are already SVY21 metres → set crs = 3414 and DO NOT transform\nbiz_pts <- st_as_sf(biz_geo, coords = c(\"X\",\"Y\"), crs = 3414) |>\n  st_join(subzones_std |> dplyr::select(SUBZONE_N, PLN_AREA_N), left = TRUE)\n\n# Quick sanity\nstopifnot(st_crs(biz_pts)$epsg == 3414)\nmean(lengths(st_intersects(biz_pts, subzones_std)) > 0)  # should be ~1\n\n# Overwrite the saved file\nwrite_rds(biz_pts, file.path(rds_dir, \"biz_points_geocoded.rds\"))\n```\n:::\n\n\n#### Load precomputed outputs again\n\n::: {.cell}\n\n```{.r .cell-code}\nacra_tidy <- readr::read_rds(file.path(rds_dir, \"acra_tidy_2024H1_2025H1.rds\"))\nbiz_pts   <- readr::read_rds(file.path(rds_dir, \"biz_points_geocoded.rds\"))\n```\n:::\n\n#### Quick Check again\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: qc-rebuild-using-biz-pts\n#| eval: true\n# Coordinate ranges in SVY21 metres\ncoords <- sf::st_coordinates(biz_pts)\nsummary(coords)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       X               Y        \n Min.   : 4721   Min.   :24733  \n 1st Qu.:28071   1st Qu.:29868  \n Median :29744   Median :33206  \n Mean   :29492   Mean   :34315  \n 3rd Qu.:32938   3rd Qu.:36953  \n Max.   :53137   Max.   :50104  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Validity + missing checks\nall(sf::st_is_valid(biz_pts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(coords[,1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(coords[,2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Coverage inside subzones\ninside <- sf::st_intersects(biz_pts, subzones_std, sparse = TRUE)\nmean(lengths(inside) > 0)   # should be ~1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\nNow intersects() does leave 1 which means all points are in Singapore\n\n#### Quick Map \n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(subzones_std) + tm_polygons(col = \"grey90\", border.col = \"white\") +\ntm_shape(biz_pts) + tm_dots(size = 0.02, alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n### Removing unwanted planning areas\n\n\nTo avoid empty polygons biasing our maps and point-pattern statistics, we trim the study area to places that actually have registrations. Specifically, we:\n\n- **Keep** planning areas with ≥ 1 geocoded point (computed from `biz_pts`).  \n- **Exclude** *NORTH-EASTERN ISLANDS* on purpose (offshore, no relevant activity for our scope).  \n- **Keep** *WESTERN ISLANDS* because logistics/port activity is plausible.  \n- **Filter** both the polygon layer (`subzones_std → subzones_use`) and the points (`biz_pts → biz_pts_use`) so subsequent joins and KDE/K-functions use a consistent window.  \n\nThis reduces noise, speeds processing, and prevents intensity estimates from being diluted by large empty areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Planning areas that have at least one point\nkeep_pa <- biz_pts |>\n  st_drop_geometry() |>\n  count(PLN_AREA_N, name = \"n\") |>\n  filter(n > 0) |>\n  pull(PLN_AREA_N)\n\nsubzones_use <- subzones_std |> filter(PLN_AREA_N %in% keep_pa)\n\nsubzones_use <- subzones_std |>\n  dplyr::filter(PLN_AREA_N %in% keep_pa,\n                PLN_AREA_N != \"NORTH-EASTERN ISLANDS\")\n\n#  also drop any biz points that lie in North-Eastern Islands,\n# or that didn’t pick up a planning area for any reason.\nbiz_pts_use <- biz_pts |>\n  dplyr::filter(!is.na(PLN_AREA_N),\n                PLN_AREA_N != \"NORTH-EASTERN ISLANDS\")\n```\n:::\n\n\n#### Map Check \n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(subzones_use) + tm_polygons(col = \"grey90\", border.col = \"white\") +\ntm_shape(biz_pts) + tm_dots(size = 0.02, alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n## EDA\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sector x Year counts\nbiz_pts_use |>\n  st_drop_geometry() |>\n  count(sector, year, name = \"n\") |>\n  arrange(sector, year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  sector                      year     n\n  <chr>                      <dbl> <int>\n1 F&B (56)                    2024  3790\n2 F&B (56)                    2025  1965\n3 IT (62)                     2024  5844\n4 IT (62)                     2025  2895\n5 Logistics/Warehousing (52)  2024   995\n6 Logistics/Warehousing (52)  2025   723\n```\n\n\n:::\n:::\n\n\n### Top Planning Areas per sector \n\n::: {.cell}\n\n```{.r .cell-code}\n# Top Planning Areas per sector (top 10)\ntop_pa <- biz_pts_use |>\n  st_drop_geometry() |>\n  count(sector, PLN_AREA_N, name = \"n\") |>\n  group_by(sector) |>\n  slice_max(n, n = 10, with_ties = FALSE) |>\n  ungroup()\n\ntop_pa\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 3\n   sector   PLN_AREA_N        n\n   <chr>    <chr>         <int>\n 1 F&B (56) GEYLANG         526\n 2 F&B (56) DOWNTOWN CORE   362\n 3 F&B (56) KALLANG         294\n 4 F&B (56) WOODLANDS       287\n 5 F&B (56) OUTRAM          283\n 6 F&B (56) BEDOK           269\n 7 F&B (56) HOUGANG         254\n 8 F&B (56) SEMBAWANG       210\n 9 F&B (56) TOA PAYOH       210\n10 F&B (56) YISHUN          209\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n\n### Subzone coverage check: how many subzones have ≥1 registration (by sector)\n\n::: {.cell}\n\n```{.r .cell-code}\n# all sector × subzone combinations in your study window\nall_grid <- expand_grid(\n  sector    = unique(biz_pts_use$sector),\n  SUBZONE_N = unique(subzones_use$SUBZONE_N)\n)\n\n# fill missing combos with n = 0, then compute has_any\nsubzone_cover <- biz_pts_use |>\n  st_drop_geometry() |>\n  count(sector, SUBZONE_N, name = \"n\") |>\n  right_join(all_grid, by = c(\"sector\",\"SUBZONE_N\")) |>\n  mutate(n = replace_na(n, 0), has_any = n > 0) |>\n  count(sector, has_any, name = \"subzones\") |>\n  tidyr::pivot_wider(names_from = has_any, values_from = subzones, values_fill = 0) |>\n  rename(`subzones_with_≥1` = `TRUE`, `subzones_with_0` = `FALSE`) |>\n  mutate(subzones_total = `subzones_with_≥1` + `subzones_with_0`) |>\n  select(sector, subzones_total, `subzones_with_≥1`, `subzones_with_0`) |>\n  arrange(sector)\n\nsubzone_cover\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  sector                     subzones_total `subzones_with_≥1` subzones_with_0\n  <chr>                               <int>              <int>           <int>\n1 F&B (56)                              319                278              41\n2 IT (62)                               319                260              59\n3 Logistics/Warehousing (52)            319                202             117\n```\n\n\n:::\n:::\n\n\n- **Headline:** IT and Logistics appear to “peak” in the CBD due to *registered-office addresses*; **Logistics relocates to industrial corridors** and IT to **business parks + town centres**.  \n\n- **Policy insight:**  \n  - **F&B:** island-wide, population-following growth → watch **malls/transport nodes**.  \n  - **IT:** concentrates in **CBD + parks** → plan **flexible office stock** near transit.  \n  - **Logistics:** anchored to **port/airport/expressways** → reserve **industrial land** and manage **last-mile interfaces** with residential areas.  \n\n### Choropleth:counts By Planning Area and Subzone \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Planning Area counts\npa_counts <- biz_pts_use |>\n  st_drop_geometry() |>\n  count(PLN_AREA_N, sector, name = \"n\")\n\nsubzones_pa <- subzones_use |>\n  distinct(PLN_AREA_N, .keep_all = TRUE) |>\n  left_join(pa_counts |>\n              group_by(PLN_AREA_N) |>\n              summarise(n_all = sum(n), .groups = \"drop\"),\n            by = \"PLN_AREA_N\")\n\n# Build a single Singapore outline from your filtered subzones\nsg_outline <- subzones_use |>\n  st_union() |>              # dissolve to one geometry\n  st_make_valid() |>\n  st_as_sf() |>\n  mutate(name = \"Singapore\") # (dummy column just to keep an sf)\ntmap_mode(\"plot\")\n\ntm_shape(subzones_pa) +\n  tm_polygons(\n    col = \"n_all\",\n    title = \"Registrations (all sectors)\",\n    style = \"quantile\", n = 5,\n    border.col = \"grey30\", border.lwd = 0.6\n  ) +\n  tm_shape(sg_outline) +\n  tm_borders(col = \"black\", lwd = 1.2) +   # <- country border\n  tm_layout(frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nDarker shades indicate planning areas with higher counts of registered businesses.  \n- The strongest concentrations appear in **Downtown Core, Geylang, and Kallang**, reflecting both genuine activity and the prevalence of registered office addresses in the CBD.  \n- Peripheral industrial/logistics corridors (e.g., **Jurong, Woodlands, Changi**) also show elevated counts.  \n- Many heartland towns register moderate F&B and IT entries, highlighting the **broad spatial reach of local services**.  \n\nThis baseline choropleth provides the starting point for intensity (KDE) and clustering (K/CSR) analyses in subsequent sections.\n\n## 1st Order Spatio Temporal Analysis \nConvert sf → owin and ppp\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build polygonal window (country outline) from filtered subzones\nW <- spatstat.geom::as.owin(st_union(subzones_use))   # SVY21 metres (EPSG:3414)\n\n# Helper: convert an sf points subset to ppp in window W\nto_ppp <- function(pts_sf) {\n  xy <- sf::st_coordinates(pts_sf)\n  spatstat.geom::ppp(x = xy[,1], y = xy[,2], window = W, check = FALSE)\n}\n```\n:::\n\n\n### Clark–Evans test per sector\n\nThe Clark–Evans nearest-neighbour test evaluates whether business registrations are **randomly distributed**, **clustered**, or **regularly spaced** relative to Complete Spatial Randomness (CSR).  \n\n- **Null hypothesis (H₀):** The point pattern of business registrations follows **CSR** (i.e., randomly distributed).  \n- **Alternative hypothesis (H₁):** The point pattern is **more clustered than CSR** (R < 1).  \n\nWe test this hypothesis for each selected sector (F&B, IT, Logistics/Warehousing) using both the **asymptotic test** and the **Monte Carlo CSR simulation** (999 realisations).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsectors <- unique(biz_pts_use$sector)\n# Asymptotic (no CSR simulation)\nce_asym <- lapply(sectors, function(sec){\n  X <- to_ppp(biz_pts_use %>% filter(sector == sec))\n  z <- clarkevans.test(X, correction = \"none\", clipregion = W, alternative = \"clustered\")\n  tibble(sector = sec,\n         n = X$n,\n         R = unname(z$statistic),\n         p_value = z$p.value,\n         method = \"Asymptotic (no CSR)\")\n}) %>% bind_rows()\n\n# Monte Carlo against CSR (recommended for reporting)\nset.seed(42)\nce_mc <- lapply(sectors, function(sec){\n  X <- to_ppp(biz_pts_use %>% filter(sector == sec))\n  z <- clarkevans.test(X, correction = \"none\", clipregion = W,\n                       alternative = \"clustered\", method = \"MonteCarlo\", nsim = 999)\n  tibble(sector = sec,\n         n = X$n,\n         R = unname(z$statistic),\n         p_value = z$p.value,\n         method = \"Monte Carlo (999 CSR sims)\")\n}) %>% bind_rows()\n\nce_results <- bind_rows(ce_asym, ce_mc) %>%\n  arrange(sector, method)\nce_results\n```\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nce_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  sector                         n     R p_value method                    \n  <chr>                      <int> <dbl>   <dbl> <chr>                     \n1 F&B (56)                    5755 0.365   0     Asymptotic (no CSR)       \n2 F&B (56)                    5755 0.365   0.001 Monte Carlo (999 CSR sims)\n3 IT (62)                     8739 0.248   0     Asymptotic (no CSR)       \n4 IT (62)                     8739 0.248   0.001 Monte Carlo (999 CSR sims)\n5 Logistics/Warehousing (52)  1718 0.317   0     Asymptotic (no CSR)       \n6 Logistics/Warehousing (52)  1718 0.317   0.001 Monte Carlo (999 CSR sims)\n```\n\n\n:::\n:::\n\n**Clark–Evans nearest-neighbour test (window = Singapore outline, SVY21).**  \nAcross all sectors the Clark–Evans statistic \\(R\\) is **below 1** and Monte-Carlo p-values are **significant** (\\(\\le 0.001\\)), indicating **clustering relative to CSR** at nearest-neighbour scale.\n\n- **IT (62):** \\(R \\approx 0.249\\), \\(p \\le 0.001\\) → **strongest clustering**. Likely reflects CBD/fringe-CBD registered-office addresses and business-park nodes (one-north, CBP).  \n- **Logistics/Warehousing (52):** \\(R \\approx 0.318\\), \\(p \\le 0.001\\) → **clear clustering**, consistent with industrial land concentration near port/airport/expressways.  \n- **F&B (56):** \\(R \\approx 0.365\\), \\(p \\le 0.001\\) → **clustered but more diffuse** than IT/Logistics, aligning with town-centre/mall/transit nodes spread island-wide.\n\n**Implications.**  \nNearest-neighbour distances are **smaller than CSR expectations** ( \\(R<1\\) ), so new registrations tend to occur near one another rather than randomly. This justifies:\n1) mapping **first-order intensity** with KDE to locate hot spots, and  \n2) using **K/CSR envelopes** to see at which spatial ranges clustering persists beyond nearest neighbours.\n\n### F&B \n\n\n\n\n\n",
    "supporting": [
      "Take_Home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}