---
title: "Hands-on_Ex09"
author: "Gautamgovan"
date: "November 6, 2025"
date-modified: "last-modified"
format: 
  html:
    toc: true
    toc-depth: 4
    number-sections: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## Objective

In this hands-on exercise, we will gain hands-on experience on how to model geographical accessibility by using R’s geospatial analysis packages.

## The Data

Four data sets will be used in this hands-on exercise, they are:

-   MP14_SUBZONE_NO_SEA_PL: URA Master Plan 2014 subzone boundary GIS data. This data set is downloaded from data.gov.sg.

-   hexagons: A 250m radius hexagons GIS data. This data set was created by using st_make_grid() of sf package. It is in ESRI shapefile format.

-   ELDERCARE: GIS data showing location of eldercare service. This data is downloaded from data.gov.sg. There are two versions. One in ESRI shapefile format. The other one in Google kml file format. For the purpose of this hands-on exercise, ESRI shapefile format is provided.

- OD_Matrix: a distance matrix in csv format. There are six fields in the data file. They are:
  - origin_id: the unique id values of the origin (i.e. fid of hexagon data set)
  - destination_id: the unique id values of the destination (i.e. fid of ELDERCARE data set)
  - entry_cost: the perpendicular distance between the origins and the nearest road
  - network_cost: the actual network distance from the origin and destination
  - exit_cost: the perpendicular distance between the destination and the nearest road
  - total_cost: the summation of entry_cost, network_cost and exit_cost
  
## Getting Started
Before we getting started, it is important for us to install the necessary R packages and launch them into RStudio environment.
The code chunk below installs and launches these R packages into RStudio environment.
```{r}
pacman::p_load(tmap, SpatialAcc, sf, 
               ggstatsplot, reshape2,
               tidyverse)
```
## Geospatial Data Wrangling 
### Importing geospatial data
Three geospatial data will be imported from the data/geospatial sub-folder. They are MP14_SUBZONE_NO_SEA_PL, hexagons and ELDERCARE.

The code chunk below is used to import these three data sets shapefile by using st_read() of sf packages.
