---
title: "In class Exercise 5"
author: "Gautamgovan"
date: "Sep 27, 2025"
date-modified: "last-modified"
format: 
  html:
    toc: true
    toc-depth: 4 
    number-sections: true
    
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true 
---

# In class Exercise 5: Global and Local Measures of Spatial Autocorrelation: sfdep methods

## Load Packages
```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

### The data


```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan") %>% 
  st_transform(crs = 32650)
```

```{r}

hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```
## Global Measures of Spatial Association
### Deriving queens' contiguity
```{r}
wm_q <- hunan %>%
  mutate(
    nb = st_contiguity(geometry),
    wt = st_weights(nb, style = "W"),
    .before = 1
  )
```

### Performing Global Moran'I permutation test

```{r}
set.seed(1234)
global_moran_perm(wm_q$GDPPC,wm_q$nb,wm_q$wt,nsim=99)
```
Reject null hypothesis 

They are spatially correlated 

In conclusion the GDP per capita per county level shows  spatial clustering 




