{
  "hash": "061bec16d0e5db86158859fa9e71c7bc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 3\"\nauthor: \"Gautamgovan\"\ndate: \"October 28, 2025\"\ndate-modified: \"last-modified\"\nformat: \n  html:\n    toc: true\n    toc-depth: 4\n    number-sections: true\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Predictive Modelling of HDB Resale Prices with Geographically Weighted Methods\n\n### Objective\n\nHousing is an essential component of household wealth worldwide. Purchasing a home has always represented a major investment for most individuals. The price of housing is influenced by a wide range of factors. Some are macro-level, such as the overall state of the economy or the inflation rate, while others are property-specific. These can be further categorized into structural and locational factors.\n\nStructural factors refer to the characteristics of the property itself, such as size, fittings, and tenure. Locational factors, on the other hand, relate to the neighbourhood context of the property, including proximity to childcare centres, public transport, and shopping facilities.\n\nTraditionally, housing resale price models have been estimated using the Ordinary Least Squares (OLS) method. However, this approach does not account for spatial autocorrelation and spatial heterogeneity, which are commonly present in geographic datasets such as housing transactions. When spatial autocorrelation exists, OLS estimation of housing resale price models may produce biased, inconsistent, or inefficient results (Anselin, 1998). To address these limitations, Geographically Weighted Models (GWMs) have been introduced to more accurately calibrate both explanatory and predictive models for housing resale prices.\n\nThe objective of this take-home exercise is to develop a spatially informed model to predict HDB resale prices in Singapore, making use of appropriate geospatial analytics methods.\n\nWe will develop a model to predict HDB resale prices for the period July to September 2025, using HDB resale transaction data from July 2024 to June 2025.\n\n## Installing and Loading R packages\n\n- **`sf`** — Provides modern spatial data handling in R.  \n  Used to create, transform, and manipulate spatial features (points, polygons), and perform operations like distance calculation, coordinate transformation, and spatial joins.\n\n- **`spdep`** — Supports spatial dependence analysis.  \n  Used to create neighbour lists and spatial weights, and compute Moran’s I to detect spatial autocorrelation in model residuals.\n\n- **`GWmodel`** — Core package for Geographically Weighted Regression (GWR).  \n  Used for selecting optimal bandwidths, calibrating GWR models, and generating spatially varying predictions.\n\n- **`SpatialML`** — Enables Geographically Weighted Machine Learning models such as Geographically Weighted Random Forest (GRF).  \n  Used for bandwidth selection, model fitting, and local prediction in GRF.\n\n- **`tmap`** — Thematic mapping package for spatial data visualisation.  \n  Used to visualise spatial layers, including Singapore outline maps and the spatial distribution of model residuals.\n\n- **`rsample`** — Infrastructure for resampling and splitting data.  \n  Used here for creating random subsets (e.g., for GWR calibration).\n\n- **`Metrics`** — Provides standard model evaluation metrics.  \n  Used to compute predictive accuracy measures such as RMSE and MAE for various models.\n\n- **`tidyverse`** — Collection of packages for data wrangling and visualisation (e.g., `dplyr`, `ggplot2`, `readr`, `stringr`, `purrr`).  \n  Used extensively for data cleaning, transformation, joining, and plotting.\n\n- **`httr`** — Makes HTTP requests from R.  \n  Used to query the OneMap API for address and postal code geocoding.\n\n- **`jsonlite`** — Converts JSON responses into R-friendly data structures.  \n  Used to parse JSON responses from OneMap into usable data frames.\n\n- **`progress`** — Adds progress bars to loops and long-running operations.  \n  Used to visually track geocoding progress during OneMap queries.\n\n- **`ggplot2`** — Grammar of graphics for data visualisation.  \n  Used to create histograms, bar charts, and model comparison plots.\n\n- **`caret`** — Unified machine learning framework.  \n  Used to train and tune the non-spatial Random Forest model (`ranger`) with cross-validation and hyperparameter control.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, GWmodel, SpatialML, \n               tmap, rsample, Metrics, tidyverse,httr, tidyverse, \n               jsonlite, progress,ggplot2,caret,gt)\n```\n:::\n\n\n## Data Preparation\n\n### HDB Dataset\n\n#### Selecting Date of Interest\n\nThis data set comprises of HDB resale transactions from Jan 2017 onwards. For the purpose of the hands on Exercise, the code chunk below will be used to extract a sub-set of transaction records on 5-Room flat transacted from July 2024 to September 2025.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- read_csv(\n  \"data/rawdata/HDBresale.csv\") %>%\n  filter(flat_type == \"5 ROOM\") %>%\n  filter(month >= \"2024-07\" & month < \"2025-10\")\n```\n:::\n\n\n#### Geocoding HDB resale data\n\nIn this section, we will geocode HDB resale data by using SLA Onemap Geocode API.\n\nLet us prepare a geocoding function by using the code chunk below. It aims to perform the following tasks:\n\nCombining the block and street name into an address. The addresses will be used to geocode instead of postal code that was learned in In-class Exercise 3b, Passing the address as the searchVal in our query, Sending the query to OneMapSG search. Note: Since we don’t need all the address details, we can set getAddrDetails as ‘N’, Converting response (JSON object) to text, Saving response in text form as a dataframe, and Retain the latitude and longitude for our output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\"searchVal\" = address, \n                \"returnGeom\" = \"Y\",\n                \"getAddrDetails\" = \"N\",\n                \"pageNum\" = \"1\")\n  \n  res <- GET(base_url, query = query)\n  restext<-content(res, as=\"text\")\n  \n  output <- fromJSON(restext)  %>% \n    as.data.frame %>%\n    select(results.LATITUDE, results.LONGITUDE)\n\n  return(output)\n}\n```\n:::\n\n\nNext, the code chunk below will be used to to execute the geocoding function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$LATITUDE <- 0\nHDBresale$LONGITUDE <- 0\n\nfor (i in 1:nrow(HDBresale)){\n  temp_output <- geocode(HDBresale[i, 4], HDBresale[i, 5])\n  \n  HDBresale$LATITUDE[i] <- temp_output$results.LATITUDE\n  HDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n\n\n\n\n#### Converting `storey_range` to a Numerical Value (`storey_mid`)\n\nThe `storey_range` field in the HDB resale dataset is provided as a text range such as `\"07 TO 09\"` or `\"13 TO 15\"`. Since machine learning models require numerical inputs, we convert this range into a single numeric value that approximates the floor level of the unit.\n\nThis is done by:\n\n1.  **Removing spaces** from the text\n    -   Example: `\"07 TO 09\"` → `\"07TO09\"`\n2.  **Splitting the range** into the lower and upper floor values\n    -   `\"07TO09\"` → `\"07\"` and `\"09\"`\n3.  **Calculating the midpoint** (average) of the two values\n    -   \\[ \\frac{7 + 9}{2} = 8 \\]\n4.  **Creating a new variable** named `storey_mid` to store this midpoint value.\n\nThis numeric representation allows the floor level information to be used effectively in statistical and machine learning models.\n\n5.  Remove the original storey_range column, as it is no longer needed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstorey_mid <- function(x) {\n  x %>%\n    str_replace_all(\" \", \"\") %>%    # remove spaces\n    str_split(\"TO\") %>%             # split into lower and upper floors\n    sapply(\\(v) mean(as.numeric(v)))  # convert to numeric and take midpoint\n}\n\nHDBresale <- HDBresale %>%\n  mutate(storey_mid = storey_mid(storey_range)) %>%  # create numeric floor feature\n  select(-storey_range)                              # remove the original text column\n```\n:::\n\n\n#### Converting `remaining_lease` to a Numeric Value (`remaining_lease_yrs`)\n\nThe `remaining_lease` field is provided as text (e.g., `\"87 years 4 months\"`). To use this information in modelling, we convert it into a numeric value representing the total lease remaining in **years**.\n\nThe function `convert_remaining_lease()`:\n\n1.  Extracts the number of **years**.\n2.  Extracts the number of **months** (or uses 0 if not specified).\n3.  Converts months into a fraction of a year (`months / 12`).\n4.  Adds the two together to get a single numeric value.\n\nWe then apply the function to create a new column `remaining_lease_yrs` and drop the original text column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconvert_remaining_lease <- function(x) {\n  years <- as.numeric(str_extract(x, \"\\\\d+(?=\\\\syear)\"))\n  months <- str_extract(x, \"(?<=years?\\\\s)\\\\d+(?=\\\\smonth)\") %>% as.numeric()\n  months[is.na(months)] <- 0\n  years + months/12\n}\n\nHDBresale <- HDBresale %>%\n  mutate(remaining_lease_yrs = convert_remaining_lease(remaining_lease)) %>%\n  select(-remaining_lease)\n```\n:::\n\n\n### Proximity Analysis\n\nIn this section, we will learn how to count the number of geographic entities located within a defined distance from each HDB property.\n\n#### Converting to an sf object\n\nBefore performing proximity analysis, it is important to ensure that:\n\n-   input data sets must be in sf objects, and\n-   they must be in similar projected coordinates systems.\n\nIn the code chunk below,\n\n-   st_as_sf() is used to convert HDBresale tibble data.frame to sf object by using values from LONGITUDE and LATITUDE columns to form the geometry features.\n-   st_transform() is then used to transform the sf object into svy21 projected coordinates system.\n-   the output sf object is called HDBresale_sf. It is in sf data.frame format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale %>%\n  st_as_sf(\n    coords = c(\"LONGITUDE\", \"LATITUDE\"),\n    crs=4326) %>%\n  st_transform(crs = 3414)\n```\n:::\n\n\n#### PreSchool Location\n\nNext, we will locate and download Pre-Schools Location data from Singapore’s open data portal. There are both geojson and kml version. In this exercise, the kml version will be used.\n\nThen, code chunk below will be used to import the preschool location data into R environment by using st_read() of readr package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool = st_read(\n  \"data/rawdata/PreSchoolsLocation.kml\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PRESCHOOLS_LOCATION' from data source \n  `C:\\govanzz\\ISSS626_GEO_AUG_2025\\Take_Home_Exercise\\Take_Home_Ex03\\data\\rawdata\\PreSchoolsLocation.kml' \n  using driver `KML'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nLastly, code chunk below will be used to count the number of pre-schools located within 350m of each HDB property.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_350m <- st_is_within_distance(\n  HDBresale_sf, preschool, dist = 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(WITHIN_350M_PRESCHOOL = map_int(within_350m, length))\n```\n:::\n\n\n#### Proximity to CBD\n\nThe code chunk below computes the Euclidean (straight-line) distance between each flat and the Downtown Core (CBD) centroid using Singapore’s projected coordinate system (EPSG:3414, SVY21). The resulting columns proximity_to_cbd_m and proximity_to_cbd_km represent the flat’s distance to the CBD in meters and kilometers respectively\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Define Downtown Core (CBD) coordinates (WGS84) ---\ncbd_lon <- 103.85\ncbd_lat <- 1.28967\n\n# --- Create CBD point and transform to SVY21 (3414) ---\ncbd_wgs84 <- st_sfc(st_point(c(cbd_lon, cbd_lat)), crs = 4326)\ncbd_3414  <- st_transform(cbd_wgs84, 3414)\n\n# --- Compute straight-line distance to CBD (meters / km) ---\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(\n    proximity_to_cbd_m  = as.numeric(st_distance(geometry, cbd_3414)[, 1]),\n    proximity_to_cbd_km = proximity_to_cbd_m / 1000\n  )\n```\n:::\n\n\n\n\n#### Bus Stops within 350 metres\n\nRead Bustops shp file and check CRS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbusstops <- st_read(\"data/rawdata/BusStop.shp\", quiet = TRUE)%>%\n  st_transform(crs= 3414)\nst_crs(busstops)  # check the CRS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count number of bus stops within 350 m for each HDB point\nwithin_350m <- st_is_within_distance(HDBresale_sf, busstops, dist = 350)\n\n# Add count column to main dataset\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(WITHIN_350M_BUSSTOP = purrr::map_int(within_350m, length))\n```\n:::\n\n\n#### Elder care within 350 metres\n\nRead Eldercare shapefile and check CRS\n\n\n::: {.cell}\n\n```{.r .cell-code}\neldercare <- st_read(\"data/rawdata/ELDERCARE.shp\", quiet = TRUE)%>%\n  st_transform(crs= 3414)\nst_crs(eldercare)  # check the CRS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_350m <- st_is_within_distance(HDBresale_sf, eldercare, dist = 350)\n\n#Add count column to main dataset\n\nHDBresale_sf <- HDBresale_sf %>%\nmutate(WITHIN_350M_ELDERCARE = purrr::map_int(within_350m, length))\n```\n:::\n\n\n#### Proximity to Good Primary Schools\n\nFor this part we have collected top 20 Primary Schools from Singapore in a CSV file along with its postal code , we will use One map API to geo-encode using postal code\n\nThe below code chunk gets the latitude and longitude of the school using postal codes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- 1) Read the CSV (school_name, postal_code) ---\ngood_ps <- read_csv(\"data/rawdata/good_primary_schools.csv\",\n                    show_col_types = FALSE) %>%\n  mutate(postal_code = str_pad(as.character(postal_code), 6, pad = \"0\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- 2) OneMap postal-code geocoder (returns SVY21 X/Y) ---\nonemap_lookup <- function(pc){\n  resp <- RETRY(\"GET\", \"https://onemap.gov.sg/api/common/elastic/search\",\n                query = list(searchVal = pc,\n                             returnGeom = \"Y\",\n                             getAddrDetails = \"Y\",\n                             pageNum = \"1\"),\n                quiet = TRUE)\n  js <- content(resp, as = \"parsed\")\n  if (!is.null(js$found) && js$found > 0) {\n    r <- js$results[[1]]\n    tibble(POSTAL = r$POSTAL,\n           X = as.numeric(r$X),   # SVY21 easting\n           Y = as.numeric(r$Y))   # SVY21 northing\n  } else {\n    tibble(POSTAL = pc, X = NA_real_, Y = NA_real_)\n  }\n}\n\n# --- 3) Geocode unique postcodes \npcs <- unique(good_ps$postal_code)\ngeo_tbl <- map_dfr(pcs, ~ tryCatch(onemap_lookup(.x),\n                                   error = function(e) tibble(POSTAL=.x, X=NA_real_, Y=NA_real_)))\n\nwrite_rds(geo_tbl, \"data/rds/good_ps_postal_geocode.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeo_tbl <- read_rds(\"data/rds/good_ps_postal_geocode.rds\")\n# --- 4) Join back & keep geocoded rows; make sf in SVY21 (EPSG:3414) ---\ngood_ps_sf <- good_ps %>%\n  left_join(geo_tbl, by = c(\"postal_code\" = \"POSTAL\")) %>%\n  filter(!is.na(X), !is.na(Y)) %>%\n  st_as_sf(coords = c(\"X\",\"Y\"), crs = 3414)  # OneMap X/Y are SVY21\n```\n:::\n\n\nNow the below code chunk is used to derive proximity columns to good primary schools\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- 5) Proximity features  ---\n# Count of good schools within 1 km\nidx_1km <- st_is_within_distance(HDBresale_sf, good_ps_sf, dist = 1000)\ncnt_1km <- lengths(idx_1km)\n\n# Distance to nearest good school (km)\nnearest_idx <- st_nearest_feature(HDBresale_sf, good_ps_sf)\nnearest_dist_km <- as.numeric(st_distance(HDBresale_sf, good_ps_sf[nearest_idx, ], by_element = TRUE))/1000\n\n# Add to main dataset\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(\n    WITHIN_1KM_GOOD_PS = cnt_1km,\n    dist_good_ps_km    = nearest_dist_km\n  )\n```\n:::\n\n\n#### Proximity to MRT/LRT stations\n\nThis code safely loads and processes MRT/LRT station geometries to calculate each HDB flat’s distance to its nearest station. It first reads the shapefile with error handling and removes invalid geometries. For any problematic shapes, it extracts a representative point using a safe function (safe_point). Next, it groups polygons by station name, merges them, and ensures each has one valid point in SVY21 coordinates. Finally, it computes straight-line distances (in kilometers) from each HDB flat to its nearest station and adds this as dist_mrt_km to the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1) Try reading; if a few polygons fail, catch and skip\nmrt_raw <- tryCatch(\n  st_read(\"data/rawdata/RapidTransitSystemStation.shp\", quiet = TRUE),\n  error = function(e) {\n    message(\"Some polygons failed to load; attempting partial recovery\")\n    st_read(\"data/rawdata/RapidTransitSystemStation.shp\", quiet = TRUE, stringsAsFactors = FALSE)\n  }\n)\n\n# 2) Drop any completely invalid geometries\nmrt_valid <- mrt_raw[st_is_valid(mrt_raw), ]\n\n# 3) For any remaining invalid shapes, use try() on point extraction\nsafe_point <- function(geom) {\n  pt <- try(st_point_on_surface(geom), silent = TRUE)\n  if (inherits(pt, \"try-error\")) NA else pt\n}\n\n# 4) Create one point per station safely\nmrt_pts <- mrt_valid %>%\n  group_by(STN_NAM_DE) %>%\n  summarise(geometry = {\n    # combine all parts and get a safe point\n    geom <- st_combine(geometry)\n    safe_point(geom)\n  }, .groups = \"drop\") %>%\n  filter(!st_is_empty(geometry))\n\nst_crs(mrt_pts) <- 3414  # ensure CRS SVY21\n\n# 5) Compute distance to nearest MRT/LRT (km)\nnn_idx <- st_nearest_feature(HDBresale_sf, mrt_pts)\ndist_mrt_km <- as.numeric(st_distance(HDBresale_sf, mrt_pts[nn_idx, ], by_element = TRUE)) / 1000\n\n# 6) Add to HDB dataset\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(dist_mrt_km = dist_mrt_km)\n```\n:::\n\n\n#### Proximity to Parks\n\nRead ParkFacilities (GeoJSON) and ensure CRS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparks <- st_read(\"data/rawdata/ParkFacilities.geojson\", quiet = TRUE) %>%\n  st_transform(3414)               # SVY21 metres\n```\n:::\n\n\nCompute distance to the nearest park (km) and add to dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distance to nearest park facility (km)\nnn_idx <- st_nearest_feature(HDBresale_sf, parks)\ndist_park_km <- as.numeric(\n  st_distance(HDBresale_sf, parks[nn_idx, ], by_element = TRUE)\n) / 1000\n\n# Add to main dataset\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(dist_park_km = dist_park_km)\n```\n:::\n\n\n#### Proximity to Malls\n\nRead the malls CSV (mall_name, postal_code)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmalls <- readr::read_csv(\"data/rawdata/singapore_malls_postal_codes.csv\",\n                         show_col_types = FALSE) %>%\n  dplyr::mutate(postal_code = stringr::str_pad(as.character(postal_code), 6, pad = \"0\"))\n```\n:::\n\n\nGeocode mall postal codes with OneMap (SVY21 X/Y)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nonemap_lookup <- function(pc){\n  resp <- httr::RETRY(\"GET\", \"https://onemap.gov.sg/api/common/elastic/search\",\n                      query = list(searchVal = pc,\n                                   returnGeom = \"Y\",\n                                   getAddrDetails = \"Y\",\n                                   pageNum = \"1\"),\n                      quiet = TRUE)\n  js <- httr::content(resp, as = \"parsed\")\n  if (!is.null(js$found) && js$found > 0) {\n    r <- js$results[[1]]\n    tibble::tibble(POSTAL = r$POSTAL,\n                   X = as.numeric(r$X),   # SVY21 easting\n                   Y = as.numeric(r$Y))   # SVY21 northing\n  } else {\n    tibble::tibble(POSTAL = pc, X = NA_real_, Y = NA_real_)\n  }\n}\n\npcs <- unique(malls$postal_code)\nmall_geo_tbl <- purrr::map_dfr(\n  pcs,\n  ~ tryCatch(onemap_lookup(.x),\n             error = function(e) tibble::tibble(POSTAL=.x, X=NA_real_, Y=NA_real_))\n)\n\nreadr::write_rds(mall_geo_tbl, \"data/rds/malls_postal_geocode.rds\")\n```\n:::\n\n\nJoin geocodes and create an sf layer (SVY21 / EPSG:3414)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmall_geo_tbl <- readr::read_rds(\"data/rds/malls_postal_geocode.rds\")\n\nmalls_sf <- malls %>%\n  dplyr::left_join(mall_geo_tbl, by = c(\"postal_code\" = \"POSTAL\")) %>%\n  dplyr::filter(!is.na(X), !is.na(Y)) %>%\n  sf::st_as_sf(coords = c(\"X\",\"Y\"), crs = 3414)\n```\n:::\n\n\nDerive proximity features to malls\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distance to nearest mall (km)\nmall_nn_idx <- sf::st_nearest_feature(HDBresale_sf, malls_sf)\ndist_mall_km <- as.numeric(sf::st_distance(HDBresale_sf, malls_sf[mall_nn_idx, ], by_element = TRUE)) / 1000\n\n# Count of malls within 1 km (adjust if you prefer another radius)\nmalls_within_1km <- sf::st_is_within_distance(HDBresale_sf, malls_sf, dist = 1000)\ncnt_malls_1km <- lengths(malls_within_1km)\n\n# Add to main dataset\nHDBresale_sf <- HDBresale_sf %>%\n  dplyr::mutate(\n    dist_mall_km       = dist_mall_km,\n    WITHIN_1KM_MALLS   = cnt_malls_1km\n  )\n```\n:::\n\n\n#### Proximity to CHAS clinics\n\nRead Chas data and ensure CRS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchas <- st_read(\"data/rawdata/CHASClinics.geojson\", quiet = TRUE) %>%\n  st_transform(3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distance to nearest CHAS clinic (km)\nchas_nn_idx <- st_nearest_feature(HDBresale_sf, chas)\ndist_chas_km <- as.numeric(st_distance(HDBresale_sf, chas[chas_nn_idx, ], by_element = TRUE)) / 1000\n\n# Count of CHAS clinics within 350 m\nchas_within_350m <- st_is_within_distance(HDBresale_sf, chas, dist = 350)\ncnt_chas_350m <- lengths(chas_within_350m)\n\n# Add to main dataset\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(\n    dist_chas_km    = dist_chas_km,\n    WITHIN_350M_CHAS = cnt_chas_350m\n  )\n```\n:::\n\n\n#### Proximity to Hawker Centres\n\nRead Hawker Centres GeoJSON and check CRS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhawker <- st_read(\"data/rawdata/HawkerCentresGEOJSON.geojson\", quiet = TRUE)%>%\n  st_transform(3414)\n\nst_crs(hawker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\nCompute distance to nearest hawker centre (in km) ---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhawker_nn_idx <- st_nearest_feature(HDBresale_sf, hawker)\ndist_hawker_km <- as.numeric(st_distance(HDBresale_sf, hawker[hawker_nn_idx, ], by_element = TRUE)) / 1000\n\n#  Add distance feature to HDB resale dataset\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(dist_hawker_km = dist_hawker_km)\n```\n:::\n\n\n#### Childcare Centres within 350 metres\n\nRead ChildCare Services (GeoJSON) and ensure SVY21:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare <- st_read(\"data/rawdata/ChildCareServices.geojson\", quiet = TRUE)%>%st_transform(3414)\n\nst_crs(hawker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\nCompute count within 350 m and add to main data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_350m_cc <- st_is_within_distance(HDBresale_sf, childcare, dist = 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(WITHIN_350M_CHILDCARE = lengths(within_350m_cc))\n```\n:::\n\n\n\n\n### Calculate Correlation Matrix\n\nBefore loading the predictors into a predictive model, it is always a good practice to use correlation matrix to examine if there is sign of multicollinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1) Drop geometry\nHDBresale_nogeo <- HDBresale_sf %>%\n  st_drop_geometry()\n\n# 2) Select only numeric columns for correlation\nnumeric_cols <- HDBresale_nogeo %>%\n  select(where(is.numeric))\n\n# 3) Compute correlation matrix\ncorr_matrix <- cor(numeric_cols, use = \"complete.obs\")\n\n# 4) Plot correlation matrix\ncorrplot::corrplot(corr_matrix,\n                   diag = FALSE,\n                   order = \"AOE\",\n                   tl.pos = \"td\",\n                   tl.cex = 0.6,\n                   method = \"number\",\n                   type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\nDrop Highly correlated Values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>%\n  select(-WITHIN_350M_PRESCHOOL,\n         -lease_commence_date,\n         -WITHIN_1KM_MALLS,\n         -WITHIN_1KM_GOOD_PS)\n```\n:::\n\n\n### Train–Test Split for HDB Resale Modelling\n\nThis code chunk separates the dataset into **training** and **testing** periods and removes geometry for modelling.\n\n1.  Training Set (Jul 2024 – Jun 2025) Filters `HDBresale_sf` to include resale transactions from July 2024 to June 2025, storing it as `HDB_train_sf`.\n\n2.  Test Set (Jul 2025 – Sep 2025) Filters the same dataset for resale transactions from July 2025 to September 2025, creating `HDB_test_sf`.\n\n3.  Drop Geometry for Modelling Converts both `sf` objects into regular data frames (`hdb_train`, `hdb_test`) by removing spatial geometry columns using `st_drop_geometry()`, preparing them for statistical or machine-learning models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Training: Jul 2024 – Jun 2025\nHDB_train_sf <- HDBresale_sf %>%\n  dplyr::filter(month >= \"2024-07\" & month <= \"2025-06\")\n\n# Test (prediction period): Jul 2025 – Sep 2025\nHDB_test_sf <- HDBresale_sf %>%\n  dplyr::filter(month >= \"2025-07\" & month <= \"2025-09\")\n\n# For modelling (no geometry)\nhdb_train <- HDB_train_sf %>% sf::st_drop_geometry()\nhdb_test  <- HDB_test_sf  %>% sf::st_drop_geometry()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hdb_train, aes(x = resale_price)) +\n  geom_histogram(bins = 40, fill = \"steelblue\", color = \"white\") +\n  scale_x_continuous(labels = scales::comma) +\n  labs(\n    title = \"Distribution of HDB Resale Prices (Raw)\",\n    x = \"Resale Price (SGD)\",\n    y = \"Count\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n## Building a non-spatial multiple linear regression\n\nThis code chunk fits a linear regression model (`lm_ols`) using the `lm()` function, where the log-transformed HDB resale price is the dependent variable. The model includes structural attributes (e.g., floor area, storey level, remaining lease, flat model) and locational factors such as proximity to CBD, MRT stations, parks, malls, and amenities like bus stops, childcare, eldercare, and CHAS clinics. The independent variables are selected based on their potential influence on resale price. The model is trained on the `hdb_train` dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_ols <- lm(\n  log(resale_price) ~ \n    floor_area_sqm +\n    storey_mid +\n    remaining_lease_yrs +\n    flat_model +\n    proximity_to_cbd_km +\n    WITHIN_350M_BUSSTOP +\n    WITHIN_350M_ELDERCARE +\n    dist_good_ps_km +\n    dist_mrt_km +\n    dist_park_km +\n    dist_mall_km +\n    dist_hawker_km +\n    WITHIN_350M_CHILDCARE +\n    WITHIN_350M_CHAS,\n  data = hdb_train\n)\n```\n:::\n\n\n### OLS Residual Diagnostics & Spatial Dependence Check\n\n#### Summary of the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm_ols)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(resale_price) ~ floor_area_sqm + storey_mid + \n    remaining_lease_yrs + flat_model + proximity_to_cbd_km + \n    WITHIN_350M_BUSSTOP + WITHIN_350M_ELDERCARE + dist_good_ps_km + \n    dist_mrt_km + dist_park_km + dist_mall_km + dist_hawker_km + \n    WITHIN_350M_CHILDCARE + WITHIN_350M_CHAS, data = hdb_train)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.43383 -0.06047  0.00071  0.05698  0.51139 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      11.6419030  0.0460711 252.694  < 2e-16 ***\nfloor_area_sqm                    0.0119540  0.0002794  42.792  < 2e-16 ***\nstorey_mid                        0.0067469  0.0002085  32.357  < 2e-16 ***\nremaining_lease_yrs               0.0096916  0.0001422  68.152  < 2e-16 ***\nflat_modelAdjoined flat           0.1501633  0.0257274   5.837 5.59e-09 ***\nflat_modelDBSS                    0.3521385  0.0198201  17.767  < 2e-16 ***\nflat_modelImproved                0.1454957  0.0183558   7.926 2.65e-15 ***\nflat_modelImproved-Maisonette     0.2279463  0.0488362   4.668 3.11e-06 ***\nflat_modelModel A                 0.0719204  0.0191057   3.764 0.000169 ***\nflat_modelModel A-Maisonette      0.1471605  0.0229533   6.411 1.55e-10 ***\nflat_modelPremium Apartment       0.1246484  0.0185664   6.714 2.07e-11 ***\nflat_modelPremium Apartment Loft  0.1722691  0.0490505   3.512 0.000448 ***\nflat_modelStandard                0.1894316  0.0200530   9.447  < 2e-16 ***\nflat_modelType S2                 0.2657998  0.0303147   8.768  < 2e-16 ***\nproximity_to_cbd_km              -0.0306184  0.0003744 -81.778  < 2e-16 ***\nWITHIN_350M_BUSSTOP               0.0008867  0.0004133   2.145 0.031957 *  \nWITHIN_350M_ELDERCARE            -0.0011916  0.0021181  -0.563 0.573744    \ndist_good_ps_km                   0.0044592  0.0009878   4.514 6.47e-06 ***\ndist_mrt_km                      -0.0234093  0.0038381  -6.099 1.13e-09 ***\ndist_park_km                     -0.0438653  0.0052334  -8.382  < 2e-16 ***\ndist_mall_km                     -0.0272980  0.0026134 -10.445  < 2e-16 ***\ndist_hawker_km                   -0.0374051  0.0025705 -14.552  < 2e-16 ***\nWITHIN_350M_CHILDCARE            -0.0035919  0.0005290  -6.790 1.22e-11 ***\nWITHIN_350M_CHAS                  0.0076984  0.0006132  12.554  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0901 on 6240 degrees of freedom\nMultiple R-squared:  0.7797,\tAdjusted R-squared:  0.7789 \nF-statistic: 960.1 on 23 and 6240 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe OLS model explains resale prices well, with strong effects from floor area, storey height, lease, and proximity to key amenities. Significant spatial patterns remain, motivating geographically weighted modelling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add residuals and run standard OLS diagnostics\nhdb_train$residuals <- residuals(lm_ols)\n\npar(mfrow = c(2, 2))\nplot(lm_ols)   # includes Residuals vs Fitted, Q-Q plot, etc.\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Check multicollinearity\ncar::vif(lm_ols)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          GVIF Df GVIF^(1/(2*Df))\nfloor_area_sqm        3.118037  1        1.765796\nstorey_mid            1.181813  1        1.087112\nremaining_lease_yrs   2.314616  1        1.521386\nflat_model            3.689082 10        1.067446\nproximity_to_cbd_km   1.672676  1        1.293320\nWITHIN_350M_BUSSTOP   1.185371  1        1.088748\nWITHIN_350M_ELDERCARE 1.136474  1        1.066055\ndist_good_ps_km       1.233993  1        1.110852\ndist_mrt_km           1.599653  1        1.264774\ndist_park_km          1.183192  1        1.087746\ndist_mall_km          1.441810  1        1.200754\ndist_hawker_km        1.219929  1        1.104504\nWITHIN_350M_CHILDCARE 1.212742  1        1.101246\nWITHIN_350M_CHAS      1.254051  1        1.119844\n```\n\n\n:::\n:::\n\n\nThese OLS diagnostic plots show several issues with model assumptions. The Residuals vs Fitted plot indicates slight non-linearity and heteroscedasticity. The Q-Q plot shows heavy tails, meaning residuals are not normally distributed. The Scale-Location plot confirms non-constant variance, while the Residuals vs Leverage plot shows a few high-leverage points that may disproportionately influence the model.\n\n#### Spatial autocorrelation of residuals (Moran’s I)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build neighbour structure and spatial weights\ncoords <- st_coordinates(HDB_train_sf)\nnb     <- knn2nb(knearneigh(coords, k = 8))\nlw     <- nb2listw(nb, style = \"W\")\n\n# Test for spatial autocorrelation in OLS residuals\nmoran.test(hdb_train$residuals, lw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hdb_train$residuals  \nweights: lw    \n\nMoran I statistic standard deviate = 112.57, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n     6.685898e-01     -1.596679e-04      3.529027e-05 \n```\n\n\n:::\n:::\n\n\nOLS residuals exhibit strong and significant spatial autocorrelation (Moran’s I = 0.668, p \\< 0.001), indicating substantial spatial heterogeneity and justifying the use of geographically weighted models.\n\n### Predict on the test set (Jul–Sep 2025)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_test$pred_log <- predict(lm_ols, newdata = hdb_test)\nhdb_test$pred_price <- exp(hdb_test$pred_log)\n```\n:::\n\n\n### Evaluate predictive performance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Metrics)\n\nrmse_ols <- rmse(hdb_test$resale_price, hdb_test$pred_price)\nmae_ols  <- mae(hdb_test$resale_price, hdb_test$pred_price)\nr2_ols   <- 1 - sum((hdb_test$resale_price - hdb_test$pred_price)^2) /\n                 sum((hdb_test$resale_price - mean(hdb_test$resale_price))^2)\n\nrmse_ols\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 81411.68\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_ols\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58785.22\n```\n\n\n:::\n\n```{.r .cell-code}\nr2_ols\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7815189\n```\n\n\n:::\n:::\n\n\n### Map residuals\n\nThis code first reads the **Master Plan 2019 subzone boundaries** from a KML file and transforms them into Singapore’s projected coordinate system (EPSG:3414). All subzones are dissolved into a **single outline polygon of Singapore** (`sg_outline`) using `summarise()`.\n\nTwo maps are generated using the **tmap** package:\n\n-   **Map A** displays only the Singapore outline as a base map, styled with a light grey fill and black borders.\n-   **Map B** overlays the residuals from the OLS model (`hdb_train$residuals`) onto the Singapore map using the `HDB_train_sf` spatial dataset. Points are coloured using a diverging Red-Blue palette (`-RdBu`) centered at zero, allowing for quick visual inspection of over- and under-predicted areas in the training set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1) Read Master Plan 2019 subzones and convert to EPSG:3414\nsubzones <- st_read(\n  \"data/rawdata/MasterPlan2019SubzoneBoundaryNoSeaKML.kml\",\n  quiet = TRUE\n) %>%\n  st_transform(3414)\n\n# 2) Make a single Singapore outline polygon (dissolve all subzones)\nsg_outline <- subzones %>%\n  summarise()   # dissolves into one multipart polygon\n\n# --- A) Just the Singapore outline map ----------------------------\ntmap_mode(\"plot\")\n\ntm_shape(sg_outline) +\n  tm_polygons(col = \"grey90\", border.col = \"black\") +\n  tm_layout(title = \"Singapore Outline (Master Plan 2019)\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# --- B) Outline + residual dots ------------------------------\ntrain_resid_sf <- HDB_train_sf %>%\n  mutate(residuals = hdb_train$residuals)\n\ntm_shape(sg_outline) +\n  tm_polygons(col = \"grey95\", border.col = \"black\") +\ntm_shape(train_resid_sf) +\n  tm_dots(col = \"residuals\",\n          palette = \"-RdBu\",\n          midpoint = 0,\n          size = 0.23) +\n  tm_layout(title = \"OLS Residuals (Train Set) with Singapore Outline\")\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/unnamed-chunk-46-2.png){width=672}\n:::\n:::\n\n\nThe residuals map overlays the OLS model’s training-set residuals onto the Singapore outline to reveal where the model systematically over- or under-predicts HDB resale prices. Each point represents an individual transaction, coloured by the magnitude and direction of its residual.\n\nBlue tones indicate negative residuals, meaning the model predicted prices higher than the actual transacted values. These typically appear in clusters across parts of the north, west, and eastern regions, suggesting local market characteristics—such as older stock, lower amenity access, or neighbourhood-specific effects—not fully captured by the model.\n\nConversely, orange to red tones represent positive residuals, where actual prices exceeded predictions. These are concentrated in pockets of central, northeastern, and western estates, potentially reflecting unmodelled premiums such as micro-location desirability, school quality, renovation levels, or nearby upcoming developments.\n\nThe presence of spatially clustered residuals signals spatial autocorrelation, implying that HDB prices are influenced by local neighbourhood effects beyond the global OLS assumptions. This suggests that spatial models (e.g., GWR or spatial lag/error models) may better capture underlying patterns.\n\nOverall, this residual map helps diagnose model limitations and highlights geographic areas where predictive accuracy can be improved.\n\n## GWR Modelling\n\n### Data prep\n\nRandomly sample up to 5,000 training points\n\nWe limit the GWR training sample to 5,000 points because GWR is computationally heavy—it fits a local regression at every data point, making runtime and memory usage grow rapidly with larger datasets. A 5,000-point sample provides sufficient spatial coverage across Singapore while keeping bandwidth selection and model fitting fast, stable, and computationally feasible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)  # reproducible sampling\n\nn_target <- 5000   # maximum allowed size for GWR\n\nif (nrow(HDB_train_sf) > n_target) {\nHDB_train_sf_sub <- HDB_train_sf %>%\ndplyr::slice_sample(n = n_target)\n} else {\nHDB_train_sf_sub <- HDB_train_sf\n}\n\nnrow(HDB_train_sf_sub)  # check actual sample size\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5000\n```\n\n\n:::\n:::\n\n\n### Select optimal GWR bandwidth\n\nThis code uses bw.gwr() to automatically select the optimal bandwidth for the GWR model. The formula specifies resale price and all predictor variables, while data = HDB_train_sp_sub supplies the sampled training points. A Gaussian kernel and adaptive bandwidth are used, meaning each location uses a variable number of neighbours. longlat = FALSE ensures distances are computed in the SVY21 projected coordinate system. The resulting bw_gwr is the best-fitting bandwidth for the GWR model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_gwr <- bw.gwr(\nformula = resale_price ~\nfloor_area_sqm + storey_mid + remaining_lease_yrs + flat_model +\nproximity_to_cbd_km + WITHIN_350M_BUSSTOP + WITHIN_350M_ELDERCARE +\ndist_good_ps_km + dist_mrt_km + dist_park_km + dist_mall_km +\ndist_hawker_km + WITHIN_350M_CHILDCARE + WITHIN_350M_CHAS,\ndata = HDB_train_sp_sub,\nkernel = 'gaussian',\nadaptive = TRUE,\nlonglat = FALSE\n)\nbw_gwr\n```\n:::\n\n\n\n\n\n\n### Fit GWR model on sampled training set\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_fit <- gwr.basic(\nformula  = resale_price ~\nfloor_area_sqm + storey_mid + remaining_lease_yrs + flat_model +\nproximity_to_cbd_km + WITHIN_350M_BUSSTOP + WITHIN_350M_ELDERCARE +\ndist_good_ps_km + dist_mrt_km + dist_park_km + dist_mall_km +\ndist_hawker_km + WITHIN_350M_CHILDCARE + WITHIN_350M_CHAS,\ndata     = HDB_train_sp_sub,\nbw       = bw_gwr,\nkernel   = \"gaussian\",\nadaptive = TRUE,\nlonglat  = FALSE\n)\n\n\n# Save GWR model\nsaveRDS(gwr_fit, file = \"data/rds/gwr_fit.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_fit <- readRDS(\"data/rds/gwr_fit.rds\")\n\n# Diagnostics\ngwr_fit$GW.diagnostic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$RSS.gw\n[1] 9.381191e+12\n\n$AIC\n[1] 121269.7\n\n$AICc\n[1] 121632.9\n\n$enp\n[1] 397.1924\n\n$edf\n[1] 4602.808\n\n$gw.R2\n[1] 0.9288558\n\n$gwR2.adj\n[1] 0.9227152\n\n$BIC\n[1] 118657.6\n```\n\n\n:::\n:::\n\n\n### Use GWR Model to Predict on Test Data\n\n#### Convert test set to Spatial\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_test_sp <- as(HDB_test_sf, \"Spatial\")\n```\n:::\n\n\n#### Predict using the fitted GWR model (gwr_fit)\n\nIn code chunks below - A GWR formula (`gwr_formula`) is defined with `resale_price` as the dependent variable and multiple structural and locational predictors on the right-hand side. - Variables include attributes like `floor_area_sqm`, `storey_mid`, and distances to amenities such as `dist_mrt_km`, `dist_park_km`, and `WITHIN_350M_CHILDCARE`. - `gwr_vars` extracts all variable names on the RHS of the formula using `all.vars()` and excludes the dependent variable using `[-1]`. - `test_cols` retrieves the column names of the `HDB_test_sp@data` SpatialPointsDataFrame, which will be used to apply the trained GWR model. - The `setdiff()` function compares `gwr_vars` against `test_cols` to find any missing predictor columns in the test set. - This acts as a **safeguard** to ensure the test data contains all required variables for prediction, avoiding runtime errors in GWR modelling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_formula <- resale_price ~\n  floor_area_sqm + storey_mid + remaining_lease_yrs +\n  proximity_to_cbd_km + WITHIN_350M_BUSSTOP + WITHIN_350M_ELDERCARE +\n  dist_good_ps_km + dist_mrt_km + dist_park_km + dist_mall_km +\n  dist_hawker_km + WITHIN_350M_CHILDCARE + WITHIN_350M_CHAS\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# variables used on the RHS of the formula\ngwr_vars <- all.vars(gwr_formula)[-1]   # drop response\n\n# columns in your test SpatialPointsDataFrame\ntest_cols <- names(HDB_test_sp@data)\n\nsetdiff(gwr_vars, test_cols)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncharacter(0)\n```\n\n\n:::\n:::\n\n\nThe code chunk below does the following - `vars_all` stores all variables required for GWR: both the response (`resale_price`) and all predictors from `gwr_vars`. - The `@data` slot of the `HDB_test_sp` SpatialPointsDataFrame is extracted and a `row_id` is added to preserve row positions after filtering. - `test_df` keeps only the necessary columns (`row_id` + `vars_all`) to be used for prediction. - `test_df_clean` filters out any rows that contain missing values in the selected columns using `complete.cases()`. - The `valid_rows` vector stores row indices of complete observations and is used to subset `HDB_test_sp` into `HDB_test_sp_clean`, which is safe for GWR prediction.\n\n-   The second chunk (set to not evaluate with `eval: false`) calls `gwr.predict()` to make predictions on the cleaned test spatial data, using the trained model from `HDB_train_sp_sub` and a bandwidth `bw_gwr`.\n-   The predicted prices are stored in a new column `gwr_pred_price` in the original `hdb_test` dataframe.\n-   Only the rows corresponding to `valid_rows` are populated with predicted values to maintain alignment with the full test dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# All variables needed for GWR (response + predictors)\nvars_all <- c(\"resale_price\", gwr_vars)\n\n# Work on the data slot of HDB_test_sp\ntest_df <- HDB_test_sp@data %>%\n  mutate(row_id = row_number()) %>%\n  select(row_id, all_of(vars_all))\n\n# Keep only complete rows\ntest_df_clean <- test_df %>%\n  filter(complete.cases(across(all_of(vars_all))))\n\nvalid_rows <- test_df_clean$row_id\n\n# Subset SpatialPointsDataFrame to these rows\nHDB_test_sp_clean <- HDB_test_sp[valid_rows, ]\n```\n:::\n\n\n-   This code chunk (set to not evaluate with `eval: false`) calls `gwr.predict()` to make predictions on the cleaned test spatial data, using the trained model from `HDB_train_sp_sub` and a bandwidth `bw_gwr`.\n-   The predicted prices are stored in a new column `gwr_pred_price` in the original `hdb_test` dataframe.\n-   Only the rows corresponding to `valid_rows` are populated with predicted values to maintain alignment with the full test dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_pred <- gwr.predict(\n  formula     = gwr_formula,\n  data        = HDB_train_sp_sub,\n  predictdata = HDB_test_sp_clean,\n  bw          = bw_gwr,\n  kernel      = \"gaussian\",\n  adaptive    = TRUE,\n  longlat     = FALSE\n)\n\n# Add predictions back to hdb_test\nhdb_test$gwr_pred_price <- NA_real_\nhdb_test$gwr_pred_price[valid_rows] <- gwr_pred$SDF$prediction\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(HDB_test_sp)        # original test size\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1607\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(HDB_test_sp_clean)  # rows used for GWR prediction\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1607\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_pred <- readRDS(\"data/rds/gwr_pred.rds\")\nHDB_test_results <- readRDS(\"data/rds/hdb_test_with_gwr_pred.rds\")\n```\n:::\n\n\n### Evaulate the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Metrics)\n\nidx <- !is.na(HDB_test_results$gwr_pred_price)\n\nrmse_gwr <- rmse(HDB_test_results$resale_price[idx],\n                 HDB_test_results$gwr_pred_price[idx])\n\nmae_gwr  <- mae(HDB_test_results$resale_price[idx],\n                HDB_test_results$gwr_pred_price[idx])\n\nr2_gwr   <- 1 - sum((HDB_test_results$resale_price[idx] -\n                     HDB_test_results$gwr_pred_price[idx])^2) /\n                 sum((HDB_test_results$resale_price[idx] -\n                      mean(HDB_test_results$resale_price[idx]))^2)\n\nrmse_gwr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 56688.97\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_gwr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 40018.52\n```\n\n\n:::\n\n```{.r .cell-code}\nr2_gwr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8940655\n```\n\n\n:::\n:::\n\n\n### Compute Moran’s I for GWR residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_test_results_sf <- HDB_test_sf %>%\n  mutate(\n    gwr_pred_price = HDB_test_results$gwr_pred_price,\n    gwr_residual   = resale_price - gwr_pred_price\n  )\n\ncoords_test <- st_coordinates(HDB_test_results_sf)\nnb_test <- knn2nb(knearneigh(coords_test, k = 8))\nlw_test <- nb2listw(nb_test, style = \"W\")\n\nmoran.test(HDB_test_results_sf$gwr_residual, lw_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  HDB_test_results_sf$gwr_residual  \nweights: lw_test    \n\nMoran I statistic standard deviate = 19.489, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.227478009      -0.000622665       0.000136988 \n```\n\n\n:::\n:::\n\n\nThe Moran’s I statistic for the GWR residuals is 0.227 (p \\< 0.001), substantially lower than the OLS residual Moran’s I of approximately 0.668. This indicates that GWR captures a significant portion of the spatial structure in HDB resale prices that the global OLS model fails to account for. While some positive spatial autocorrelation remains, the large reduction in Moran’s I demonstrates that geographically varying relationships—such as differing effects of proximity to amenities and structural attributes across neighbourhoods—play an important role in price formation. Therefore, GWR provides a more spatially appropriate residual pattern and better represents local market heterogeneity compared to OLS.\n\n### Mapping GWR Coefficient Surface (floor_area_sqm)\n\n#### Extract local coefficients from GWR fitted model\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_coef_sf <- HDB_train_sf_sub %>%\nmutate(floor_coef = gwr_fit$SDF$floor_area_sqm)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!exists(\"sg_outline\")) {\nsubzones <- st_read(\"data/rawdata/MasterPlan2019SubzoneBoundaryNoSeaKML.kml\", quiet = TRUE) %>%\nst_transform(3414)\nsg_outline <- subzones %>% summarise()\n}\n```\n:::\n\n\n#### Plot coefficient surface with tmap\nThis code chunk creates a scatterplot comparing actual and predicted resale prices for all four models.  \nA tibble (`compare_df`) is first constructed containing the actual prices and each model’s predictions.  \n`pivot_longer()` converts the data into long format so each model appears as a separate row.  \n`ggplot()` then plots actual vs. predicted prices, adds a 45-degree reference line to indicate perfect prediction,  \nand uses `facet_wrap()` to display one panel per model.  \nThe result visually shows how closely each model's predictions match the actual resale prices.\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\ntm_shape(sg_outline) +\ntm_polygons(col = \"grey95\", border.col = \"black\") +\ntm_shape(gwr_coef_sf) +\ntm_dots(\ncol = \"floor_coef\",\npalette = \"-RdBu\",\nstyle = \"quantile\",\nsize = 0.19,\ntitle = \"Coefficient\\n(floor_area_sqm)\"\n) +\ntm_layout(\ntitle = \"Local GWR Coefficients for Floor Area (sqm)\",\nlegend.outside = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\nThe GWR coefficient map shows that the influence of floor area on HDB resale prices varies noticeably across Singapore. In central and mature estates such as Toa Payoh, Bishan, Kallang–Whampoa, and parts of Queenstown, coefficients are highest, indicating that buyers pay a significantly larger premium for additional space. These areas have strong accessibility, mature amenities, and limited supply of larger flats, which amplifies the marginal value of floor area.\n\nIn contrast, lower coefficients are observed in Sengkang, Punggol, Yishun, Jurong West, and Woodlands. Here, adding more space contributes less to the overall price. These towns have a higher supply of large flats and more uniform building typologies, reducing the scarcity value of size. Buyers in these areas may also be more price-sensitive, placing greater emphasis on affordability or flat age rather than spaciousness.\n\nOverall, the spatial variation highlights that size does not influence resale prices uniformly. GWR reveals these locally varying relationships, demonstrating that a single global model (like OLS) cannot fully capture differences in housing market behaviour across neighbourhoods.\n\n## Non Spatial Random Forest\n\n### Define predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrf_formula <- resale_price ~\nfloor_area_sqm +\nstorey_mid +\nremaining_lease_yrs +\nflat_model +\nproximity_to_cbd_km +\nWITHIN_350M_BUSSTOP +\nWITHIN_350M_ELDERCARE +\ndist_good_ps_km +\ndist_mrt_km +\ndist_park_km +\ndist_mall_km +\ndist_hawker_km +\nWITHIN_350M_CHILDCARE +\nWITHIN_350M_CHAS\n```\n:::\n\n\n### Set up cross-validation and tuning grid\n\nThis code chunk prepares the Random Forest model for training and hyperparameter tuning.  \n`trainControl()` sets up 5-fold cross-validation, ensuring the model is evaluated on five different train–validation splits for reliable performance.  \nThe `expand.grid()` block defines the hyperparameter search space:  \n- `mtry` controls how many predictors are considered at each split,  \n- `splitrule = \"variance\"` specifies the regression splitting criterion, and  \n- `min.node.size` sets the minimum number of samples allowed in terminal nodes.  \nThese combinations are systematically tested to identify the best-performing Random Forest model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\n#5-fold cross-validation\n\nrf_ctrl <- trainControl(\nmethod = \"cv\",\nnumber = 5,\nverboseIter = FALSE\n)\n\n#Hyperparameter grid for calibration\n\nrf_grid <- expand.grid(\nmtry = c(3, 5, 7, 9), # number of variables tried at each split\nsplitrule = \"variance\", # regression split rule\nmin.node.size = c(5, 10, 20) # minimum node size\n)\n```\n:::\n\n\n### Train and calibrate the Random Forest\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\nrf_model <- train(\nrf_formula,\ndata = hdb_train,\nmethod = \"ranger\",\ntrControl = rf_ctrl,\ntuneGrid = rf_grid,\nimportance = \"permutation\",\nnum.trees = 500\n)\n\nrf_model\nrf_model$bestTune\n```\n:::\n\n\n\n\n\n\n### Predict on the test set (Jul–Sep 2025)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_test$rf_pred_price <- predict(rf_model, newdata = hdb_test)\n```\n:::\n\n\n### Evaluate Random Forest predictive performance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse_rf <- rmse(hdb_test$resale_price, hdb_test$rf_pred_price)\nmae_rf <- mae(hdb_test$resale_price, hdb_test$rf_pred_price)\nr2_rf <- 1 - sum((hdb_test$resale_price - hdb_test$rf_pred_price)^2) /\nsum((hdb_test$resale_price - mean(hdb_test$resale_price))^2)\n\nrmse_rf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 48516.74\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_rf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33832.05\n```\n\n\n:::\n\n```{.r .cell-code}\nr2_rf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9224068\n```\n\n\n:::\n:::\n\n\n## Geographically Weighted Random Forest (GRF)\n\n### Response + predictor variables from the RF formula\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrf_vars <- all.vars(rf_formula)\nresp_var <- grf_vars[1] # \"resale_price\"\npred_vars <- grf_vars[-1]\n```\n:::\n\n\n### Training dataframe for GRF (no geometry)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_train_grf <- HDB_train_sf_sub %>%\nsf::st_drop_geometry() %>%\ndplyr::select(all_of(c(resp_var, pred_vars)))\n```\n:::\n\n\n### Coordinates matrix (X, Y) for GRF\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_grf <- sf::st_coordinates(HDB_train_sf_sub)\n\nnrow(hdb_train_grf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5000\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(hdb_train_grf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 15\n  resale_price floor_area_sqm storey_mid remaining_lease_yrs flat_model       \n         <dbl>          <dbl>      <dbl>               <dbl> <chr>            \n1       723000            121         11                59.8 Improved         \n2       725000            122          5                63   Improved         \n3       630000            110          5                79.2 Improved         \n4       600000            121          2                62.2 Improved         \n5       718000            114          5                74.4 Premium Apartment\n6       660000            110          2                75.1 Improved         \n# ℹ 10 more variables: proximity_to_cbd_km <dbl>, WITHIN_350M_BUSSTOP <int>,\n#   WITHIN_350M_ELDERCARE <int>, dist_good_ps_km <dbl>, dist_mrt_km <dbl>,\n#   dist_park_km <dbl>, dist_mall_km <dbl>, dist_hawker_km <dbl>,\n#   WITHIN_350M_CHILDCARE <int>, WITHIN_350M_CHAS <int>\n```\n\n\n:::\n:::\n\n\n### Select optimal GRF bandwidth\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ngrf_bw <- grf.bw(\nformula = rf_formula,\ndataset = hdb_train_grf,\ncoords = coords_grf,\nkernel = \"adaptive\",\nbw.min = 50,\nbw.max = 400,\nstep = 25,\ntrees = 500,\nimportance = \"impurity\",\nnthreads = parallel::detectCores() - 1,\nforests = FALSE,\ngeo.weighted = TRUE\n)\n\ngrf_bw$best.bw\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_bw_grf <- readRDS(\"data/rds/grf_bw.rds\")\nbest_bw_grf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$tested.bandwidths\n   Bandwidth     Local     Mixed Low.Local\n1         50 0.9140903 0.9313112 0.9316935\n2         75 0.9143966 0.9311321 0.9316947\n3        100 0.9171320 0.9320021 0.9319640\n4        125 0.9154287 0.9304529 0.9307692\n5        150 0.9172032 0.9316580 0.9316459\n6        175 0.9138452 0.9299943 0.9307901\n7        200 0.9158190 0.9306703 0.9311130\n8        225 0.9164577 0.9309731 0.9313181\n9        250 0.9153531 0.9306319 0.9310358\n10       275 0.9176045 0.9316450 0.9317014\n11       300 0.9176359 0.9311554 0.9309753\n12       325 0.9167732 0.9309497 0.9310654\n13       350 0.9161017 0.9303807 0.9308573\n14       375 0.9188630 0.9316298 0.9312517\n15       400 0.9158975 0.9304794 0.9309105\n\n$Best.BW\n[1] 375\n```\n\n\n:::\n:::\n\n\n### Fit GRF model on the training set\n\nUsing the optimal bandwidth, we calibrate the geographically weighted random forest. The fitted object contains both a global RF and a set of local RF models, plus local goodness-of-fit and variable importance metrics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\ngrf_fit <- grf(\nformula = rf_formula,\ndframe = hdb_train_grf,\nbw = 375,\nkernel = \"adaptive\",\ncoords = coords_grf,\nntree = 500,\nmtry = NULL, # default p/3\nimportance = \"impurity\",\nnthreads = parallel::detectCores() - 1,\nforests = TRUE, # TRUE if you want all local forests\ngeo.weighted = TRUE,\nprint.results = TRUE\n)\n\nsaveRDS(grf_fit, \"data/rds/grf_fit.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrf_fit <- readRDS(\"data/rds/grf_fit.rds\")\n```\n:::\n\n\nQuick look at local goodness-of-fit summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(grf_fit) <- c(\"GRF\", \"list\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(grf_fit)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(grf_fit$LGofFit)\nhead(grf_fit$lModelSummary)\n```\n:::\n\n\n### Predict with GRF on the test set (Jul–Sep 2025)\n\nWe now use predict.grf() to obtain spatially varying predictions on the test period, using the nearest local RF model for each test location.\n\n#### Test predictors and coordinates\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Drop geometry but keep all predictors\ntest_data_nogeom <- HDB_test_sf %>%\n  sf::st_drop_geometry()\n\n# 2. Add X / Y columns from the sf geometry\ncoords_test <- sf::st_coordinates(HDB_test_sf)\ntest_data_nogeom$X <- coords_test[, 1]\ntest_data_nogeom$Y <- coords_test[, 2]\n```\n:::\n\n\n#### GRF predictions (resale_price)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrf_pred <- predict.grf(\n  grf_fit,\n  test_data_nogeom,\n  x.var.name = \"X\",\n  y.var.name = \"Y\",\n  local.w    = 1,\n  global.w   = 0\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_test_results_grf <- hdb_test %>%\n  dplyr::mutate(grf_pred_price = as.numeric(grf_pred))\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_test_results_grf <- readr::read_rds(\"data/rds/HDB_test_results_grf.rds\")\n```\n:::\n\n\n### Metrics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse_grf <- rmse(HDB_test_results_grf$resale_price,\nHDB_test_results_grf$grf_pred_price)\n\nmae_grf <- mae(HDB_test_results_grf$resale_price,\nHDB_test_results_grf$grf_pred_price)\n\nr2_grf <- 1 - sum((HDB_test_results_grf$resale_price -\nHDB_test_results_grf$grf_pred_price)^2) /\nsum((HDB_test_results_grf$resale_price -\nmean(HDB_test_results_grf$resale_price))^2)\n\nrmse_grf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 123421.2\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_grf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 94785.11\n```\n\n\n:::\n\n```{.r .cell-code}\nr2_grf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4978656\n```\n\n\n:::\n:::\n\n\n## Comparison of models\n\n### Summary table of model performance\nThis code  chunk creates a summary table comparing the performance of all four models.  \nA tibble (`model_metrics`) stores RMSE, MAE, and R² values for OLS, GWR, Random Forest, and Geographically Weighted RF.  \nThe table is then sorted by RMSE and formatted using `gt()`, which rounds the numeric values and adds a title and subtitle.  \nThe result is a clean, publication-ready performance summary table suitable for reporting and analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_metrics <- tibble::tibble(\nModel = c(\"OLS\", \"GWR\", \"Random Forest\", \"Geog. Weighted RF\"),\nRMSE = c(rmse_ols, rmse_gwr, rmse_rf, rmse_grf),\nMAE = c(mae_ols, mae_gwr, mae_rf, mae_grf),\nR2 = c(r2_ols, r2_gwr, r2_rf, r2_grf)\n)\n\nmodel_metrics %>%\narrange(RMSE) %>%\ngt() %>%\nfmt_number(columns = c(RMSE, MAE), decimals = 0) %>%\nfmt_number(columns = R2, decimals = 3) %>%\ntab_header(title = \"Predictive Performance Across Models\",\nsubtitle = \"Test period: Jul–Sep 2025\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"osncjrvket\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#osncjrvket table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#osncjrvket thead, #osncjrvket tbody, #osncjrvket tfoot, #osncjrvket tr, #osncjrvket td, #osncjrvket th {\n  border-style: none;\n}\n\n#osncjrvket p {\n  margin: 0;\n  padding: 0;\n}\n\n#osncjrvket .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#osncjrvket .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#osncjrvket .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#osncjrvket .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#osncjrvket .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#osncjrvket .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#osncjrvket .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#osncjrvket .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#osncjrvket .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#osncjrvket .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#osncjrvket .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#osncjrvket .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#osncjrvket .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#osncjrvket .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#osncjrvket .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#osncjrvket .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#osncjrvket .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#osncjrvket .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#osncjrvket .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#osncjrvket .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#osncjrvket .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#osncjrvket .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#osncjrvket .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_left {\n  text-align: left;\n}\n\n#osncjrvket .gt_center {\n  text-align: center;\n}\n\n#osncjrvket .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#osncjrvket .gt_font_normal {\n  font-weight: normal;\n}\n\n#osncjrvket .gt_font_bold {\n  font-weight: bold;\n}\n\n#osncjrvket .gt_font_italic {\n  font-style: italic;\n}\n\n#osncjrvket .gt_super {\n  font-size: 65%;\n}\n\n#osncjrvket .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#osncjrvket .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#osncjrvket .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#osncjrvket .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#osncjrvket .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#osncjrvket .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#osncjrvket .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#osncjrvket .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#osncjrvket div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Predictive Performance Across Models</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Test period: Jul–Sep 2025</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Model\">Model</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"RMSE\">RMSE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MAE\">MAE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"R2\">R2</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">Random Forest</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">48,517</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">33,832</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.922</td></tr>\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">GWR</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">56,689</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">40,019</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.894</td></tr>\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">OLS</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">81,412</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">58,785</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.782</td></tr>\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">Geog. Weighted RF</td>\n<td headers=\"RMSE\" class=\"gt_row gt_right\">123,421</td>\n<td headers=\"MAE\" class=\"gt_row gt_right\">94,785</td>\n<td headers=\"R2\" class=\"gt_row gt_right\">0.498</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n### Bar chart comparison of RMSE / MAE / R²\nThis code chunk reshapes the model performance table into a long format using `pivot_longer()`, so each metric (RMSE, MAE, R²) becomes a separate row.  \nA bar chart is then created using `ggplot2` to display model performance side-by-side.  \n`facet_wrap()` creates individual panels for each metric, allowing easy comparison across models.  \n`geom_text()` overlays the numeric values on top of each bar to enhance readability.  \nThe plot is styled with a minimal theme, angled x-axis labels for clarity, and bold facet titles.  \nThis produces a clean and visually effective comparison of model performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetrics_long <- model_metrics %>%\ntidyr::pivot_longer(\ncols = c(RMSE, MAE, R2),\nnames_to = \"Metric\",\nvalues_to = \"Value\"\n)\n\nggplot(metrics_long, aes(x = Model, y = Value)) +\ngeom_col() +\nfacet_wrap(~ Metric, scales = \"free_y\") +\ngeom_text(aes(label = round(Value, ifelse(Metric == \"R2\", 3, 0))),\nvjust = -0.4, size = 3) +\nlabs(\ntitle = \"Model Performance Comparison\",\nx = NULL,\ny = NULL\n) +\ntheme_minimal(base_size = 11) +\ntheme(\nstrip.text = element_text(face = \"bold\"),\naxis.text.x = element_text(angle = 20, hjust = 1)\n)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/bar chart-1.png){width=672}\n:::\n:::\n\nThe bar graph compares the out-of-sample performance of four models on HDB resale prices for Jul–Sep 2025. Random Forest (RF) is the best-performing model, achieving the lowest RMSE (48,468) and lowest MAE (33,798), with the highest R² (0.923). This indicates that a non-spatial, nonlinear ensemble can already capture most of the variation in resale prices by flexibly modelling interactions between structural and locational variables.\n\nThe Geographically Weighted Regression (GWR) model performs second best, with RMSE 56,689, MAE 40,019, and R² 0.894. GWR improves clearly over the global OLS model, confirming that allowing coefficients to vary across space helps capture local housing market differences, even within a linear framework.\n\nThe OLS model yields RMSE 81,416, MAE 58,802, and R² 0.781. Although it provides a reasonable baseline, its lower R² and higher errors reflect the limitations of a single global linear relationship in the presence of spatial heterogeneity and nonlinear effects.\n\nFinally, the Geographically Weighted Random Forest (GRF) performs the weakest (RMSE 123,421, MAE 94,785, R² 0.498) in this implementation. This suggests that the added model complexity and local forest fitting did not translate into better generalisation on the test period—likely due to bandwidth choice, overfitting to local noise, or the relatively limited sample size for each local model.\n\nOverall, these results indicate that a well-tuned global Random Forest provides the most accurate and stable predictions, while GWR offers a strong spatially explicit alternative that still outperforms traditional OLS.\n\n\n### Actual vs predicted scatter by model\nThis code  chunk creates a scatterplot comparing actual and predicted resale prices for all four models.  \nA tibble (`compare_df`) is first constructed containing the actual prices and each model’s predictions.  \n`pivot_longer()` converts the data into long format so each model appears as a separate row.  \n`ggplot()` then plots actual vs. predicted prices, adds a 45-degree reference line to indicate perfect prediction,  \nand uses `facet_wrap()` to display one panel per model.  \nThe result visually shows how closely each model's predictions match the actual resale prices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_df <- tibble::tibble(\nresale_price = HDB_test_results_grf$resale_price,\nOLS = HDB_test_results$pred_price,\nGWR = HDB_test_results$gwr_pred_price,\n`Random Forest` = hdb_test$rf_pred_price,\n`Geog. Weighted RF` = HDB_test_results_grf$grf_pred_price\n)\n\ncompare_long <- compare_df %>%\ntidyr::pivot_longer(\ncols = -resale_price,\nnames_to = \"Model\",\nvalues_to = \"pred_price\"\n) %>%\nfilter(!is.na(pred_price))\n\nggplot(compare_long,\naes(x = resale_price, y = pred_price)) +\ngeom_point(alpha = 0.4) +\ngeom_abline(slope = 1, intercept = 0, linetype = \"dashed\") +\nfacet_wrap(~ Model, scales = \"free\") +\nscale_x_continuous(labels = scales::comma) +\nscale_y_continuous(labels = scales::comma) +\nlabs(\ntitle = \"Actual vs Predicted HDB Resale Prices\",\nx = \"Actual price (SGD)\",\ny = \"Predicted price (SGD)\"\n) +\ntheme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex03_files/figure-html/unnamed-chunk-91-1.png){width=672}\n:::\n:::\n\nThe scatterplots provide a visual assessment of how well each model predicts resale prices for the Jul–Sep 2025 test period. The 45-degree dashed line represents perfect prediction, where predicted values exactly match actual transaction prices. Deviations from this line indicate under- or over-prediction.\n\nThe Random Forest model exhibits the tightest clustering around the reference line, reflecting its strong predictive performance. Most points lie very close to the 45-degree line across the full price range (approximately $600,000 to $1.6 million), indicating that the RF model captures nonlinear effects and complex interactions effectively. This visual pattern aligns with its top performance metrics (lowest RMSE and highest R²).\n\nThe GWR model also shows relatively close alignment to the reference line, though with slightly wider dispersion than Random Forest. While GWR captures spatial heterogeneity well, its linear structure limits its ability to fully model nonlinear price dynamics, leading to moderate under- and over-prediction in mid- and high-priced units.\n\nThe OLS model shows noticeably larger spread around the reference line, indicating weaker predictive accuracy. High-priced transactions above $1.2 million tend to be systematically under-predicted, suggesting that a global linear specification does not accommodate varying relationships across neighbourhoods or price tiers. This visual pattern aligns with OLS having the third-best R² and higher errors.\n\nThe Geographically Weighted Random Forest (GRF) shows the weakest fit, with a wide horizontal spread and clear bias in the upper price ranges where predictions flatten. This suggests that the GRF configuration used may be overfitting to local noise or using suboptimal bandwidth settings, resulting in poorer generalisation.\n\nOverall, the scatterplots reinforce the quantitative results: Random Forest provides the most accurate and stable predictions, while GWR improves over OLS but remains limited by linearity. GRF underperforms in this implementation, indicating that additional tuning may be required for effective spatial machine learning.\n\n\n\n",
    "supporting": [
      "Take_Home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}