---
title: "In class Exercise 4"
author: "Gautamgovan"
date: "September 13, 2025"
date-modified: "last-modified"
format: 
  html:
    toc: true
    number-sections: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---
## Load Packages

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr,GWmodel,ggstatsplot)
```
## Data Wrangling
```{r}
hunan <- st_read(dsn = "C:/govanzz/ISSS626_GEO_AUG_2025/In-class_Exercise/In-class_Ex04/Data/geospatial", 
                 layer = "Hunan")
```
```{r}
hunan2012 <- read_csv("C:/govanzz/ISSS626_GEO_AUG_2025/In-class_Exercise/In-class_Ex04/Data/aspatial/Hunan_2012.csv")
```
```{r}
hunan <- left_join(hunan,hunan2012) %>%
  select(1:3, 7, 15,16,31,32)
```
## Geographically weighted Summary Statistics
### Cross Validation
```{r}
bw_CV <- bw.gwr(GDPPC ~ 1,
                data = hunan,
                approach = "CV",
                adaptive = FALSE,
                kernel = "bisquare",
                longlat = T)

bw_CV
```
```{r}
bw_AIC <- bw.gwr(GDPPC ~ 1,
                data = hunan,
                approach = "AIC",
                adaptive = FALSE,
                kernel = "bisquare",
                longlat = T)

bw_AIC
```
```{r}
# Convert sf to Spatial
hunan_sp <- as(hunan, "Spatial")

# Then run gwss on hunan_sp
gwstat <- gwss(data = hunan_sp,
               vars = "GDPPC",
               bw = bw_AIC,
               kernel = "bisquare",
               adaptive = FALSE,
               longlat = T)

```

```{r}
# Convert gwss SDF output into a data frame
gwstat_df <- as.data.frame(gwstat$SDF)
```

```{r}
# Append the newly derived data.frame onto hunan_sf
hunan_gstat <- cbind(hunan, gwstat_df)
```

### Plotting and Visualisation
```{r}
# Plot geographically weighted mean
tm_shape(hunan_gstat) +
  tm_fill("GDPPC_LM",           
          style = "quantile",
          palette = "Blues",
          title = "GW Mean of GDPPC") +
  tm_borders(alpha = 0.5)
```
